$$Y = C + I_g + C + Nx$$
$$I_d = I_n + d, Nx = Ex - Im$$
Классическая ветвь экономической науки - саморегулирование рынка.

Великая Депрессия - кризис классической теории.

Кейнс. Внутри рынка нет механизмов обеспечения макроэкономического равновесия. Разработка основ антикризисного регулирования.

70-e - разочарование в кейнсианстве, неспособность остановить рост безработицы и инфляции. Было замечено, что рост инфляции и рост безработицы обратно зависимы(кривая Филипса).

Неоклассика конца XIX века - реакция на теорию Карла Маркса, Альфред Маршал.

Неоклассика конца XX века - экономика предложения(Лафер), цель которой - снижение налогов, повышение льгот корпорациям, сокращение дефицита госбюджета. Теория рациональных ожиданий - люди
ведут себя рационально. Теория общественного выбора, вторжение экономических инструментов в процесс принятия политических решений. Неолиберализм - принцип саморегулирования экономики. Хаек -
"Дорога к рабству".

Монетаризм - неоконсервативная теория, исходящая из решающего влияния денежной массы на процессы инфляции, государство только мешает экономике, единственное его место - кредитно-денежное
обращение. Монетарное правило - ЦБ обязан поддерживать рост количества денег в обращении независимо от циклов хозяйства. Модель Манделла-Флеминга.

Институционализм. Основоположник - Вебер. Институты - корпорации, государство, и т. д. Неоинституционализм.
* Основные экономические агенты и институты
Домашнее хозяйство, фирма, правительство, cобственность, рынок, деньги

Первые три института являются автономными и становятся агентами.

Фирма возникает как реакция на дороговизну ресурсов.

Теория общественного выбора: общество представляется как совокупность людей с частными интересами.

Домохозяйство принимает решения о потреблении благ для поддержания собственного существования. Натуральное и товарное хозяйства. Доходная часть семьи может состоять из денежных и натуральных
доходов. Денежные доходы: зарплаты, соцвыплаты, доходы от предпринимательской деятельности, доходы от реализации имущества. Номинальный доход - сумма денег, полученная хозяйством за период,
реальные - то же, но в натуральной форме. Располагаемый доход - номинальный доход за вычетом налогов.

Расходы: личные потребительские расходы, налоги и прочие обязательные платежи, накопления/сбережения/акции/облигации. Закон Энгеля. Уровень жизни - структура потребностей и их обеспечение.
Качество жизни != уровень жизни. Минимальные социальные стандарты - законодательно закреплённые стандарты потребления благ.

Фирма(предприятие) появилась в результате отделения от домашнего хозяйства процесса производства. Признаки:
1. Цель создания - производство и продажа.
2. Покупка факторов производства.
3. Направленность - извлечение прибыли.
Типы фирм:
1. ИП
2. Товарищество/партнёрство
3. Акционерное общество(корпорация)

Государство - агент, принимающий решения о перераспределении благ в обществе.
