1. Яковлева Ксения Владимировна,  ksusha_yakovleva@mail.ru

1 кр в середине курса. РБК, известия, ведомости. Рейтинговая система + экзамен.
Семинары - философия-style, вопросы + статьи.

4 блока: введение, микроэкономика, макроэкономика, ввп.

Лектор Ильин-Минкевич ВладИслав Игоревич.

* Общие проблемы экономического развития

** Экономика - наука и хозяйство

1. Понятия и структура экономики.
Изначальная трактовка - искусство ведения домашнего хозяйства.

Экономика как хозяйство - инструмент для распределения ресурсов и поддержки
жизнеобеспечения людей.
Экономика как наука - совокупность накопленных знаний о ведении хозяйства и
соответствующих отношений, возникающих при этом.

Микроэкономика - исследование отдельных объектов.
Мезоэкономика - Региональная/отраслевая экономика.
Макроэкономика - исследование системы в целом.
Мегаэкономика - международная система.

Экономическая теория - синтез научного и вненаучного знания.

Границы экономической теории - ?
Предмет экономики - поведение человеков в процессах производства, распределения,
обмена и потребления.

Потребность - нужда как мотиватор. Первичные(низшие) и вторичные(высшие) потребности.

Благо - всё то, что представляет полезность. Антиблаго - всё то, что общество
не желает присваивать. Блага комплементарные и субституты, одноразовые/многоразовые,
прямые/хранимые, частные/общественные.

Потребительская ценность блага - ценность для потребителя.
Стоимость блага как цели - альтернативные издержки.
Экономическое благо - ограниченное благо.
Интерес. Ресурс - косвенное благо. Ресурсы, непосредственно учавствующие в
производстве, называются факторами производства. L - трудовые, T - природные,
K - капитал, информация, предпринимательский талант.
