#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+OPTIONS: toc:nil
* Задача 1194
Найти поверхность, удовлетворяющую уравнению:
$$y^2\frac{\partial{z}}{\partial{x}} + xy\frac{\partial{z}}{\partial{y}} = x$$
и проходящую через линию:
$$x = 0,\, z = y^2$$

УЧП соответствует системе:
$$\frac{dx}{y^2} = \frac{dy}{xy} = \frac{dz}{x}\, (1 = 2 = 3)$$
Найдём первые интегралы:
$$1 = 2 \Rightarrow xydx = y^2dy \Rightarrow d(x^2) = d(y^2) \Rightarrow x^2 - y^2 = C_1$$
$$2 = 3 \Rightarrow \frac{dy}{y} = dz \Rightarrow d(\ln{y}) = dz \Rightarrow z - \ln{y} = C_2$$
Тогда общее решение имеет вид:
$$z - \ln{y} = F(x^2 - y^2)$$
где $F(x, y)$ - произвольная дифференцируемая функция от $x$ и $y$.

Подставим в это решение уравнение линии:
$$y^2 - \ln{y} = F(-y^2) \Rightarrow F(x) = -x + \ln{\sqrt{-x}}$$
Таким образом, решение имеет вид:
$$z = \ln{y} - x^2 + y^2 - \ln{\sqrt{x^2 - y^2}}$$

* Задача 1198
Найти поверхность, удовлетворяющую уравнению:
$$x\frac{\partial{z}}{\partial{x}} - y\frac{\partial{z}}{\partial{y}} = z^2(x - 3y)$$
и проходящую через линию:
$$x = 1,\, yz + 1 = 0$$

УЧП соответствует системе:
$$\frac{dx}{x} = \frac{dy}{-y} = \frac{dz}{z(x - 3y)}\, (1 = 2 = 3)$$
Найдём первые интегралы:
$$1 = 2 \Rightarrow \frac{dx}{x} = \frac{dy}{-y} \Rightarrow xy = C_1$$
$$1 \cdot z + 2 \cdot 3z = 3 \Rightarrow dx + 3dy = \frac{dz}{z} \Rightarrow x + 3y - \ln{|z|} = C_2$$
Подставим в эти выражения уравнение кривой, чтобы найти связь между $C_1$ и $C_2$:
\begin{equation*}
  \begin{cases}
    y = C_1,\\
    1 + 3y + \ln{|y|} = C_2
  \end{cases}
\end{equation*}
Откуда получаем:
$$C_2 = 1 + 3C_1 + \ln{|C_1|} \Rightarrow x + 3y - \ln{z} = 1 + 3xy + \ln{|xy|}$$
Или, выражая $z$ через $x$ и $y$:
$$z = \exp{(x + 3y - 1 - 3xy - \ln{|xy|})}$$

* Задача 1203
Найти поверхность, удовлетворяющую уравнению:
$$(y - z)\frac{\partial{z}}{\partial{x}} + (z - x)\frac{\partial{x}}{\partial{y}} = x - y$$
и проходящую через линию:
$$z = y = -x$$

УЧП соответствует системе:
$$\frac{dx}{y - z} = \frac{dy}{z - x} = \frac{dz}{x - y}\, (1 = 2 = 3)$$
Найдём первые интегралы:
$$1 + 2 = -3 \Rightarrow dx + dy = -dz \Rightarrow x + y + z = C_1$$
$$1 \cdot 2x + 2 \cdot 2y = -3 \cdot 2z \Rightarrow x^2 + y^2 + z^2 = C_2$$
Тогда общее решение имеет вид:
$$x^2 + y^2 + z^2 = F(x + y + z)$$
Где $F(x)$ - произвольная дифференцируемая функция.

Подставим в это соотношение уравнение кривой:
$$3x^2 = F(x)$$
Откуда итоговое решение имеет вид:
$$x^2 + y^2 + z^2 = 3(x + y + z)^2$$

* Задача 1204
Найти поверхность, удовлетворяющую уравнению:
$$x\frac{\partial{z}}{\partial{x}} + (xz + y)\frac{\partial{z}}{\partial{y}} = z$$
и проходящую через линию:
$$x + y = 2z,\, xz = 1$$

УЧП соответствует системе:
$$\frac{dx}{x} = \frac{dy}{xz + y} = \frac{dz}{z}\, (1 = 2 = 3)$$
Найдём первые интегралы:
$$1 = 3 \Rightarrow \frac{dx}{x} = \frac{dz}{z} \Rightarrow \frac{z}{x} = C_1$$
$$1 \cdot z + 3 \cdot x - 2 = 1 \Rightarrow \frac{xdz + zdx - dy}{xz - y} = \frac{dx}{x} \Rightarrow \frac{xz - y}{x} = C_2$$

Подставим в найденные первые интегралы уравнение кривой и найдём соотношение между $C_1$ и $C_2$:
\begin{equation*}
  \begin{cases}
    C_1 = \frac{1}{x^2},\\
    C_2 = 1 - \frac{y}{x} = 1 - \frac{2z - x}{x} = 2 - 2\frac{z}{x} = 2 - 2C_1
  \end{cases}
\end{equation*}

Откуда, подставляя значения первых интегралов, получаем:
$$\frac{xz - y}{x} = 2 - 2\frac{z}{x}$$

* Задача 1206
Найти поверхность, удовлетворяющую уравнению:
$$x\frac{\partial{z}}{\partial{x}} + z\frac{\partial{z}}{\partial{y}} = y$$
и проходящую через линию:
$$y = 2z,\, x + 2y = z$$

УЧП соответствует системе:
$$\frac{dx}{x} = \frac{dy}{z} = \frac{dz}{y}\, (1 = 2 = 3)$$
Найдём первые интегралы:
$$2 = 3 \Rightarrow ydy = zdz \Rightarrow z^2 - y^2 = C_1$$
$$1 = 2 + 3 \Rightarrow \frac{dx}{x} = \frac{dy + dz}{y + z} \Rightarrow \frac{y + z}{x} = C_2$$

Таким образом, общее решение имеет вид:
$$F\left(z^2 - y^2, \frac{y + z}{x}\right) = 0$$
Где $F(x, y)$ - произвольная дифференцируемая функция двух аргументов. Подставим в неё уравнение кривой,
предварительно преобразовав его:
\begin{equation*}
  \begin{cases}
    y = 2z,\\
    x = z - 2y = -3z
  \end{cases}
\end{equation*}
$$F(-3z^2, -1) = 0$$

Таким образом, уравнение искомой поверхности имеет вид:
\begin{equation*}
  \begin{cases}
    F\left(z^2 - y^2, \frac{y + z}{x}\right) = 0,\\
    F(-3x^2, -1) = 0
  \end{cases}
\end{equation*}

* Задача 1174
Найти общее решение уравнения:
$$xy\frac{\partial{z}}{\partial{x}} - x^2\frac{\partial{z}}{\partial{y}} = yz$$

УЧП соответствует системе:
$$\frac{dx}{xy} = \frac{dy}{x^2} = \frac{dz}{yz} \, (1 = 2 = 3)$$
Найдём первые интегралы:
$$1 = 2 \Rightarrow ydy = xdx \Rightarrow y^2 - x^2 = C_1$$
$$1 = 3 \Rightarrow \frac{dx}{x} = \frac{dz}{z} \Rightarrow \frac{z}{x} = C_2$$

Отсюда, общее решение имеет вид:
$$\frac{z}{x} = F(y^2 - x^2)$$
Где $F(x)$ - произвольная дифференцируемая функция.

* Задача 1186
Найти общее решение уравнения:
$$(y + z)\frac{\partial{u}}{\partial{x}} + (z + x)\frac{\partial{u}}{\partial{y}} + (x + y)\frac{\partial{u}}{\partial{z}} = u$$

УЧП соответствует системе:
$$\frac{dx}{y + z} = \frac{dy}{z + x} = \frac{dz}{x + y} = \frac{du}{u} \, (1 = 2 = 3 = 4)$$
Найдём первые интегралы:
$$1 + 2 + 3 = 4 \Rightarrow \frac{dx + dy + dz}{2(x + y + z)} = \frac{du}{u} \Rightarrow \frac{u^2}{x + y + z} = C_1$$
$$1 - 2 = 4 \Rightarrow \frac{dx - dy}{y - x} = \frac{du}{u} \Rightarrow u(x - y) = C_2$$
$$2 - 3 = 4 \Rightarrow \frac{dy - dz}{z - y} = \frac{du}{u} \Rightarrow u(y - z) = C_3$$

Таким образом, общее решение имеет вид:
$$F\left(\frac{u^2}{x + y + z}, u(x - y), u(y - z)\right) = 0$$
Где $F(x, y, z)$ - произвольная дифференцируемая функция.

* Задача 1209
Найти поверхность, удовлетворяющую уравнению:
$$xy^3\frac{\partial{z}}{\partial{x}} + x^2z^2\frac{\partial{z}}{\partial{y}} = y^3z$$
и проходящую через кривую:
$$x = -z^3, \, y = z^2$$

УЧП соответствует системе:
$$\frac{dx}{xy^3} = \frac{dy}{x^2z^2} = \frac{dz}{y^3z} \, (1 = 2 = 3)$$
Найдём первые интегралы:
$$1 = 3 \Rightarrow \frac{dx}{x} = \frac{dz}{z} \Rightarrow \frac{z}{x} = C_1$$
$$1 \cdot z + 3 \cdot x = 2 \Rightarrow \frac{zdx + xdz}{xy^2z} = \frac{dy}{x^2z^2} \Rightarrow xzd(xz) = y^2dy \Rightarrow \frac{x^2z^2}{2} - \frac{y^3}{3} = C_2$$

Подставим сюда уравнение кривой, чтобы найти соотношение между $C_1$ и $C_2$:
\begin{equation*}
  \begin{cases}
    C_1 = -\frac{1}{z^2},\\
    C_2 = \frac{z^8}{2} - \frac{z^6}{3}
  \end{cases}
\end{equation*}
Получаем, что $C_2 = \frac{1}{2C_1^4} + \frac{1}{3C_1^3}$, откуда уравнение искомой поверхности имеет вид:
$$\frac{x^2z^2}{2} - \frac{y^3}{3} = \frac{x^4}{2z^4} + \frac{x^3}{3z^3}$$
75, 81, 83, 88, 72, 74, 76, 78, 155, 156
* Задача 75
Найти экстремали функционала $J[y] = \int_0^\pi(4y\cos x + y'^2 - y^2)dx, y(0) = y(\pi) = 0$.

Экстремалями являются решения уравнения:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
Где $F(x, y, y') = 4y\cos x + y'^2 - y^2$.
$$F_y = 4\cos x - 2y$$
$$\frac{d}{dx}F_{y'} = \frac{d}{dx}2y' = 2y''$$
Получили уравнение:
$$4\cos x - 2y - 2y'' = 0$$
Или:
$$y'' + y = 4\cos x$$
Общее решение однородного уравнения имеет вид:
$$y_{oo} = C_1\sin x + C_2\cos x$$
Частное решение неоднородного уравнения ищем в виде:
#+BEGIN_EXPORT latex
\begin{multline*}
y_{np} = x(a\sin x + b\cos x) \Rightarrow y'_{np} = x(a\cos x - b\sin x) + (a\sin x + b\cos x) \Rightarrow\\
\Rightarrow y''_{np} = x(-a\sin x - b\cos x) + (a(\cos x + \sin x) + b(\cos x - \sin x)) \Rightarrow\\
\Rightarrow y''_{np} + y_{np} = (a + b)\cos x + (a - b)\sin x = \cos x \Rightarrow a = b = \frac{1}2
\end{multline*}
#+END_EXPORT
Таким образом, общее решение уравнения Эйлера имеет вид:
$$y_{no} = \left(C_1 + \frac{1}2x\right)\sin x + \left(C_2 + \frac{1}2x\right)\cos x$$
Для нахождения экстремалей подставим в решение граничные условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
C_2 = 0, \\
C_2 + \frac{\pi}2 = 0,
\end{cases}
\Rightarrow
\begin{cases}
C_2 = 0, \\
C_2 = -\frac{\pi}2
\end{cases}
\end{equation*}
#+END_EXPORT
Таким образом, экстремалей нет.
* Задача 81
Найти экстремали функционала:
$$J[y(x)] = \int_a^b[2xy + (x^2 + e^y)y']dx, y(a) = A, y(b) = B$$

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = 2x + y'e^y$$
$$\frac{d}{dx}F_{y'} = \frac{d}{dx}(x^2 + e^y) = 2x + y'e^y$$
Получили уравнение:
$$0 = 0$$
Таким образом, любая кривая, удовлетворяющая граничным условиям будет экстремалью.
* Задача 83
Найти экстремали функционала:
$$J[y(x)] = \int_0^{\frac{\pi}4}(y'^2 - y^2)dx; y(0) = 1, y\left(\frac{\pi}4\right) = \frac{\sqrt 2}2$$
ВЫпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = 2y$$
$$F_{y'} = \frac{d}{dx}(2y') = 2y''$$
Получаем уравнение:
$$2y - 2y'' = 0$$
Общее решение этого уравнения имеет вид:
$$y_{oo} = C_1e^x + C_2e^{-x}$$
Чтобы найти экстремали, подставим граничные условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
C_1 + C_2 = 1, \\
C_1e^{\frac{\sqrt 2}2} + C_2e^{-\frac{\sqrt 2}2} = \frac{\sqrt 2}2
\end{cases}
\Rightarrow
\begin{cases}
C_1 + C_2 = 1, \\
C_1e^{\sqrt 2} + C_2 = \frac{\sqrt 2}2e^{\frac{\sqrt 2}2}
\end{cases}
\Rightarrow
\begin{cases}
C_1 = \frac{\sqrt 2e^{\frac{\sqrt 2}2} - 1}{2(e^{\sqrt 2} - 2)}, \\
C_2 = 1 - C_2
\end{cases}
\end{equation*}
#+END_EXPORT
Таким образом, единственной экстремалью является функция $y = C_1e^x + C_2e^{-x}$, где $C_1$ и $C_2$ определяются
из системы выше.
* Задача 88
Найти экстремали функционала:
$$J[y(x)] = \int_0^1(2e^y - y^2)dx; y(0) = 1, y(1) = e$$

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = 2e^y - 2y$$
$$\frac{d}{dx}F_{y'} = 0$$
Получили уравнение:
$$2e^y - 2y = 0$$
Или:
$$y = e^y$$
При подстановке $x = 0$ получаем противоречие:
$$1 = e$$
Т. е. экстремалей нет.
* Задача 72
Найти экстремали функционала:
$$J[y] = \int_1^2(y'^2 + 2yy' + y^2)dx; y(1) = 1, y(2) = 0$$

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = 2y' + 2y$$
$$\frac{d}{dx}F_{y'} = \frac{d}{dx}(2y' + 2y) = 2y'' + 2y'$$
Получили уравнение:
$$2y - 2y'' = 0$$
Общее решение этого уравнения имеет вид:
$$y = C_1e^x + C_2e^{-x}$$
Подставим начальные условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
C_1e + \frac{C_2}e = 1, \\
C_1e^2 + \frac{C_2}{e^2} = 0
\end{cases}
\Rightarrow
\begin{cases}
C_1 = \frac{1}{e + e^3}, \\
C_2 = \frac{e^3}{e^2 + 1}
\end{cases}
\end{equation*}
#+END_EXPORT
Откуда экстремалью является функция:
$$y = \frac{e^x + e^{4 - x}}{e^3 + e}$$
* Задача 74
Найти экстремали функционала:
$$J[y] = \int_0^1yy'^2dx; y(0) = 1, y(1) = \sqrt[3]4$$

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = y'^2$$
$$\frac{d}{dx}F_{y'} = \frac{d}{dx}(2yy') = 2y'^2 + 2yy''$$
Получили уравнение:
#+BEGIN_EXPORT latex
\begin{equation}
2yy'' - y'^2 = 0
\end{equation}
#+END_EXPORT
Положим $y' = p(y)$, тогда $y'' = p'p$ и уравнение преобразуется к виду:
$$2yp'p - p'^2 = 0$$
Или:
$$p'(p' - 2py) = 0$$
Если $p' = 0$, то $p = C \Rightarrow y' = C \Rightarrow y = C_1x + C_2$. Подставив эту функцию в уравнение (1), найдём,
что $y = C$.
В противном случае уравнение приводится к виду:
$$\frac{p'}p = 2y \Rightarrow p = Cy^2, C \neq 0$$
Откуда $y' = Cy^2 \Rightarrow \frac{y'}{y^2} = C, C \neq 0 \Rightarrow y = \frac{1}{C_1x + C_2}, C_1 \neq 0$.

Объединяя это решение с предыдущим, получим:
$$y = \frac{1}{C_1x + C_2}, C_1^2 + C_2^2 \neq 0$$
Подставим граничные условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{dcases}
\frac{1}{C_2} = 1, \\
\frac{1}{C_1 + C_2} = \sqrt[3]4
\end{dcases}
\Rightarrow
\begin{dcases}
C_1 = \sqrt[3]{\frac{1}4} - 1, \\
C_2 = 1
\end{dcases}
\end{equation*}
#+END_EXPORT
Получили единственную экстремаль:
$$y = \frac{\sqrt[3]4}{(1 - \sqrt[3]4)x + \sqrt[3]4}$$
* Задача 76
Найти экстремали функционала $J[y] = \int_0^1(y'^2 - y^2 - y)e^{2x}dx, y(0) = 0, y(1) = e^{-1}$.

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = (2y - 1)e^{2x}$$
$$\frac{d}{dx}F_{y'}= \frac{d}{dx}(2ye^{2x}) = e^{2x}(2y' + 4y)$$
Получили уравнение:
$$e^{2x}(2y' - 2y + 1) = 0$$
Или:
$$y' - y = \frac{1}2$$
Общее решение этого уравнения имеет вид:
$$y = Ce^x - \frac{1}2$$
Подставим начальные условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
C\cdot1 - \frac{1}2 = 0, \\
Ce - \frac{1}2 = e^{-1}
\end{cases}
\Rightarrow
\begin{cases}
C = \frac{1}2, \\
C = \frac{e^{-1} + 2^{-1}}e
\end{cases}
\end{equation*}
#+END_EXPORT
Система несовместна, значит экстремалей нет.
* Задача 78
Найти экстремали функционала $J[y] = \int_{-1}^0(y'^2 - 2xy)dx, y(-1) = 0, y(0) = 2$.

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = 2x$$
$$\frac{d}{dx}F_{y'} = \frac{d}{dx}(2y') = 2y''$$
Получили уравнение:
$$y'' = x \Rightarrow y' = \frac{x^2}2 + C_1 \Rightarrow y = \frac{x^3}6 + C_1x + C_2$$
Подставим граничные условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
-\frac{1}6 - C_1 + C_2 = 0, \\
C_2 = 2
\end{cases}
\Leftrightarrow
\begin{cases}
C_1 = \frac{11}6, \\
C_2 = 2
\end{cases}
\end{equation*}
#+END_EXPORT
Таким образом, единственной экстремалью является кривая
$$y = \frac{x^3}6 + \frac{11}6x + 2$$
* Задача 155
Исследовать функционал на экстремум: $J[y] = \int_2^3\frac{x^3}{y'^2}dx; y(2) = 4, y(3) = 9$.

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = 0$$
#+BEGIN_EXPORT latex
\begin{multline*}
\frac{d}{dx}F_{y'} = \frac{d}{dx}\left(-2\frac{x^3}{y'^3}\right) = -2\frac{3x^2y'^3 - 3y'^2y''x^3}{y'^6}
= 6\frac{x^3y'' - x^2y'}{y'^4}
\end{multline*}
#+END_EXPORT

Получили уравнение:
#+BEGIN_EXPORT latex
\begin{multline*}
\begin{cases}
x^2(xy'' - y') = 0, \\
y' \neq 0
\end{cases}
\end{multline*}
#+END_EXPORT
$x = 0$ и $y = 0$ - не решения, поэтому уравнение приводится к виду:
$$y'' - \frac{1}xy' = 0 \Leftrightarrow (\ln y')' = (\ln |x|)' \Leftrightarrow y' = Cx, C \neq 0
\Leftrightarrow y = Cx^2 + C_1, C \neq 0$$
Допустимые значения $C$ и $C_1$ найдём, исходя из граничных условий:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
4C + C_1 = 4, \\
9C + C_1 = 9
\end{cases}
\Leftrightarrow
\begin{cases}
C = 1, \\
C_1 = 0
\end{cases}
\end{equation*}
#+END_EXPORT
Т. е. экстремум может достигаться только на кривой $y = x^2$. Эта кривая может быть включена в поле экстремалей
$y = Cx^2$.

Найдём $F_{y'y'}$
$$F_{y'y'} = 6\frac{x^3}{y'^4} =|_{y = y_0} = 4x^2 = 0 \text{ при } x = 0$$
Это означает, что слабого экстремума на этой кривой нет, а значит, и сильного.
* Задача 156
Исследовать функционал на экстремум: $J[y] = \int_1^2(xy'^4 - 2yy'^3)dx; y(1) = 0, y(2) = 1$.

Выпишем уравнение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = 0$$
$$F_y = -2y'^3$$
$$\frac{d}{dx}F_{y'} = \frac{d}{dx}(4xy'^3 - 6yy'^2) = 4y'^3 + 12xy'^2y'' - 6y'^3 - 12yy'y''$$
Получили уравнение:
$$12yy'y'' - 12xy'^2y'' = 0$$
Или:
$$y'y''(y - xy') = 0$$
Если $y'' = 0$, то $y = C_1x + C_2$, иначе уравнение принимает вид:
$$\frac{y'}y = \frac{1}x \Leftrightarrow y = Cx, C \neq 0$$
Таким образом, все экстремали имеют вид:
$$y = C_1x + C_2$$
Проверим краевые условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
C_1 + C_2 = 0, \\
2C_1 + C_2 = 1
\end{cases}
\Leftrightarrow
\begin{cases}
C_1 = 1, \\
C_2 = -1
\end{cases}
\end{equation*}
#+END_EXPORT
Таким образом, экстремум может достигаться на экстремали $y_0 = x - 1$. Она может быть включена в поле экстремалей
$y = x + C$.
$$F_{y'y'} = 12xy'^2 - 12yy' = 12y'(xy' - y) = |_{y = y_0} 12x - 12(x - 1) = 12 > 0$$
Таким образом, на $y_0$ достигается слабый минимум функционала. При произвольных $y'$ знак $F_{y'y'}$ не сохраняется,
значит, сильного минимума нет.
* Обобщения простейшей задачи вариационного исчисления
$$J[y] = \int_a^bF(x, y, y')dx$$
1.
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
y(x) \in M, \\
z(x) \in N
\end{cases}
\rightarrow J[y, z] \in \mathbb{R}
\end{equation*}
#+END_EXPORT
Для поиска экстремума записывается система:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{dcases}
F_y - \frac{d}{dx}F_{y'} = 0, \\
F_z - \frac{d}{dz}F_{z'} = 0
\end{dcases}
\end{equation*}
#+END_export
* Задача 107
#+BEGIN_EXPOrt latex
\begin{equation*}
\begin{cases}
J[y(x), z(x)] = \int_0^{\frac{\pi}2}(y'^2 + z'^2 - 2yz)dx, \\
y(0) = 0, y\left(\frac{\pi}2\right) = 1, \\
z(0) = 0, z\left(\frac{\pi}2\right) = 1, \\
\end{cases}
\end{equation*}
#+END_EXPORT
Записываем систему уравнений Эйлера:
#+BEGIN_EXPORT latex
\begin{multline*}
\begin{cases}
-2z - 2y'' = 0, \\
-2(y + z'') = 0,
\end{cases}
\Rightarrow
\begin{cases}
z + y'' = 0, \\
y + z'' = 0
\end{cases}
\Rightarrow
\begin{cases}
z = -y'', \\
y^{IV} - y = 0
\end{cases}
\Rightarrow \\
\Rightarrow
\begin{cases}
y = C_1e^x + C_2e^{-x} + C_3\cos x + C_4\sin x, \\
z = -C_1e^x - C_2e^{-x} + C_3\cos x + C_4\sin x
\end{cases}
\end{multline*}
#+END_EXPORT
Подставив граничные условия, найдём:
#+BEGIN_EXPORT latex
\begin{equation*}
y = z = \sin x
\end{equation*}
#+END_EXPORT
2. $$J[y] = \int_a^bF(x, y, y', \ldots, y^{(n)})$$
Здесь $F \in C^{n + 1}(D)$ и заданы $2n$ граничных условий:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
y(a) = y_0, \\
y(b) = y_1, \\
y'(a) = y'_0, \\
y'(b) = y'_1, \\
\ldots \\
y^{(n - 1)} = y_0^{n - 1}, \\
y^{(n - 1)} = y_1^{n - 1}
\end{cases}
\end{equation*}
#+END_EXPORT
Уравнение Эйлера-Пуассона:
$$\sum_{k = 0}^n(-1)^k\frac{d^k}{dx^k}F_{y^{(k)}} = 0$$
Решения этого уранвения - экстремали.
* Задача 1
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{dcases}
J[y] = \int_0^{\frac{\pi}2}(y''^2 - y^2 + x^2)dx, \\
y(0) = 1, y'(0) = 0, \\
y\left(\frac{\pi}2\right) = 0, y'\left(\frac{\pi}2\right) = -1
\end{dcases}
\end{equation*}
#+END_EXPORT
Запишем уравнение Эйлера-Пуассона:
$$F_y - \frac{d}{dx}F_{y'} + \frac{d^2}{dx^2}F_{y''} = 0$$
$$F_y = -2y$$
$$\frac{d}{dx}F_{y'} = 0$$
$$\frac{d^2}{dx^2}F_{y''} = \frac{d^2}{dx^2}(2y'') = 2y^{IV}$$
Получили уравнение:
$$-2y + 2y^{IV} = 0$$
Или $$y^{IV} - y = 0$$
Общее решение имеет вид:
$$y = C_1e^x + C_2e^x + C_3\sin x + C_4\cos x$$
Подставим краевые условия:
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
C_1 + C_2 + C_4 = 1, \\
C_1e^{\frac{\pi}2} + C_2e^{\frac{\pi}2} + C_3 = 0, \\
C_1 - C_2 + C_3 = 0, \\
C_1e^{\frac{\pi}2} - C_2e^{\frac{\pi}2} - C_4 = -1
\end{cases}
\Rightarrow
\begin{cases}
C_1 = C_2 = C_3 = 0, \\
C_4 = 1
\end{cases}
\end{equation*}
#+END_EXPORT
Откуда единственной экстремалью является кривая $y = \cos x$
* Условие Якоби
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
J[y] = \int_a^bF(x, y, y')dx, \\
y(a) = A, \\
y(b) = B
\end{cases}
\end{equation*}
#+END_EXPORT
Рассмотрим \textit{уравнение Якоби}:
$$(F_yy - \frac{d}{dx}F_yy')u - \frac{d}{dx}(F_{y'y'}u')|_{y = y_0} = 0$$
Где $y_0$ - проверяемая экстремаль.


Пусть $u(x)$ решение уравнения Якоби, удовлетворяющее условиям:
1. $u(a) = 0$
2. u(x) не обращается в нуль на $(a; b]$
Если такое решение существует, то экстремаль можно включить в поле экстремалей с центром в $(a, A)$.
* Задача 156
$$J[y] = \int_1^2(xy'^4 - 2yy'^3)dx; y(1) = 0, y(2) = 1$$
Экстремаль уже найдена ранее: $y = x - 1$. Проверим её включение в поле экстремалей с помощью условия Якоби.
Выпишем уравнение Якоби:
$$(0 + \frac{d}{dx}(6y'^2))u - \frac{d}{dx}((12xy'^2 - 12yy')u') = 0$$
$$\frac{d}{dx}(y'^2)u - \frac{d}{dx}((2xy'^2 - 2yy')u') = 0$$
Подставим экстремаль:
$$-\frac{d}{dx}((2x - 2(x - 1))u') = 0 \Rightarrow (x - x + 1)u' = C \Rightarrow u = Cx + C_1$$
Вспоминая, что $u(1) = 0$, получаем $u = C(x - 1)$.
* Задача 76
#+BEGIN_EXPORT latex
\begin{equation*}
\begin{cases}
J[y] = \int_0^1(y'^2 - y^2 - y)e^{2x}dx, \\
y(0) = 0, \\
y(1) = \frac{1}r
\end{cases}
\end{equation*}
#+END_EXPORT
Выпишем уравение Эйлера:
$$F_y - \frac{d}{dx}F_{y'} = (-2y - 1)e^2x - \frac{d}{dx}(2y'e^{2x}) = (-2y - 1)e^{2x} - 2y''e^{2x} - 2y'\cdot2$$
Общее решение имеет вид:
$$y = C_1e^{-x} + C_2xe^{-x} - \frac{1}2$$
Поле экстремалей не выделяется, нужно воспользоваться условием Якоби.
