#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+OPTIONS: toc:nil
* Задача 10.2
Запишем силу Лоренца, действующую на заряды в пластине:
$$\vec F_{L} = q \times [\vec v \times \vec B]$$
В положении равновесия она равна силе поля, создаваемого зарядами:
$$\vec F_q = q\vec E \Rightarrow \vec E = -[\vec v \times \vec B]$$
По теореме Гаусса $Q = \oiint_SdS (\vec D, \vec n) = DS = \varepsilon_0vB$
* Задача 10.3
По закону Фарадея напряжение на концах каждой катушки одно и то же и равно $U = -\frac{d\Phi}{dt}$.
С другой стороны, сила тока, протекающего через каждую катушку, одна и та же, и равна $I_i = \frac{I}{N}$.
Отсюда получаем, что $L_i = \frac{\Phi_i}{I_i} = \frac{\Phi N}{I} = NL \Rightarrow L = \frac{L_i}{N}$.
* Задача 10.4
Найдём магнитный поток через треугольник:
$$\Phi = \oiint_S (\vec B, \vec n)dS = \int_0^h \int_{-x}^x \frac{\mu_0 I_1}{2\pi(x + d)}dydx = \frac{\mu_0 I_1}{\pi}\int_0^h \frac{x}{x + d}dx = \frac{\mu_0 I_1}{\pi}\left(h - \ln\left(1 + \frac{d}{h}\right)\right)$$
Отсюда:
$$\varepsilon = -\frac{d\Phi}{dt} = \frac{\mu_0}{\pi}\left(h - \ln\left(1 + \frac{d}{h}\right)\right)\frac{dI}{dt} \Rightarrow I_{i} = \frac{\varepsilon}{R} = \frac{2\mu_0t}{\pi R\tau^2}I_0e^{-\left(\frac{t}{\tau}\right)^2}$$
Продифференцировав $I_i$ по $t$, получим, что максимум достигается в точке $\frac{t}{\tau} = \frac{1}{\sqrt 2}$ и равен:
$$I_{i_{max}} = \frac{\mu_0}{\pi R}\sqrt \frac{2}{e} I_0\left(h - \ln\left(1 + \frac{d}{h}\right)\right)$$
* Задача 10.6
По закону Фарадея $\varepsilon_i = -\frac{d\Phi}{dt}$. С другой стороны, по закону Ома для полной цепи $\varepsilon_i = IR = R\frac{dQ}{dt} \Rightarrow R\frac{dQ}{dt} = -\frac{d\Phi}{dt}$. Проинтегрировав по $t$ от $0$ до $t_0$, получим, что $RQ = -\Delta\Phi$.

Найдём изменение магнитного потока:
$$\Phi_0 = \oiint_S (\vec B, \vec n)dS = \int_c^{c + a} \int_0^b \frac{\mu_0 I}{2\pi x}dydx = \frac{\mu_0 bI}{2\pi}\int_c^{c + a} \frac{dx}{x} = \frac{\mu_0 bI}{2\pi}\ln\left(\frac{c + a}{c}\right)$$
$$\Phi_1 = \oiint_S (\vec B, \vec n)dS = -\int_{c - a}^c \int_0^b \frac{\mu_0 I}{2\pi x}dydx = \ldots = \frac{\mu_0 bI}{2\pi}\ln\left(\frac{c - a}{c}\right)$$
Тогда:
$$Q = \frac{\Delta\Phi}{R} = \frac{\mu_0 bI}{\pi R}\ln\left(\frac{c + a}{c - a}\right)$$
* Задача 10.7
Поскольку длина квадрата не изменилась, можно найти связь между стороной квадрата и радиусом круга:
$$4a = 2\pi r \Rightarrow r = \frac{2}{\pi}a$$
Отсюда получаем новую площадь контура:
$$\pi r^2 = \pi\frac{4}{\pi^2}a^2 = \frac{4}{\pi}a^2 \Rightarrow \Delta\Phi = B\Delta S = -B(1 - \frac{4}{\pi^2})a^2 \Rightarrow Q = -\frac{\Delta\Phi}{R} = \frac{B}{R}\left(1 - \frac{4}{\pi^2}\right)a^2$$
* Задача 10.9
Магнитный поток через рамку равен:
$$\Phi = BScos(\omega t) = Babcos(\omega t)$$
Откуда по закону Фарадея получаем ЭДС:
$$\varepsilon = -\frac{d\Phi}{dt} = \omega Babsin(\omega t)$$
* Задача 10.10
Магнитный поток через рамку равен:
$$\Phi = BScos(\omega t) = abB_0cos(\Omega t)cos(\omega t) = 1/2abB_0(cos((\Omega - \omega)t) + cos((\Omega + \omega)t)$$
Из закона Фарадея находим ЭДС:
$$\varepsilon = -\frac{d\Phi}{dt} = abB_0((\Omega - \omega)sin((\Omega - \omega)t + (\Omega + \omega)sin((\Omega + \omega)t)))$$
* Задача 10.12
Поле соленоида однородно с индукцией: $B = \mu_0nI$.

Из задачи 10.6 $\Delta\Phi = -RQ \Rightarrow BS = RQ \Rightarrow = \mu_0n\frac{SI}{R}$.
* Уравнения Максвелла
$$\operatorname{rot} \vec H = \vec j + \frac{\partial \vec D}{\partial t},$$
$$\operatorname{rot} \vec E = -\frac{\partial \vec B}{\partial t},$$
$$\operatorname{div} \vec B = 0,$$
$$\operatorname{div} \vec D = \rho,$$
Материальные уравнения:
$$\vec D = \varepsilon\varepsilon_0\vec E,$$
$$\vec B = \mu\mu_0\vec H,$$
Закон Ома:
$$\vec j = \lambda(\vec E + \vec E_{ext}),$$
Уравнение непрерывности:
$$\frac{\partial\rho}{\partial t} + \operatorname{div}\vec j = 0,$$
Закон Джоуля-Ленца:
$$\nu = \vec j \vec E = \lambda E^2 = \frac{j^2}{\lambda}$$
Теорема Умова-Пойнтинга:
$$\frac{dW}{dt} = -\oint_S\vec\Pi d\vec S - \frac{dQ}{dt} + \int_V \vec j dV$$
Где $W = \frac{1}2\int_V(\vec E\vec D + \vec H\vec B)dV$, $\Pi = [\vec E\vec H]$.
Потенциалы:
$$\vec B = \operatorname{rot}\vec A$$
$$\vec E = -\operatorname{grad}\varphi - \frac{\partial\vec A}{\partial t}$$
Квазистационарное приближение:
$$\frac{\partial \vec D}{\partial t} \approx 0$$
* Задача 11.1
Дано: $\lambda, l, R, B(t), k$.
\begin{equation*}
B(t) = \begin{cases}
kt, 0 \leq r \leq R_1,\\
0, r > R_1,
\end{cases}
\end{equation*}
$R_1 > r$
$$P - ?$$
Из второго из уравнений Максвелла $\operatorname{rot}\vec E = -\frac{\partial\vec B}{\partial t}$. Задача имеет
цилиндрическую симметрию, поэтому задачу удобнее всего решать в цилиндрических координатах. Кроме того, нет явной
зависимости поля от $z$ и $\varphi$. Получаем уравнение:
\begin{equation}
\operatorname{rot}\vec E = (0, 0, -k)
\end{equation}
Воспользуемся представлением ротора в цилиндрических координатах:
\begin{multline*}
\operatorname{rot}\vec E = 
\begin{vmatrix}
\frac{1}r \vec e_r          & \vec e_\varphi                    & \frac{1}r \vec e_z       \\
\frac{\partial}{\partial r} & \frac{\partial}{\partial \varphi} & \frac{\partial}{\partial z} \\
E_r                         & r E_\varphi                       & E_z
\end{vmatrix}
= \\
= \left(\frac{1}{r}\left(\frac{\partial E_z}{\partial\varphi} - \frac{\partial (rE_\varphi)}{\partial z}\right);
-\frac{\partial E_z}{\partial r} + \frac{\partial E_r}{\partial z};
\frac{1}r\left(\frac{\partial (rE_\varphi)}{\partial r} - \frac{\partial E_r}{\partial\varphi}\right)\right)
\end{multline*}
Откуда получаем систему:
\begin{equation*}
\begin{dcases}
\frac{1}r\frac{\partial E_z}{\partial \varphi} - \frac{\partial E_\varphi}{\partial z} = 0, \\
\frac{\partial E_r}{\partial z} - \frac{\partial E_z}{\partial r} = 0, \\
\frac{\partial (rE_\varphi)}{\partial r} - \frac{\partial E_r}{\partial\varphi} = -kr, \\
\end{dcases}
\end{equation*}
Учитывая, что $\frac{\partial E}{\partial\varphi} = \frac{\partial E}{\partial z} = 0$, систему можно записать в
виде:
\begin{equation*}
\begin{dcases}
\frac{\partial E_z}{\partial r} = 0, \\
\frac{\partial (rE_\varphi)}{\partial r} = -kr
\end{dcases}
\end{equation*}
Откуда находим выражения для $E_\varphi$ и $E_z$:
\begin{equation}
\begin{dcases}
E_\varphi = -\frac{kr}2 + \frac{C_1}r, \\
E_z = C_2
\end{dcases}
\end{equation}
Поскольку по условию задачи на оси цилиндра свободных зарядов нет, то поле при $r \to 0$ ограничено, поэтому
$C_1 = 0$.

Для нахождения $E_r$ и $E_z$ воспользуемся четвёртым уравнением Максвелла. Так как свободных зарядов в цилиндре
нет, то $\operatorname{div}\varepsilon_0\vec E = \rho = 0$, или, в цилиндрических координатах:
\begin{equation*}
\frac{1}r\frac{\partial(rE_r)}{\partial r} + \frac{1}r\frac{\partial E_\varphi}{\partial \varphi}
+ \frac{\partial E_z}{\partial z} = 0 \Rightarrow \frac{\partial (rE_r)}{\partial r} = 0
\end{equation*}
Откуда находим выражение для $E_r$:
\begin{equation}
E_r = \frac{C_3}r
\end{equation}
Вспоминая, что на оси цилиндра нет свободных зарядов, окончательно получим, что $E_r = 0$. Таким образом, $\vec E$
имеет вид:
\begin{equation}
\vec E = (0; -\frac{kr}2; C_2)
\end{equation}
Из закона Ома $\vec j = \lambda\vec E$, поэтому $\vec j$ имеет вид:
\begin{equation}
\vec j = (0, -\frac{kr}2\lambda; \lambda C_2)
\end{equation}
Поскольку цилиндр ограничен, ток не может течь вдоль оси цилиндра, поскольку такой контур незамкнут, откуда $C_2 = 0$.
Окончательно получаем, что $\vec j = -\frac{\lambda kr}2\vec e_\varphi$. Тогда объёмная плотность мощности равна:
$$\nu = \vec j \vec E = \lambda\frac{k^2r^2}4$$
Мощность, заключённая в кольце, ограниченном радиусами $r$ и $r + dr$:
$$dP = \lambda\frac{k^2r^2}4dV = \lambda\frac{k^2r^22\pi rdr}4 = \frac{\pi\lambda k^2l}2r^3dr$$
Проинтегрировав по $r$ от 0 до R, получим:
$$P = \frac{\pi\lambda k^2l}8R^4$$
* Задача 11.3
В проводнике, помещённом в нестационарное магнитное поле, циркулируют токи Фуко. Линии тока представляют собой
окружности, центры которых лежат на оси $Oz$, причём зависимость плотности тока от времени $t$ и от расстояния
$r$ рассматриваемой точки до оси $Oz$ описывается законом $j(r,t) = kre^{-t/\tau}$. Определите индукцию магнитного
поля в проводнике, если известно, что в момент времени $t = 0$ она была равна нулю во всём объёме проводника.

Поскольку задача имеет цилиндрическую симметрию, выгоднее всего использовать цилиндрические координаты. По закону
Ома:
$$\vec E = \frac{1}\lambda \vec j = \left(0; \frac{ke^{-t/\tau}}\lambda; 0\right)$$
Далее, по первому уравнению Максвелла $\operatorname{rot}\vec E = -\frac{d\vec B}{dt}$. Найдём
$\operatorname{rot}\vec E$:
\begin{equation}
\operatorname{rot}\vec E =
\begin{vmatrix}
\frac{1}r\vec e_r           & \vec e_\varphi                   & \frac{1}r\vec e_z \\
\frac{\partial}{\partial r} & \frac{\partial}{\partial\varphi} & \frac{\partial}{\partial z} \\
0                           & \frac{kre^{-t/\tau}}\lambda       & 0
\end{vmatrix}
= \left(0; 0; 2\frac{ke^{-t/\tau}}\lambda\right)
\end{equation}
Тогда
\begin{multline}
B = -\int_{t_0}^t\operatorname{rot}\vec E dt = -2\frac{k\tau}{\lambda}\int_{t_0}^te^{-t/\tau}d(t/\tau) = \\
= 2\frac{k\tau}{\lambda}e^{-t/\tau}\bigg|_{t_0}^t = 2\frac{k\tau}{\lambda}(e^{-t/\tau} - e^{-t_0/\tau})
\end{multline}
Из начальных условий $B(0) = 0$, откуда $t_0 = 0$, откуда
$$\vec B(t) = 2\frac{k\tau}\lambda(e^{-t/\tau} - 1)\vec e_z$$
* Задача 11.4
Дано: $U_0, d$ для плоскопараллельного диода. Рассчитать $\rho(x)$.

Из четвёртого уравнения Максвелла получим уравнение Пуассона:
$$\frac{d^2\varphi}{dx^2} = -\frac{\rho(x)}{\varepsilon_0}$$
Из примера 11.2 известно распределение потенциала: $\varphi(x) = U_0\left(\frac{x}d\right)^{4/3}$.
Откуда и из уравнения Пуассона получим: $\rho(x) = -\varepsilon_0U_0\frac{4}{9}\left(\frac{d}x\right)^{2/3}\frac{1}{d^2}$

Выведем распределение потенциала:

Уравнение Пуассона:
\begin{equation}
\frac{d^2\varphi}{dx^2} = -\frac{\rho(x)}{\varepsilon_0}
\end{equation}
Обозначим концентрацию электронов $n(x)$, тогда $\rho(x) = -en(x)$. Тогда плотность тока зависит от скорости
электронов следующим образом:
$$\vec j = -en(x)\vec v \Rightarrow n(x) = \frac{j}{ev}$$
Скорость электронов находится из закона сохранения энергии:
$$\frac{mv^2}2 + e\varphi(x) = \frac{mv_0^2}2 + e\varphi(0)$$
$v_0 << v$, поэтому положив $v \approx 0$, получим $v = \sqrt\frac{2e\varphi}m$. Подставив найденное значение в (8),
получим уравнение для потенциала:
$$\frac{d^2\varphi}{dx^2} = \frac{j}{\varepsilon_0}\sqrt{\frac{m}{2e\varphi}} = \alpha\varphi^{-1/2}$$
Где $\alpha = \frac{j}{\varepsilon_0}\sqrt\frac{m}{2e\varphi}$.

Обозначим $p(\varphi) = \frac{d\varphi}{dx}$, тогда:
$$\frac{d^2\varphi}{dx^2} = \frac{d}{dx}(p(\varphi)) = p\frac{dp}{d\varphi}$$, поэтому уравнение принимает вид:
$$p\frac{dp}{d\varphi} = \alpha\varphi^{-1/2}$$
Интегрируя это уравнение, найдём:
$$p = 2\sqrt\alpha\varphi^{1/4} + C$$
или
$$\frac{d\varphi}{dx} = 2\sqrt\alpha\varphi^{1/4} + C$$
Поскольку по условию катод окружен облаком электронов, на электрон у катода не действует сила, т. е. $E(0) = 0
\Rightarrow \frac{d\varphi}{dx}(0) = 0$, откуда $C = 0$.
Интегрируя полученное уравнение второй раз, найдём:
$$\varphi(x) = \left(\frac{3\sqrt a}2\right)^{4/3} + C_1$$
$C_1 = 0$, так как $\varphi(0) = 0$. Постоянная $\alpha$ находится из второго граничного условия: $\varphi(d) = U_0$.
Окончательно потенциал имеет вид:
$$\varphi(x) = U_0\left(\frac{x}d\right)^{4/3}$$
* Задача 11.8
К плоскому воздушному конденсатору, обкладки которого имеют форму дисков с зазором $d$ между ними, приложено переменное
напряжение $U = U_0\cos\omega t$ c амплитудой $U_0$ и круговой частотой $\omega$. Найти амплитуду $H_0$ и $B_0$ на
расстоянии $r$ от оси конденсатора, если радиус обкладок $R, r < R$. Между обкладками конденсатора помещён однородный
диэлектрик с $\varepsilon$ и $\mu$.

Распределение тока проводимости вне пластин и токов смещения между ними обладает цилиндрической симметрией, поэтому
создаваемое токами смещения магнитное поле имеет ту же симметрию. В силу теоремы о циркуляции $\vec H$ по окружности
радиуса $r$ с центром на оси конденсатора:
#+BEGIN_EXPORT latex
\begin{multline*}
2\pi rH = \oint_L\vec Hd\vec l = \frac{d}{dt}\oint_S\vec Dd\vec S = \frac{d}{dt}(\pi r^2D) = \pi r^2\frac{dD}{dt} = \\
= \varepsilon_0\varepsilon\pi r^2\frac{dE}{dt} = \frac{\varepsilon_0\varepsilon\pi r^2}{d}\frac{dU}{dt}
= -\frac{\varepsilon_0\varepsilon\pi r^2}{d}\omega U_0\sin \omega t
\end{multline*}
#+END_EXPORT
Откуда получаем выражение для $H$ и $B$:
$$H = -\frac{\varepsilon_0\varepsilon r}{2d}\omega U_0\sin\omega t \Rightarrow H_0 = \frac{\varepsilon_0\varepsilon r}{2d}\omega U_0$$
$$B_0 = \mu\mu_0 H_0 = \mu\mu_0\omega U_0\frac{\varepsilon_0\varepsilon r}{2d}$$
* Задача 11.9
Заряженный и отключённый от источника плоский конденсатор с круглыми пластинами пробивается электрической искрой
вдоль своей оси. Считая разряд квазистационарным и пренебрегая краевыми эффектами, вычислите полный поток электромагнитной
энергии, вытекающей из пространства между обкладками.

Рассчитаем поле, возникающее в конденсаторе. Поле обладает цилиндрической симметрией, поэтому расчёт будем вести в
цилиндрических координатах. Поле создаётся токами проводимости в направлении искры и токами смещения в противоположном
направлении. Рассмотрим в качестве контура интегрирования окружность радиуса $r$ с центром на оси конденсатора. По
теореме о циркуляции вектора магнитной индукции:
$$\oint_L\vec Hd\vec l = 2\pi rH = I - \frac{r^2}{R^2}I$$
Откуда
$$H = \frac{I}{2\pi r}\left(1 - \frac{r^2}{R^2}\right)$$
$$H(R) = 0 \Rightarrow \Pi(R) = 0 \Rightarrow \int_S\vec\Pi d\vec S = 0$$
* Задача 11.12
Цилиндрический электронный пучок радиусом $R$ распространяется в свободном пространстве. Электроны пучка летят
параллельно, их концентрация равна $n$, а кинетическая энергия каждого из них равна W. Найти величину и направление
вектора Пойнтинга в любой точке пространства.

Задача обладает цилиндрической симметрией. По теореме Умова-Пойнтинга:
$$\frac{dW}{dt} = -\oint_S\vec\Pi d\vec S - \frac{dQ}{dt} + \int_V\vec jdV$$
Второе слагаемое равно нулю, поскольку не происходит выделения тепла. Третье слагаемое равно нулю, поскольку нет
внешних сил. Рассмотрим изменение энергии электромагнитого поля в малом цилиндре высотой $d$ и радиусом $r$, соосном с пучком:
$$\frac{dW}{dt} = W\pi r^2h$$
Используя формулу Остроградского-Гаусса, теорему Умова-Пойнтинга можно переписать в виде:
$$w = -div \vec \Pi$$
* Законы Киргхофа
$$\sum_iI_i = 0$$
$$\sum_iU_i = \sum_j\varepsilon_j$$
* Задача 12.2
Конденсатор заряжен до заряда $q_0$ подключен через ключ к сопротивлению $R$. Найти тепло, выделяющееся после замыкания
ключа.

По второму правилу Киргхофа:
$$\frac{q}C + IR = 0$$
$$\frac{1}C\int Idt + IR = 0$$
$$\frac{I}{C} + R\frac{dI}{dt} = 0$$
$$I = I_0\exp\left(-\frac{t}{RC}\right)$$
$$I_0 = \frac{q_0}{RC} \Rightarrow I(t) = \frac{q_0}{RC}\exp{\left(-\frac{t}{RC}\right)}$$
$$Q = \int_0^tI^2Rdt = \int_0^t\frac{q_0^2}{RC^2}\exp\left\{-\frac{2t}{RC}\right\}dt =
\frac{q_0^2}{RC^2}\left(-\frac{RC}2\right)\exp\left\{-\frac{2t}{RC}\right\}\bigg|_0^t =
\frac{q_0^2}(1 - e^{-\frac{2t}{RC}})$$
* Задача 12.3
Конденсатор ёмкостью $C$, заряженный до разности потенциалов $U_0$, подключён к сопротивлению $R$ параллельно с
катушкой индуктивности $L$. Найти зависимость напряжения на конденсаторе от времени.

В цепи возникнет колебательный процесс перетекания заряда между пластинами конденсатора. Из-за сопротивления
колебания будут затухающими.
Первое правило Киргхофа:
$$-(I_1 + I_2 + I_3) = 0$$
Вследствие параллельного соединения напряжения на конденсаторе, резисторе и катушке одинаковы.
$$I_2 = \frac{U_C}R$$
$$I_1 = C\frac{dU_C}{dt}$$
$$I_3 = \frac{1}L\int U_Cdt$$
$$C\frac{dU}{dt} + \frac{U_C}R + \frac{1}L\int U_Cdt = 0$$
$$U''_C + \frac{U'_C}{RC} + \frac{1}{LC}U_C = 0 \text{ - уравнение затухающих колебаний}$$
Общее решение УЗО имеет вид:
$$U_C(t) = (A\cos \omega t + B\sin \omega t)e^{-\delta t}$$
Где $\omega = \sqrt{\omega_0^2 - \delta^2}, \omega_0 = \frac{1}{LC}, \delta = \frac{1}{2RC}$.
Для нахождения $A$ и $B$ нам нужны начальные условия:
1. $U(0) = U_0$.
2. $I_3(0) = 0 \Rightarrow I_1(0) = -I_2(0)$.
$$U'_C(t) = -\delta e^{-\delta t}(A\cos\omega t + B\sin\omega t) + e^{-\delta t}(-\omega A\sin\omega t + B\omega\cos\omega t)$$
$$U'_C(0) = \ldots \Rightarrow B = -\frac{\delta U_0}\omega$$
Источник переменного напряжения поключен к цепи, состоящей из последовательно подключённых сопротивления $R$,
конденсатора $C$ и катушки $L$. $\varepsilon(t) = \varepsilon_0\cos\omega_0 t$.

Переходим к комплексной амплитуде: $\varepsilon = \overline{\varepsilon_0}e^{i\omega t} \Rightarrow I \sim \overline I_0e^{i\omega t + \varphi}$.
Тогда можно получить комплексные выражения для падений напряжения:
$$\overline U_R = \overline IR$$
$$\overline U_C = \frac{1}{i\omega C}\overline I$$
$$\overline U_L = i\omega L\overline I$$
Комплексные коэффициенты, имеющие размерность сопротивления, называются \textit{импедансами}.
$$Z_R = R, Z_C = \frac{1}{i\omega C}, Z_L = i\omega L$$
* Задача 12.6
См. рисунок в учебнике. Каковы должны быть $L, R_1, R_2, C$, чтобы $I_R = 0$?

$I_R = 0 \Leftrightarrow U_{AB} = 0$, поэтому задача сведётся к последовательному и параллельному соединению проводников.
$$\overline{I_1} = \frac{\overline\varepsilon}{Z_R + Z_L}$$
$$\overline{I_2} = \frac{\overline\varepsilon}{Z_C + Z_R}$$
$$\overline{U_{CA}} = \overline{I_1}Z_{R_2}$$
$$\overline{U_{CB}} = \overline{I_2}Z_C$$
ДЗ: Задачи 12.6, 12.8, 12.13, 12.17, 12.34
