#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+OPTIONS: toc:nil
#+OPTIONS: date:nil
#+OPTIONS: ':t
#+LANGUAGE: ru
#+TITLE: Фридрих Шлейермахер. Программа либеральной теологии и её критика
* Введение
Фридрих Шлейермахер оказал значительное влияние на развитие нынешней христианской мысли, его
называли "отцом церкви XIX века"^1. Он стоял в начале либеральной теологии -- крайне популярного
направления теологии в конце XIX-начале XX в. Либеральные теологи пытались "осовременить"
христианство и привести его в соответствие с достижениями науки, рационализировать Священное
Писание. Впоследствии это привело к сведению роли христианства до нравственного учения, а не
религиозного, и демифологизации Священного Писания. В этом реферате будет дан обзор идей
либеральной теологии и их критики более поздними теологами.
* Идеи либеральной теологии
В "речах о религии"^2 Ф. Шлейермахер высказывает тезисы о сути религии, образовавшие фундамент для либеральной теологии.

Ключевой тезис Шлейермахера -- религия порождается чувством абсолютной взаимозависимости, связи всех вещей в мире и целого.
По мнению Шлейермахера, это чувство необходимо возникает в любой лучшей душе одним из двух способов: либо путём наблюдения за
внешним миром и отыскания внутренней связи между всеми явлениями и событиями, либо путём рефлексии и отыскания всевозможных
проявлений целого внутри себя: "созерцайте самих себя с пристальным напряжением, отделите всё, что не есть ваше я, продолжайте
фиксировать ваше внутреннее содержание, -- и чем более, по мере удаления всего чуждого, ваша личность и ваше обособленное бытие
сужается и даже почти исчезает, тем яснее предстанет перед вами вселенная, тем прекраснее вы будете вознаграждены за ужас
самоуничтожения преходящего чувством вечного в вас"^2. Поскольку религия порождается чувством, область религии есть область
чувства, поэтому религию невозможно свести ни к науке, ни к нравственности, ведь наука относится к сфере разума, а нравственность
относится к сфере действия и человеческих взаимоотношений. Все же претензии к религии от того, что религии пытаются приписать то,
чем она не является, например, механизмы познания и описания мира или функции регулятора взаимоотношений между людьми. Также
Шлейермахер показывает губительность вмешательства государства в религию, в частности, попыток возлагания на религию
ответственности за поддержание авторитета государства.

Другим важным следствием чувственной природы религии является вторичность религиозной догматики, понятий и принципов религии.
Система понятий и принципов есть лишь отражение религиозного чувства и потому по определению вторична и не может быть основой
религии. Религиозная догматика и обряды есть выражение религии на языке современной культуры, из чего вытекает два важных
следствия. Во-первых, все религии равноправны, поскольку являются одним и тем же, но только в конкретном культурном контексте
(вообще говоря, стоит указать, что это относится к так называемым "позитивным" религиям, вроде христианства или ислама;
языческие "естественные" религии Шлейермахер считает слишком неявными, неопределёнными, чтобы они могли служить выражением
религиозного чувства). Во-вторых, очень важно уметь трактовать священные тексты и адаптировать их к новым культурным условиям.
Эта идея легла в основу герменевтики.

Учение о герменевтике стало основой для демифологизации Священного Писания, вплоть до отказа от божественности Иисуса Христа
и признания его лишь идеалом нравственного человека, не закладывавшего никакого вероучения.
Стоит заметить, что такая редукция идёт вразрез с идеей Шлейермахера о несводимости религии к нравственности.
* Критика либеральной теологии
Кьеркегор в "страхе и трепете"^3 показывает, что единственным способом постижения Бога является
осознание противоречия и асбурда, заложенного в возможности прямого общения с Богом. Тем самым
Кьеркегор критикует идею о возможности прихода к Богу через наблюдение за миром и рефлексию.
Карл Барт развивает концепцию трансцендентного Бога, утверждая что поскольку напрямую осознать
Бога невозможно, претензии либеральной теологии на адекватность толкования Священного Писания
не могут быть состоятельными(что, в принципе, согласуется с идеями Шлейерхмахера, поскольку
и Священное Писание, и попытки его толкования есть лишь "проекции" целого на современную
обстановку). Историческая критика Библии с точки зрения Барта же есть попытка поставить её
под свой контроль и фактически выстроить теологию на основе антропологии. По этой же причине
и догматика будет всегда оставаться относительной и неполной, в чём-то заблуждающейся.

Несмотря на то, что казалось бы в отношении толкования Священного Писания идеи Барта и Кьеркегора
казалось бы не противоречат идеям Шлейермахера, между воззрениями либеральных и диалектических
теологов есть одно существенное различие. Как было указано в предыдущей части, Шлейермахер
указывал религиозное чувство как нечто врождённое, присущее каждому человеку. У Кьеркегора и
Барта же Бог обязательно трансцендентален, он может быть воспринят только через противоречие.

Кьеркегор и Барт также чётко различают истинное Христианство и его институциональные формы,
Церковь, веру и религию. Поскольку вера это парадоксальное откровение Бога-инкогнито, её
выражением не может быть ни религия, ни Церковь, ни культура. У Шлейермахера также было
похожее разделение между Церковью и естественной верой, но у него это различие заключалось
в том, что Церковь должна быть посредником между религией и массами, и за счёт этого Церковь
будет неизбежно искажать религию.
* Заключение
В заключение хотелось бы рассмотреть комментарий А. Уминского о "Евангелии страданий" Кьеркегора^4,
чтобы показать, что идеи Кьеркегора актуальны и сейчас. В этом комментарии автор показывает,
что в результате долгого "благополучия" христианства произошло искажение самой
сути понятия "христианин", что привело к дискредитации христианства в XX веке с одной стороны,
и появлению идеи "богословия процветания" -- с другой. Именно поэтому, несмотря на то, что
казалось бы Церковь сейчас много делает, её слова могут быть не услышанными. Благополучная Церковь
и благополучная церковная жизнь уже не воспринимаются как следование за Христом. В самом деле, ведь
следование за Христом подразумевает не только единоразовый отказ от всего и от себя("взваливание на
себя креста"), но каждодневную готовность оставить всё и броситься в неизвестность("нести свой крест").
Более того, настоящее следование за Христом предполагает следование в одиночку, без учителя. Таким
образом, по мнению автора, Кьеркегор утверждает, что благочестивый благополучный человек, исправно
ходящий в церковь и придерживающийся традиций, тем не менее, не может считаться христианином, если он
не готов в любой момент отказаться от себя и своего благополучия. Вопрос "благополучности" христианства
сейчас актуален как никогда.
* Источники
$[1]$: Barth К. Die protecstantische Theologie im 19. Jahrhundert. ihre Vorgeschichle und ihre Geschichtc. Zürich, 1952. S. 379. \\
$[2]$: Friedrich Schleiermacher: Über die Religion. Hamburg 1958, S. 1.\\
$[3]$: Fear and Trembling; Copyright 1843 Søren Kierkegaard – Kierkegaard's Writings; 6 – copyright 1983 – Howard V. Hong\\
$[4]$: https://www.pravmir.ru/o-knige-s-kerkegora/
