#+LATEX_COMPILER: xelatex
#+LANGUAGE: ru

#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}
#+LATEX_HEADER:\usepackage{fontspec}
#+LATEX_HEADER:\setmainfont{CMU Serif}
#+LATEX_HEADER:\setsansfont{CMU Sans Serif}
#+LATEX_HEADER:\setmonofont{CMU Typewriter Text}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}\setcounter{stnmt}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

#+LATEX_HEADER:\newcounter{stnmt}\setcounter{stnmt}{0}
#+LATEX_HEADER:\def\st{\par\smallskip\refstepcounter{stnmt}\textbf{\arabic{stnmt}}}
#+LATEX_HEADER:\newtheorem*{Statement}{Утверждение \st}

#+begin_export latex
\pagebreak
#+end_export
* Представление функций алгебры логики(ФАЛ) дизъюнктивными нормальными формами (ДНФ) и его геометрическая интерпретация. Совершенная ДНФ и критерий единственности ДНФ.
  Множество $B^n$, где $B = \{0, 1\}, n \in \mathbb{N}$ называется /единичным кубом/ или /гиперкубом/ размерности $n$. Отношение перестановочности разбивает куб $B^n$ на классы эквивалентности -- /слои/ куба $B_0^n, \ldots, B_n^n$, где $B_i^n$ -- множество наборов с $i$ единицами, $|B_i^n| = \begin{pmatrix}n \\ i\end{pmatrix}$.

  На гиперкубе введём отношение лексикографического линейного порядка, которое задаётся нумерацией \nu:
#+begin_export latex
\begin{equation*}
\nu(\alpha_1, \ldots, \alpha_n) = \sum_{i = 1}^n\alpha_i2^{n - i}
\end{equation*}
#+end_export
Иными словами, в качестве номера набора $\alpha_1, \ldots, \alpha_n$ объявляется число, двоичная запись которого, дополненная слева нулями до длины $n$, совпадает с набором $\alpha_1, \ldots, \alpha_n$. Множество наборов, имеющих номера из отрезка $[a, b]$, называется /отрезком куба/ B^n.

/Расстоянием Хэмминга/ \rho(a, b) между наборами $a$ и $b$ называется количество разрядов, в которых наборы отличаются друг от друга. Наборы, находящиеся друг от друга на расстоянии $n$, называются /противоположными/, а наборы, отличающиеся только в одном разряде, называются /соседними/. Множество $\{b: \rho(a, b) = t\}$ называется /сферой/ радиуса $t$ с центром в $a$, соответственно, множество $\{b: \rho(a, b) \leq t\}$ называется /шаром/ радиуса $t$ с центром в $a$. i-й слой куба $B^n$ является сферой радиуса $i$ с центром в наборе $\widetilde{0} = (0, 0, \ldots, 0)$ и сферой радиуса $n - i$ с центром в наборе $\widetilde{1} = (1, 1, \ldots, 1)$.

На множестве $B^n$ введём отношение частичного порядка:
#+begin_export latex
\begin{equation*}
\alpha = (\alpha_1, \ldots, \alpha_n) \leq \beta = (\beta_1, \ldots, \beta_n) \Leftrightarrow \alpha_i \leq \beta_i \forall i = \overline{1, n}.
\end{equation*}
#+end_export
При этом $a < b$, если $a \leq b$  и $a \neq b$. Наборы $a, b$ для которых $a \leq b$ или $b \leq a$ называются /сравнимыми/, в противном случае /несравнимыми/.

Для набора $\gamma = (\gamma_1, \ldots, \gamma_n)$ длины $n$ над множеством $\{0, 1, 2\}$ через $\Gamma_{\gamma}$ обозначим множество всех тех наборов $\alpha = (\alpha_1, \ldots, \alpha_n)$ куба $B^n$, для которых $\alpha_i = \gamma_i \forall i \in \overline{1, n}: \gamma_i \neq 2$. Это множество называется /гранью/ куба $B^n$, число $n - r$, равное числу двоек в наборе $\gamma$, называется /размерностью/ этой грани, а число $r$ -- её /рангом/. Грань $\Gamma_{\gamma}$ представляет собой подкуб размерности $n - r$ куба $B^n$.

Будем рассматривать счётный упорядоченный алфавит булевых переменных(БП) $\mathfrak{X} = \{x_1, x_2, \ldots, x_n, \ldots\}$ и будем рассматривать функции алгебры логики(ФАЛ) над переменными из $\mathfrak{X}$. Множество таких функций будем обозначать $P_2(\mathfrak{X})$ или $P_2$, или $P_2(n)$. Для задания ФАЛ $f$ из $P_2(n)$ можно использовать её таблицу значений -- матрицу $M$ из множества $B^{2^n\times(n + 1)}$, i-я строка, $i \in \overline{1, 2^n}$ которой имеет вид
#+begin_export latex
\begin{equation*}
M(i, [1, n + 1]) = (\alpha, f(\alpha))
\end{equation*}
#+end_export
Столбец $M([1, 2^n], n = 1)$, однозначно задающий ФАЛ $f$, считается её столбцом значений и записывается в виде строки, обозначаемой $\widetilde{\alpha}_f$. Кроме того, ФАЛ $f$ однозначно задаётся своим /характеристическим множеством/:
#+begin_export latex
\begin{equation*}
N_f = \{\alpha | \alpha \in B^n, f(\alpha) = 1\}
\end{equation*}
#+end_export
В этом случае ФАЛ $f$ является характеристической функцией множества $N_f$.

Функции $\&, \vee$ и $\oplus$ коммутативны и ассоциативны, а $\&$ также дистрибутивна относительно $\vee$ и $\oplus$. Кроме того, имеют место следующие тождества:
#+begin_export latex
\begin{equation}
x\cdot0 = x\cdot\overline{x} = x\oplus x = 0, x\vee1 = x\vee\overline{x} = x\oplus\overline{x} = 1,
\end{equation}
\begin{equation}
x\cdot x = x\vee x = x\vee 0 = x\oplus 0
\end{equation}
\begin{equation}
\label{eq:merge}
x_1\vee x_1x_2 = x_1
\end{equation}
#+end_export

ФАЛ вида
#+begin_export latex
\begin{equation*}
f(x_1, \ldots, x_n) = a_1x_1 \oplus \ldots \oplus a_nx_n \oplus a_0
\end{equation*}
#+end_export
называются /линейными/. Существенными БП этой ФАЛ являются те и только те $x_i$, для которых $a_i = 1$.

Рассмотрим формулы над множеством
#+begin_export latex
\begin{equation*}
\text{Б}_0 = \{x_1\cdot x_2, x_1\vee x_2, \overline{x}_1\}
\end{equation*}
#+end_export
Функции $x_i$ и $\overline{x}_i$ будем называть /буквами/ БП $x_i$ и будем считать, что
$x_i^0 = \overline{x}_i, x_i^1 = x_i$. Конъюнкция(дизъюнкция) $r, 1 \leq r \leq n$, букв различных БП из $X(n)$ называется /элементарной конъюнкцией(элементарной дизъюнкцией) ранга $r$ от БП $X(n)$/. Дизъюнкция различных элементарных конъюнкций называется /дизъюнктивной нормальной формой/ (ДНФ), а конъюнкция различных элементарных дизъюнкций называется /конъюнктивной нормальной формой/ (КНФ). При этом ДНФ (КНФ) считается /совершенной/, если все её ЭК(соответственно, ЭД) существенно зависят от одних и тех же БП, а их ранг равен числу этих БП. Число ЭК в ДНФ(ЭД в КНФ) $\mathfrak{A}$ называется /длиной/ ДНФ(КНФ) и обозначается $\lambda(\mathfrak{A})$. Любую ФАЛ $f(x_1, \ldots, x_n)$, отличную от константы, можно представить в виде её совершенных ДНФ и КНФ следующим образом:
#+begin_export latex
\begin{equation}
f(x_1, \ldots, x_n) = \bigvee\limits_{(\alpha_1, \ldots, \alpha_n) \in N_f}x_1^{\alpha_1}\ldots x_n^{\alpha_n} =
\bigwedge\limits_{(\beta_1, \ldots, \beta_n) \in \overline{N}_f}(x_1^{\overline{\beta}_1}\lor\ldots\lor x_n^{\overline{\beta}_n})
\end{equation}
#+end_export
Поскольку любую ФАЛ $f$ из $P_2(n)$, отличную от нуля, можно представить в виде совершенной ДНФ, а ФАЛ $f \equiv 0$ представляется формулой $x_1\cdot\overline{x}_1$, то множество Б_0 является базисом $P_2$.

Совершенную ДНФ можно обобщить с помощью /представления Шеннона/:
#+begin_export latex
\begin{equation}
f(x', x'') = \bigwedge\limits_{\sigma'' = (\sigma_{q + 1}, \ldots, \sigma_n)}x_{q + 1}^{\sigma_{q + 1}}\ldots
x_n^{\sigma_n}f_{\sigma''}(x')
\end{equation}
#+end_export
Здесь $q \in [0, n], x' = (x_1, \ldots, x_q), x'' = (x_{q + 1}, \ldots, x_n)$ и $f_{\sigma''}(x') = f(x', \sigma'')$. При $q = 0$ все ФАЛ $f_{\sigma''}(x')$ являются константными.

Представление ФАЛ в виде ДНФ или КНФ имеет простую геометрическую интерпретацию. Пусть
#+begin_export latex
\begin{equation}
\label{eq:dnf}
f(x_1, \ldots, x_n) = K_1 \lor \ldots K_s = \mathfrak{A},
\end{equation}
\begin{equation}
\label{eq:knf}
f(x_1, \ldots, x_n) = J_1\ldots J_t = \mathfrak{B},
\end{equation}
#+end_export
где $K_1, \ldots, K_s(J_1, \ldots, J_t)$ -- различные ЭК(ЭД) от БП $x_1, \ldots, x_n$. Эти представления эквивалентны следующим покрытиям множеств $N_f$ и $\overline{N}_f$ гранями куба $B^n$:
#+begin_export latex
\begin{equation}
\label{eq:covnf}
N_f = N_{K_1}\cup\ldots\cup N_{K_s},
\end{equation}
\begin{equation}
\label{eq:convnotnf}
\overline{N}_f = \overline{N}_{J_1}\cup\ldots\cup\overline{N}_{J_t}.
\end{equation}

\begin{Lemma}
Совершенная ДНФ ФАЛ $f, f \in P_2(n)$, является единственной ДНФ от БП $X(n)$, которая реализует эту ФАЛ, тогда и только тогда, когда в $N_f$ нет соседних наборов.
\end{Lemma}
\begin{proof}
Совершенная ДНФ ФАЛ $f$ является единственной ДНФ от БП $X(n)$, которая реализует эту ФАЛ, тогда и только тогда, когда в множестве $N_f$ нет граней размерности больше 0, что и означает, что в $N_f$ нет соседних наборов.
\end{proof}
\pagebreak
\zall
#+end_export
* Сокращённая ДНФ и способы её построения.
  Будем говорить, что ФАЛ $f'$ /имплицирует/ ФАЛ $f''$ или ФАЛ $f''$ /поглощает/ ФАЛ $f'$, если $N_{f'} \subseteq N_{f''}$, т. е. $f' \rightarrow f'' \equiv 1$. ЭК, имплицирующая ФАЛ $f$, называется /импликантой/ этой ФАЛ. $f' \rightarrow f'' \Leftrightarrow f'' = f'\lor f'' \text{ или } f' = f'\cdot f''$.

  ДНФ $\mathfrak{A}$ вида \eqref{eq:dnf} будем называть ДНФ /без поглощений/ ЭК, если ни одна из граней $N_{K_1}, \ldots, N_{K_s}$ не содержится ни в одной из других граней покрытия \eqref{eq:covnf}. Это означает, что ни одна из ЭК $K_i, i = \overline{1, s}$ не является импликантой другой ЭК $K_j, j = \overline{1, s}, i \neq j$. Используя тождество поглощения \eqref{eq:merge}, можно из любой ДНФ $\mathfrak{A}$ получить ДНФ $\widehat{\mathfrak{A}}$ без поглощений ЭК.

  Импликанта $K$ ФАЛ $f$ называется /простой импликантой/ этой ФАЛ, если она не поглощается никакой другой импликантой этой ФАЛ, т. е. не существует такой импликанты $f K'$ такой, что $K = K'\cdot K''$. Это означает, что в простую импликанту $f$ не входят буквы несущественных БП $f$ и из любой импликанты $f$ можно получить простую импликанту удалением некоторых букв. Из последнего следует, что любая импликанта ФАЛ $f$ имплицирует некоторую простую импликанту $f$, что даёт геометрический смысл простой импликанты: простые импликанты ФАЛ $f$ соответствуют максимальным по включению граням $N_f$.

  Дизъюнкция всех простых импликант ФАЛ $f$ называется её /сокращённой/ ДНФ. Сокращённая ДНФ является ДНФ без поглощений и ей соответствует покрытие множества $N_f$ всеми максимальными по включению гранями множества $N_f$ этой ФАЛ, что даёт геометрический метод построения сокращённой ДНФ.

  Для более наглядного построения сокращённой ДНФ для ФАЛ $f$ в случае небольшого количества переменных, её часто представляют в виде /карты Карно/. Переменные $f$ делятся на две группы, количество переменных в которых отличается не более, чем на 1, в шапке таблицы записываются значения наборов из этих групп в порядке кода Грея(т. е. так, чтобы соседние наборы отличались ровно в одном разряде). В ячейках таблицы записываются соответствующие значения функции, а противоположные стороны таблицы отождествляются по принципу "тора". Квадрат или прямоугольник из соседних клеток таблицы с площадью, равной степенью двойки, соответствует некоторой грани булева куба.
  #+begin_export latex
  \begin{Theorem}
Пусть $\mathfrak{A'}$ и $\mathfrak{A''}$ -- сокращённые ДНФ ФАЛ $f'$ и $f''$ соответственно, а ДНФ $\mathfrak{A}$ без поглощений получается из формулы $\mathfrak{A'}\cdot\matfrak{A''}$ путём раскрытия скобок и приведения подобных слагаемых. Тогда $\mathfrak{A}$ -- сокращённая ДНФ ФАЛ $f = f'\cdot f''$.
  \end{Theorem}
  \begin{proof}
Достаточно показать, что в $\mathfrak{A}$ входит любая простая импликанта ФАЛ $f$. Пусть ЭК $K$ является простой импликантой ФАЛ $f$, а значит, является импликантой как $f'$, так и $f''$. Поскольку $\mathfrak{A'}$ и $\mathfrak{A''}$ являются сокращёнными ДНФ, в них найдутся ЭК $K'$ и $K''$, имплицириуемые ЭК $K$. Это значит, что в ДНФ $\mathfrak{A}$ войдёт ЭК $\widetilde{K}$, имплицируемая $K'\cdot K''$. Эта ЭК получится в результате раскрытия скобок и приведения подобных в формуле $\mathfrak{A'}\cdot\mathfrak{A''}$. Поскольку ЭК $K$ имплицирует ФАЛ $K'\cdot K''$, то $K$ имплицирует и $\widetilde{K}$. Поскольку $\widetilde{K}$ является импликантой $f$ и при этом имплицируется $K$, то $\widetile{K} = K$, так как $K$ -- простая импликанта $f$.
  \end{proof}
\begin{Consequence}
Если ДНФ $\mathfrak{A}$ без поглощений получается из КНФ $\mathfrak{B}$ ФАЛ $f$ в результате раскрытия скобок и приведения подобных, то $\mathfrak{A}$ -- сокращённая ДНФ ФАЛ $f$.
\end{Consequence}
\begin{proof}
Доказательство проводится индукцией по числу множителей в КНФ $\mathfrak{B}$.
\end{proof}
  #+end_export

  Метод Блейка позволяет получить сокращённую ДНФ ФАЛ $f$ из произвольной ДНФ этой ФАЛ с помощью эквивалентных преобразований на основе тождества обобщённого склеивания:
  #+begin_export latex
  \begin{equation*}
x_1x_2\lor\overline{x}_1x_3 = x_1x_2\lor\overline{x}_1x_3\lor x_2x_3
  \end{equation*}
  #+end_export

  Любая ДНФ $\mathfrak{A'}$, которую можно получить из ДНФ $\mathfrak{A}$ путём формирования в ней с помощью тождеств ассоциативности и коммутативности подформул вида $x_iK'\lor\overline{x}_iK''$, применения к этим подформулам тождества обобщённого склеивания:
  #+begin_export latex
  \begin{equation}
  \label{eq:gengluing}
x_iK'\lor\overline{x}_iK'' = x_iK'\lor\overline{x}_iK''\lor K'K''
  \end{equation}
  #+end_export
и последующего приведения подобных слагаемых, называется /расширением/ ДНФ $\mathfrak{A}$. Расширение $\mathfrak{A'}$ ДНФ $\mathfrak{A}$ называется /строгим/, если $\mathfrak{A'}$ содержит ЭК, не являющуюся импликантой ни одной ЭК из $\mathfrak{A}$. Сокращённая ДНФ не имеет строгих расширений. Также, в результате построения последовательных строгих расширений из любой ДНФ можно получить ДНФ без поглощений ЭК, которая не имеет строгих расширений. Процесс построения строгих расширений сойдётся, поскольку число импликант функции $f$ конечно, а все слагаемые, добавляемые при построении расширений, являются импликантами $f$.
#+begin_export latex
\begin{Theorem}
ДНФ без поглощений ЭК является сокращённой ДНФ тогда и только тогда, когда она не имеет строгих расширений.
\end{Theorem}
\begin{proof}
Достаточно убедиться в том, что ДНФ $\mathfrak{A}$ без поглощений ЭК, не имеющая строгих расширений, содержит все простые импликанты реализуемой ею ФАЛ $f$. Пусть $X(n) = \{x_1, \ldots, x_n\}$ -- множество БП ДНФ $\mathfrak{A}$, а $K$ -- простая импликанта $f$, которая не входит в $\mathfrak{A}$. Рассмотрим множество $\mathcal{K}$, состоящее из всех тех элементарных конъюнкций от БП $X(n)$, которые являются импликантами $f$, но не являются импликантами ни одной ЭК из $\mathfrak{A}$. Множество $\mathcal{K}$ непусто, поскольку содержит $K$, но при этом не содержит ЭК ранга $n$, поскольку любая ЭК вида $x_1^{\alpha_1}\ldots x_n^{\alpha_n}$, где $\alpha = (\alpha_1, \ldots, \alpha_n) \in N_f$, является импликантой той ЭК из $\mathfrak{A}$, которая обращается в 1 на наборе $\alpha$.

Пусть теперь $k$ -- ЭК максимального ранга в $\mathcal{K}$, причём $R(k) < n$, и пусть буквы некоторой БП $x_i, 1 \leq i \leq n$, не входят в $k$. Тогда, в силу выбора ЭК $k$ и свойств ДНФ $\mathfrak{A}$, ЭК вида $x_i\cdot k$ (вида $\overline{x}_i\cdot k$) должна быть импликантой некоторой ЭК вида $x_i\cdot K'$ (вида $\overline{x}_i\cdot K''$) из $\mathfrak{A}$, где ЭК $K'$ и $K''$ состоят из букв ЭК $k$. Следовательно, ЭК $k$ является импликантой ЭК $\widetilde{K}$, равной $K'\cdot K''$, а ЭК $\widetilde{K}$, в свою очередь, является импликантой некоторой ЭК из $\mathfrak{A}$. Действительно, ДНФ $\mathfrak{A}$ не имеет строгих расширений и поэтому содержит ЭК, которая имплицируется ЭК $\widetilde{K}$, получающейся из подформулы $x_iK'\lor\overline{x}_iK''$ в результате преобразования \eqref{eq:gengluing}. Таким образом, ЭК $k$ является импликантой некоторой ЭК из $\mathfrak{A}$ и не может входить в $\mathcal{K}$. Полученное противоречие доказывает, что ЭК $K$ входит в $\mathcal{A}$.
\end{proof}
\begin{Consequence}
Из любой ДНФ $\mathfrak{A}$ ФАЛ $f$ можно получить сокращённую ДНФ этой ФАЛ в результате построения последовательных строгих расширений до получения ДНФ без поглощений ЭК, не имеющих строгих расширений.
\end{Consequence}
\begin{proof}
Из любой ДНФ $\mathfrak{A}$ ФАЛ $f$ можно получить ДНФ без поглощений ЭК, которая не имеет строгих расширений. По доказанной теореме эта ДНФ является сокращённой ДНФ.
\end{proof}
\pagebreak
\zall
#+end_export
* Тупиковая ДНФ, ядро и ДНФ пересечение тупиковых. ДНФ Квайна, критерий вхождения простых импликант в тупиковые ДНФ и его локальность.
  Будем говорить, что ДНФ $\mathfrak{A}$, реализующая ФАЛ $f$, является /тупиковой/ ДНФ, если $f \neq \mathfrak{A'}$ для любой ДНФ $\mathfrak{A'}$, полученной из $\mathfrak{A}$ в результате удаления некоторых букв или целых ЭК. Таким образом, в тупиковую ДНФ могут входить только простые импликанты этой ФАЛ и $\mathfrak{A}$ является ДНФ без поглощений ЭК. С геометрической точки зрения тупиковая ДНФ $\mathfrak{A}$ ФАЛ $f$ задаёт тупиковое покрытие множества $N_f$ максимальными гранями ФАЛ $f$ и обратно. Это означает, что никакая из граней, соответствующих некоторой ЭК ДНФ $f$ не содержится в объединении граней, соответствующих остальным ЭК.

  Построение тупиковых ДНФ является промежуточным этапом при построении /минимальной/ (/кратчайшей/) ДНФ, т. е. ДНФ, имеющей минимальный ранг (длину) среди всех ДНФ, реализующих $f$. Минимальная ДНФ всегда есть тупиковая, а среди кратчайших ДНФ всегда найдётся тупиковая.
  При построении тупиковых ДНФ бывает полезно знать ДНФ /пересечение тупиковых/ (ДНФ $\cap T$) ФАЛ $f$, т. е. дизъюнкцию всех тех различных простых импликант этой ФАЛ, которые входят в любую тупиковую ФАЛ $f$.

  Набор $\alpha \in B^n$ называется /ядровой точкой/ ФАЛ $f$, если $\alpha \in N_f$ и $\alpha$ покрывается только одной максимальной гранью $f$. При этом максимальная грань $N_k$, содержащая эту точку, называется /ядровой гранью/ $f$, а совокупность различных ядровых граней называется /ядром/ $f$.

  #+begin_export latex
  \begin{Lemma}
ДНФ $\cap T$ ФАЛ $f$ состоит из тех и только тех простых импликант ФАЛ $f$, которые соответствуют ядровым граням этой ФАЛ.
  \end{Lemma}
  \begin{proof}
Пусть тупиковая ДНФ $\mathfrak{A}$ ФАЛ $f$ не включает в себя простую импликанту $K$, которая соответствует ядровой грани $N_K$ ФАЛ $f$, содержащей ядровую точку $\alpha$ этой ФАЛ. Тогда ни одна другая максимальная грань не содержит точки $\alpha$ и поэтому все отличные от $K$ простые импликанты $f$ обращаются в 0 на наборе $\alpha$. Это значит, что ДНФ $\mathfrak{A}$ также равна нулю на этом наборе, т. е. $f(\alpha) = 0$. Полученное противоречие с тем, что $\alpha \in N_f$ означает, что ЭК $K$ должна входить в любую тупиковую ДНФ ФАЛ $f$.

Пусть теперь простая импликанта $K$ ФАЛ $f$ соответствует грани $N_K$, не входящей в ядро ФАЛ $f$. Это значит, что каждая точка грани $N_K$ покрывается некоторой другой максимальной гранью, отличной от $N_K$. Следовательно, все отличные от $N_K$ максимальные грани ФАЛ $f$ образуют покрытие множества $N_f$, из которого можно выделить тупиковое подпокрытие, соответствующее тупиковой ДНФ $f$, не содержащей ЭК $K$.
  \end{proof}
  #+end_export

  При построении тупиковых ДНФ ФАЛ $f$ наряду с ДНФ пересечение тупиковых полезно знать ДНФ /сумма тупиковых/ (ДНФ $\Sigma T$) ФАЛ $f$, т. е. дизъюнкцию всех тех различных простых импликант этой ФАЛ, которые входят хотя бы в одну тупиковую ДНФ ФАЛ $f$. ДНФ $\Sigma T$ $f$ в общем случае не реализует функцию $f$ и даже может быть пустой, в то время как ДНФ $\Sigma T$ ФАЛ $f$ всегда реализует эту ФАЛ, содержится в её сокращённой ДНФ и может с ней совпадать.

  Будем называть ФАЛ /ядровой/, если все её максимальные грани являются ядровыми. Из только что доказанной леммы следует, что сокращённая ДНФ ядровой ФАЛ является её единственной тупиковой ДНФ.

  ДНФ, получающаяся из сокращённой ДНФ ФАЛ $f$ удалением тех ЭК $K$, для которых грань $N_K$ покрывается ядром ФАЛ $f$, но не входит в него, называется /ДНФ Квайна/ этой ФАЛ. ДНФ Квайна $f$ включает в себя ДНФ $\Sigma T$ и содержится в её сокращённой ДНФ.

  Для ФАЛ $f$ и набора $\alpha \in N_f$ обозначим через $\Pi_{\alpha}(f)$ множество всех происходящих через $\alpha$ максимальных граней $f$, которое мы будем называть /пучком/ $f$ /через точку $\alpha$/. Точку $\alpha \in N_f$ будем называть /регулярной точкой/ $f$, если $\exists \beta \in N_f: \Pi_{\beta}(f) \subset \Pi_{\alpha}(f)$. Для любой регулярной точки $\alpha$ найдётся нерегулярная точка $\beta \in N_f: \Pi_{\beta}(f) \subset \Pi_{\alpha}(f)$.

  Любая неядровая точка ядровой грани регулярна. Грань $N_K$ ФАЛ $f$ называется /регулярной гранью/ этой ФАЛ, если все точки $N_K$ регулярны. Грань, которая не входит в ядро, но покрывается им, является регулярной.
  #+begin_export latex
  \begin{Theorem}
Простая импликанта $K$ ФАЛ $f$ входит в ДНФ $\Sigma T$ тогда и только тогда, когда грань $N_K$ не является регулярной гранью этой ФАЛ.
  \end{Theorem}
\begin{proof}
Пусть $\alpha_1, \ldots, \alpha_s$ -- все регулярные точки $f$. Тогда для любого $j, j = \overline{1, s}$ найдётся нерегулярная точка $\beta_j$ $f$ такая, что любая максимальная грань, проходящая через $\beta_j$, проходит и через $\alpha_j$. Тогда любой набор максимальных граней, покрывающих точки $\beta_1, \ldots, \beta_s$, покрывает и точки $\alpha_1, \ldots, \alpha_s$. Это значит, что грань $N_K$, состоящая только из регулярных точек, не может входить в тупиковое покрытие множества $N_f$ максимальными гранями, что означает, что ЭК $K$ не может входить в ДНФ $\Sigma T$ ФАЛ $f$.

Пусть теперь $N_K$ -- нерегулярная грань $f$, которая содержит нерегулярную точку $\alpha$ и пусть $N_f \backslash N_K = \{\beta_1, \ldots, \beta_q\}$. Из нерегулярности точки $\alpha$ следует, что для любого $j, j = \overline{1, q}$ пучок $\Pi_{\beta_j}(f)$ не может быть строго вложен в $\Pi_{\alpha}(f)$. Кроме того, $\Pi_{\beta_j}(f) \neq \Pi_{\alpha}(f)$, так как $N_K \in \Pi_{\alpha}(f) \backslash \Pi_{\beta_j}(f) \Rightarrow \exists N_{K_j} \in \Pi_{\beta_j}: \beta_j \in N_{K_j}, \alpha \notin N_{K_j}$. Это означает, что из покрытия $N_f$ максимальными гранями $N_K, N_{K_1}, \ldots, N_{K_q}$ нельзя удалить грань $N_K$, т. к. только она покрывает точку $\alpha$. Это значит, что любое тупиковое подпокрытие этого покрытия будет соответствовать тупиковой ДНФ, содержащей ЭК $K$.
\end{proof}
  #+end_export

  Для каждой максимальной грани $\mathcal{N}$ ФАЛ $f$ положим $S_0(\mathcal{N}, f) = \{\mathcal{N}\}$, а затем индукцией по $r, r = 1, 2, \ldots$ определим множество $S_r(\mathcal{N}, f)$ как множество всех максимальных граней $f$, которые имеют непустое пересечение c хотя бы одной гранью из множества $S_{r - 1}(\mathcal{N}, f)$. Множество $S_r(\mathcal{N}, f)$ будем называть /окрестностью порядка $r$ грани $\mathcal{N}$ функции $f$/.

  Вопрос о вхождении простой импликанты $K$ ФАЛ $f$ в ДНФ $\cap T$ (ДНФ $\Sigma T$) этой ФАЛ можно решить, рассматривая окрестность $S_1(N_K, f)(S_2(N_K, f))$. Для проверки грани $N_K$ на её вхождение в ДНФ Квайна ФАЛ $f$ также достаточно рассмотреть окрестность порядка 2.
* Особенности ДНФ линейных и монотонных ФАЛ. Функция покрытия, таблица Квайна и построение всех тупиковых ДНФ.
* Градиентный алгоритм и оценка длины градиентного покрытия, лемма о протыкающих наборах. Использование градиентного алгоритма для построения ДНФ.
* Задача минимизации ДНФ. Поведение функции Шеннона и оценки типичных значений для ранга и длины ДНФ.
* Алгоритмические трудности минимизации ДНФ и оценки максимальных значений некоторых связанных с ней параметров. Теорема Журавлёва о ДНФ сумма минимальных
* Формулы алгебры логики, их эквивалентные преобразования с помощью тождеств. Полнота системы основных тождеств для эквивалентных преобразований формул базиса \text{Б}_0 = {&, \lor, \neg}.
* Задание формул с помощью деревьев, функционалы их сложности и соотношения между ними. Оптимизация подобных формул по глубине.
* Схемы из функциональных элементов (СФЭ). Изоморфизм и эквивалентность схем, функционалы их сложности, операции приведения. Верхние оценки числа формул и СФЭ в базисе Б_0
* Контактные схемы (КС) и \pi-схемы, их изоморфизм, эквивалентность, сложность, операции приведения. Структурное моделирование некоторых формул и \pi-схем. Оценки числа КС и числа \pi-схем. Особенности функционирования многополюсных КС.
* Эквивалентные преобразования СФЭ и моделирование с их помощью формульных преобразований. Моделирование эквивалентных преобразований формул и схем в различных базисах, теорема перехода.
* Эквивалентные преобразования КС. Основные тождества, вывод вспомогательных (дополнительных) и обобщённых тождеств.
* Полнота системы основных тождеств. Отсутствие конечной полной системы тождеств в классе всех КС.
* Задачи синтеза. Методы синтеза схем на основе ДНФ и связанные с ними верхние оценки сложности функций.
* Простые нижние оценки сложности ФАЛ, реализация некоторых ФАЛ и минимальность некоторых схем.
* Разложение ФАЛ и операция суперпозиции схем. Корректность суперпозиции для некоторых типов схем, разделительные КС и лемма Шеннона.
* Каскадные КС и СФЭ. Метод каскадов и примеры его применения, метод Шеннона.
* Нижние мощностные оценки функций Шеннона, их обобщение на случай синтеза схем для ФАЛ из специальных классов.
* Дизъюнктивно-универсальные множества ФАЛ. Асимптотически наилучший метод О. Б. Лупанова для синтеза СФЭ в базисе Б_0.
* Регулярные разбиения единичного куба и моделирование ФАЛ переменными. Асимптотически наилучший метод синтеза формул в базисе Б_0.
* Асимптотически наилучший метод синтеза КС. Синтез схем для ФАЛ из некоторых специальных классов.
* Задача контроля схем и тесты для таблиц. Построение всех тупиковых тестов, оценки длины диагностического теста.
* Самокорректирующиеся КС и методы их построения. Асимптотически наилучший метод синтеза КС, корректирующих 1 обрыв (1 замыкание).
* Доказательство теоремы Кука. Примеры NP-полных проблем, связанных с графами.
* Некоторые модификации основных классов схем (BDD, вычисляющие программы, схемы на КМОП-транзисторах и др.), ориентированные на программно-аппаратную реализацию ФАЛ.
* Реализация автоматных функций схемами из функциональных элементов и элементов задержки, схемы с "мгновенными" обратными связями.
