#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

* Семинар 1
** Задача 1
 Построить СДНФ функции:
 |-------+-------+-------+---|
 | $x_1$ | $x_2$ | $x_3$ | f |
 |-------+-------+-------+---|
 |     0 |     0 |     0 | 1 |
 |     0 |     0 |     1 | 0 |
 |     0 |     1 |     0 | 1 |
 |     0 |     1 |     1 | 1 |
 |     1 |     0 |     0 | 0 |
 |     1 |     0 |     1 | 1 |
 |     1 |     1 |     0 | 0 |
 |     1 |     1 |     1 | 1 |
 |-------+-------+-------+---|
*** Решение
    #+begin_export latex
    \begin{equation}
 D_f^s(x_1, x_2, x_3) = \overline{x_1}\overline{x_2}\overline{x_3}\vee\overline{x_1}x_2\overline{x_3}
 \vee\overline{x_1}x_2x_3\vee x_1\overline{x_2}x_3
    \end{equation}
 \begin{equation}
 K_f^s(x_1, x_2, x_3) = (x_1\vee x_2\vee\overline{x_3})(\overline{x_1}\vee x_2\vee x_3)
 (\overline{x_1}\vee\overline{x_2}\vee x_3)(\overline{x_1}\vee\overline{x_2}\vee\overline{x_3})
 \end{equation}
    #+end_export
** Задача 2
   #+begin_export latex
   \begin{equation}
 f = (00101111). \text{ Найти простые импликанты.}
   \end{equation}
   #+end_export
*** Решение
    #+begin_export latex
    \begin{equation}
 A = \{x_1, \overline{x_3}, x_1x_2, x_2\overline{x_3}\}\text{ - импликанты $f$.}
    \end{equation}
 $x_1x_2$ - не простая импликанта.
    #+end_export
** Задача 3
   #+begin_export latex
 Найти простые импликанты функции
   \begin{equation}
 f = (01111110).
   \end{equation}
   #+end_export
*** Решение
    #+begin_export latex
    \begin{equation}
 A = \{x_1\overline{x_2}, x_2x_3, x_1x_2x_3\}\text{ - импликанты}
    \end{equation}
 $x_1\overline{x_2}$ - простая импликанта, $x_2x_3$ и $x_1x_2x_3$ - не импликанты.
    #+end_export
** Задача 4
 Построить сокращённую ДНФ функции
   #+begin_export latex
 \begin{equation}
 \tilde{\alpha_f} = (1111 1000 0100 1100)
 \end{equation}
   #+end_export
*** Решение
 Код максимальной грани: $(0022)$, соответствующая простая импликанта $\overline{x_1}\overline{x^2}$.
 Далее идёт ребро $(0200)$, соответствующее импликанте $\overline{x_1}\overline{x_2}\overline{x_3}$.
 Далее идёт ребро $(2100)$, соответствующее импликанте $x_2\overline{x_3}\overline{x_4}$.
 Следующее ребро $(1102) \rightarrow x_1x_2\overline{x_3}$,
 $(1201) \rightarrow x_1\overline{x_3}x_4$, $(2001) \rightarrow \overline{x_2}\overline{x_3}x_4$.
** Задача 2.6
 Найти сокращённую ДНФ методом карты:
 #+begin_export latex
 \begin{equation}
 \tilde{\alpha_f} = (0101 0111)
 \end{equation}
 #+end_export
*** Решение
 |-----------+---+---|
 | x_1x_2x_3 | 0 | 1 |
 |-----------+---+---|
 |        00 | 0 | 1 |
 |        01 | 0 | 1 |
 |        11 | 1 | 1 |
 |        10 | 0 | 1 |
 |-----------+---+---|
 Откуда $D_f = x_3\vee x_1x_2$.
** Задача 2.6(5)
   #+begin_export latex
   \begin{equation}
 \tilde{\alpha_f} = (0001 1011 1101 1111)
   \end{equation}
   #+end_export
*** Решение
 |-------+-------+-------+-------+-----|
 | $x_1$ | $x_2$ | $x_3$ | $x_4$ | $f$ |
 |-------+-------+-------+-------+-----|
 |     0 |     0 |     0 |     0 |   0 |
 |     0 |     0 |     0 |     1 |   0 |
 |     0 |     0 |     1 |     0 |   0 |
 |     0 |     0 |     1 |     1 |   1 |
 |     0 |     1 |     0 |     0 |   1 |
 |     0 |     1 |     0 |     1 |   0 |
 |     0 |     1 |     1 |     0 |   1 |
 |     0 |     1 |     1 |     1 |   1 |
 |     1 |     0 |     0 |     0 |   1 |
 |     1 |     0 |     0 |     1 |   1 |
 |     1 |     0 |     1 |     0 |   0 |
 |     1 |     0 |     1 |     1 |   1 |
 |     1 |     1 |     0 |     0 |   1 |
 |     1 |     1 |     0 |     1 |   1 |
 |     1 |     1 |     1 |     0 |   1 |
 |     1 |     1 |     1 |     1 |   1 |
 |-------+-------+-------+-------+-----|
 Тогда карта Карно будет иметь вид:
 |----------------+----+----+----+----+-----------------------------|
 | $x_1x_2x_3x_4$ | 00 | 01 | 11 | 10 |                             |
 |----------------+----+----+----+----+-----------------------------|
 |             00 |  0 |  0 |  1 |  0 | $x_2x_3, x_2\overline{x_4}$ |
 |             01 |  1 |  0 |  1 |  1 | $x_1x_2, x_1\overline{x_3}$ |
 |             11 |  1 |  1 |  1 |  1 | $x_1x_4$                    |
 |             10 |  1 |  1 |  1 |  0 | $x_3x_4$                    |
 |----------------+----+----+----+----+-----------------------------|
 Тогда сокращённая ДНФ имеет вид:
 #+begin_export latex
 \begin{equation}
 D_f = x_2\overline{x_4}\vee x_2x_3\vee x_1x_2\vee x_1x_4\vee x_3x_4\vee x_1\overline{x_3}
 \end{equation}
 #+end_export
** Задача 2.3(1)
 Получить сокращённую ДНФ по КНФ:
 #+begin_export latex
 \begin{equation}
 (x_1\vee x_2\vee\overline{x_3})(\overline{x_1}\vee x_2\vee x_3)(\overline{x_2}\vee\overline{x_3})
 \end{equation}
 #+end_export
*** Решение
    #+begin_export latex
 \begin{multline}
    (x_1\vee x_2\vee\overline{x_3})(\overline{x_1}\vee x_2\vee x_3)(\overline{x_2}\vee\overline{x_3})
 = (x_1x_2\vee x_1x_3 \vee x_2\overline{x_1}\vee x_2\vee x_2x_3\vee\overline{x_1}\overline{x_3}
 \vee x_2\overline{x_3})(\overline{x_2}\vee\overline{x_3}) = \\
 = (x_2\vee x_1x_3\vee\overline{x_1}\overline{x_3})(\overline{x_2}\vee\overline{x_3})
 = x_2\overline{x_3}\vee x_1\overline{x_2}x_3\vee\overline{x_1}\overline{x_2}\overline{x_3}
 \vee\overline{x_1}\overline{x_3} = x_2\overline{x_3}\vee\overline{x_1}\overline{x_3}\vee x_1\overline{x_2}x_3
 \end{multline}
    #+end_export
** Задача 2.2(1)
 Построить сокращённую ДНФ по данной ДНФ методом Блейка:
 #+begin_export latex
 \begin{equation}
 \overline{x_1}\overline{x_2}\vee x_1\overline{x_2}x_4\vee x_2\overline{x_3}x_4\vee\overline{x_2}x_4|
 \vee\overline{x_1}\overline{x_3}x_4\vee x_1\overline{x_3}x_4|\vee\overline{x_2}\overline{x_3}x_4
 \vee\overline{x_3}x_4 = \overline{x_1}\overline{x_2}\vee\overline{x_2}x_4\vee\overline{x_3}x_4
 \end{equation}
 #+end_export
** Задача 2.2(2)
   #+begin_export latex
   \begin{equation}
 x_1\overline{x_2}x_3\vee\overline{x_1}x_2\overline{x_4}\vee\overline{x_2}\overline{x_3}x_4|
 \vee x_1\overline{x_2}x_4
   \end{equation}
   #+end_export
** Задача 2.9(1)
   #+begin_export latex
   \begin{equation}
 f(\tilde{x_n}) = x_1\oplus\ldots\oplus x_n
   \end{equation}
 Длина сокращённой ДНФ - ?
   #+end_export
*** Решение
    #+begin_export latex
    Максимальные грани - точки $\Rightarrow$ длина сокращённой ДНФ, она же длина СДНФ равна
 $2^n - 1$.
    #+end_export
** Задача 2.9(2)
 Найти длину сокращённой ДНФ функции:
   #+begin_export latex
   \begin{equation}
 f(\tilde{x_n}) = (x_1\vee x_2\vee x_3)(\overline{x_1}\vee\overline{x_2}\overline{x_3})\oplus
 x_4\oplus\ldots\oplus x_n
   \end{equation}
   #+end_export
*** Решение
    #+begin_export latex
 \begin{equation}
 f(\tilde{\alpha}) = 1 \Leftrightarrow \begin{cases}
 g(\tilde{\alpha}) = 1, \\
 h(\tilde{\alpha}) = 0, \\
 g(\tilde{\alpha}) = 0, \\
 h(\tilde{\alpha}) = 1.
    \end{cases}
 \end{equation}
 Первому случаю соответствует $2^{n - 4}\cdot6$ максимальных грани, второму - $2\cdot2^{n - 4}$,
 итого длина ДНФ составляет $2^{n - 1}$.
    #+end_export

 http://mk.cs.msu.ru, лекционные курсы, ОКи, домашние задания там.
* Домашняя работа 1
** Задача 2.3(4)
Представить в виде СДНФ функцию:
#+begin_export latex
\zall
\begin{equation}
f(\tilde{x}^3) = (01010001)
\end{equation}
#+end_export
*** Решение
    #+begin_export latex
Функция принимает единичные значения на наборах $001, 011$ и $111$, откуда СДНФ имеет вид:
\begin{equation}
f(\tilde{x}^3) = \overline{x_1}\overline{x_2}x_3\vee\overline{x_1}x_2x_3\vee x_1x_2x_3
\end{equation}
    #+end_export
** Задача 2.1(3)
Из множества $A$ ЭК выделить простые импликанты функции $f$:
#+begin_export latex
\begin{equation}
A = \{x_1, \overline{x_4}, x_2\overline{x_3}, \overline{x_1}\overline{x_2}\overline{x_4}\},
f(\tilde{x}^4) = (1010 1110 1101 1110)
\end{equation}
#+end_export
*** Решение
    #+begin_export latex
ЭК $x_1$ не является импликантой функции $f$, так как $f(1111) = 0$.

ЭК $\overline{x_4}$ является простой импликантой функции $f$.

ЭК $x_2\overline{x_3}$ является импликантой функции $f$. ЭК $x_2$ не является импликантой
функции $f$, так как $f(1111) = 0$. ЭК $\overline{x_3}$ также не является импликантой $f$,
так как $f(0001) = 0$, значит $x_2\overline{x_3}$ -- простая импликанта функции $f$.

ЭК $\overline{x_1}\overline{x_2}\overline{x_4}$ является импликантой функции $f$, но она не
является простой, так как содержит множитель $\overline{x_4}$, который, как было указано ранее,
является импликантой $f$.
    #+end_export
** Задача 2.5(2, 6)
Изобразив множество $N_f$ функции $f(\tilde{x}^n)$ в $B^n$, найти коды максимальных интервалов
и построить сокращённую ДНФ:
   #+begin_export latex
\begin{equation}
\tilde{\alpha}_f = (0101 0011)
\end{equation}
\begin{equation}
\tilde{\alpha}_f = (0001 0111 1110 1111)
\end{equation}
   #+end_export
*** Решение
Для первой функции находим две максимальные грани с кодами $(112)$ и $(021)$, попытки расширить
которые приводят к выходу из $N_f$. Отсюда получаем сокращённую ДНФ:
#+begin_export latex
\begin{equation}
f(\tilde{x}^3) = \overline{x_1}x_3\vee x_1x_2
\end{equation}
#+end_export
Для второй функции максимальные грани имеют коды $(2112)$, $(1202)$, $(0121)$ и $(0211)$.
Попытки расширить эти грани приводят к выходу из $N_f$. Отсюда получаем сокращённую ДНФ:
#+begin_export latex
\begin{equation}
f(\tilde{x}^4) = x_2x_3\vee x_1\overline{x_3}\vee\overline{x_1}x_2x_4\vee\overline{x_1}x_3x_4
\end{equation}
#+end_export
** Задача 2.6(2, 6)
Найти сокращённую ДНФ функции с помощью минимизирующей карты:
#+begin_export latex
\begin{equation}
\tilde{\alpha_f} = (1101 1011)
\end{equation}
\begin{equation}
\tilde{\alpha_f} = (0011 1101 1111 1101)
\end{equation}
#+end_export
Карта Карно для первой функции:
|------------------+----+----+----+----|
| $x_1$ \ $x_2x_3$ | 00 | 01 | 11 | 10 |
|------------------+----+----+----+----|
|                0 |  1 |  1 |  1 |  0 |
|                1 |  1 |  0 |  1 |  1 |
|------------------+----+----+----+----|
В данном случае максимальными по включению будут прямоугольники $(00-)$, $(-00)$, $(0-1)$,
$(-11)$, $(11-)$, $(1-0)$, откуда сокращённая ДНФ имеет вид:
#+begin_export latex
\begin{equation}
f(\tilde{x}^3) = \overline{x_1}\overline{x_2}\vee\overline{x_2}\overline{x_3}\vee\overline{x_1}x_3
\vee x_2x_3\vee x_1x_2\vee x_1\overline{x_3}
\end{equation}
#+end_export
Карта Карно для второй функции:
|---------------------+----+----+----+----|
| $x_1x_2$ \ $x_3x_4$ | 00 | 01 | 11 | 10 |
|---------------------+----+----+----+----|
|                  00 |  0 |  0 |  1 |  1 |
|                  01 |  1 |  1 |  1 |  0 |
|                  11 |  1 |  1 |  1 |  0 |
|                  10 |  1 |  1 |  1 |  1 |
|---------------------+----+----+----+----|
Максимальными по включению здесь будут прямоугольники $(10--), (-10-), (--11), (-010)$,
которые дают сокращённую ДНФ:
#+begin_export latex
\begin{equation}
f(\tilde{x}^4) = x_1\overline{x_2}\vee x_2\overline{x_3}\vee x_3x_4\vee\overline{x_2}x_3\overline{x_4}
\end{equation}
#+end_export
** Задача 2.2(3, 4)
По заданной ДНФ методом Блейка получить сокращённую ДНФ:
#+begin_export latex
\begin{equation}
D = x_1\vee\overline{x_1}x_2\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_1}x_2x_3x_4
\end{equation}
\begin{equation}
D = x_1\overline{x_2}x_4\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_3}\overline{x_4}
\end{equation}
#+end_export
*** Решение
#+begin_export latex
\begin{multline}
x_1\vee\overline{x_1}x_2\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_1}x_2x_3x_4 = \\
= x_1\vee\overline{x_1}x_2\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_1}x_2x_3x_4
\vee x_2\vee\overline{x_2}x_3\vee x_2x_3x_4\vee\overline{x_1}x_3\vee\overline{x_1}x_3x_4 = \\
= x_1\vee x_2\vee\overline{x_1}x_3\vee\overline{x_2}x_3\vee
= x_1\vee x_2\vee\overline{x_1}x_3\vee\overline{x_2}x_3\vee x_3
= x_1\vee x_2\vee x_3
\end{multline}
\begin{multline}
x_1\overline{x_2}x_4\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_3}\overline{x_4}
= x_1\overline{x_2}x_4\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_3}\overline{x_4}\vee
\overline{x_2}x_3x_4\vee\overline{x_1}\overline{x_2}\overline{x_4}\vee x_1\overline{x_2}\overline{x_3} = \\
= x_1\overline{x_2}x_4\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_3}\overline{x_4}\vee
\overline{x_2}x_3x_4\vee\overline{x_1}\overline{x_2}\overline{x_4}\vee x_1\overline{x_2}\overline{x_3}\vee
\overline{x_2}\overline{x_3}\overline{x_4}\vee x_1\overline{x_2}x_4\vee\overline{x_1}\overline{x_2}x_3 = \\
= x_1\overline{x_2}x_4\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_3}\overline{x_4}
\vee\overline{x_2}x_3x_4\vee\overline{x_1}\overline{x_2}\overline{x_4}\vee x_1\overline{x_2}\overline{x_3}
\end{multline}
#+end_export
** Задача 2.3(3, 4)
Построить сокращённую ДНФ по заданной КНФ:
#+begin_export latex
\begin{equation}
(x_1\vee\overline{x_2}\vee\overline{x_3})(\overline{x_1}\vee x_2)(x_1\vee x_2\vee x_3)
\end{equation}
\begin{equation}
(x_1\vee x_2\vee x_3)(\overline{x_1}\vee\overline{x_2}\vee\overline{x_3})
\end{equation}
#+end_export
*** Решение
    #+begin_export latex
\begin{multline}
(x_1\vee\overline{x_2}\vee\overline{x_3})(\overline{x_1}\vee x_2)(x_1\vee x_2\vee x_3) =
(x_1x_2\vee\overline{x_1}\overline{x_2}\vee\overline{x_1}\overline{x_3}\vee x_2\overline{x_3})
(x_1\vee x_2\vee x_3) = \\
= x_1x_2\vee x_1x_2x_3\vee\overline{x_1}\overline{x_2}x_3\vee\overline{x_1}x_2\overline{x_3}\vee
x_1x_2\overline{x_3}\vee x_2\overline{x_3} = x_1x_2\vee x_2\overline{x_3}\vee\overline{x_1}\overline{x_2}x_3
\end{multline}
\begin{equation}
(x_1\vee x_2\vee x_3)(\overline{x_1}\vee\overline{x_2}\vee\overline{x_3})
= x_1\overline{x_2}\vee x_1\overline{x_3}\vee\overline{x_1}x_2\vee x_2\overline{x_3}\vee
\overline{x_1}x_3\vee\overline{x_2}x_3
\end{equation}
    #+end_export
** Задача 2.9(6)
Найти длину сокращённой ДНФ функции $f$:
#+begin_export latex
\begin{equation}
f(\tilde{x}^n) = (x_1\vee\ldots\vee x_n)(x_1\vee\ldots\vee x_k\vee\overline{x}_{k + 1}\vee\ldots\vee\overline{x}_n)
\end{equation}
#+end_export
*** Решение
    #+begin_export latex
\begin{multline}
(x_1\vee\ldots\vee x_n)(x_1\vee\ldots\vee x_k\vee\overline{x}_{k + 1}\vee\ldots\overline{x}_n) =
(\vee_{i = 1}^kx_k)\vee(\vee_{i, j = 1}^{k, n}x_ix_j)\vee(\vee_{i = k + 1, j = 1}^{n}\overline{x}_ix_j) = \\
= (\vee_{i = 1}^kx_k)\vee(\vee_{i, j = k + 1}^n\overline{x_i}x_j)\vee(\vee_{i, j = k + 1}^nx_ix_j)
\end{multline}
Всего получаем
\begin{equation}
k + 2\frac{(n - k)(n - k + 1)}2 = k + (n - k)(n - k + 1) = n + (n - k)^2 = n^2 - 2nk + n + k^2
\end{equation}
слагаемых.
    #+end_export
