#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}\setcounter{stnmt}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

#+LATEX_HEADER:\newcounter{stnmt}\setcounter{stnmt}{0}
#+LATEX_HEADER:\def\st{\par\smallskip\refstepcounter{stnmt}\textbf{\arabic{stnmt}}}
#+LATEX_HEADER:\newtheorem*{Statement}{Утверждение \st}

* Основы кибернетики
3 контрольные работы.

Схема системы управления:
Управляющая система <--> Объект управления

Построение системы управления:
1. Выбор оптимальной функции управления из данного класса
2. Построение оптимальной УС заданного типа.
3. Оценка качества построенной СУ, а затем, возможно, сделать всё сначала.

* Минимизация ДНФ и связанные с ней задачи
Пусть $\delta$ - множество, $P = \{\delta_1, \ldots, \delta_p\}$ - система его подмножеств. Если $U_{j = 1}^p\delta_i = \delta$, то $P$ - *покрытие* $\delta$,
$\delta_i$ - *компоненты* покрытия $P$, $p$ - *ранг* покрытия. Подсистема $P$, покрывающая $\delta$,
называется *подпокрытием*. Покрытие, в котором каждая компонента не содержится ни в какой
другой(в объединении остальных) называется *неприводимым* (*тупиковым*). Покрытие с попарно
непересекающимися компонентами называется *разбиением*.
$$E_2 = B = \{0, 1\}$$
*Булева функция* - отображение $B^n \rightarrow B$.
Табличное задание булевой функции. Вектор значений булевой функции:
$$\tilde{\alpha}_f = (\beta_0, \ldots, \beta_{2^n - 1})$$
*Булева переменная* $x_i$ БФ $f(\tilde{x}^n)$ называется *существенной*, если значения на
некоторых смеженых по ней наборах различаются. В противном случае переменная называется
*фиктивной* или *несущественной*. Две функции равны, если они совпадают с точностью до
добавления и удаления фиктивных переменных.
Формульный метод задания БФ.

Пусть Б - система БФ($\text{Б} \subset P_2$). Предполагается, что Б содержит $x_1$.

Выражение $x_i$ - формула над Б глубины 0, реализующая БФ $x_i$. Пусть $\varphi \in \text{Б}$,
формула $A_j$ над Б имеет глубину $d_j$ и реализует БФ $f_j$, $j = \overline{1, t}$. Тогда
выражение $A$ вида $\varphi(A_1, \ldots, A_t)$ есть формула над Б глубины $d = \max_{j = \overline{1, t}}d_j + 1$,
реализующая БФ $f = \varphi(f_1, \ldots, f_t)$. Подформулы $A_1, \ldots, A_t$ называются
*главными подформулами* формулы $A$. Формулы, реализующие равные функции, называются
*эквивалентными*.

Запись вида $A' = A''$, где $A'$ и $A''$ - эквивалентные функции, называется *тождеством*.
Основные тождества:
1. *Коммутативность* конъюкции и дизъюнкции.
2. *Ассоциативность*.
3. *Дистрибутивность* конъюкции и дизъюнкции относительно друг друга.
4. *Закон де Моргана* и правило снятия двойного отрицания.
5. *Правило поглощения*.
6. $x = x\cdot x = x \vee x = x\cdot1 = x\vee 0$
7. $0 = x\cdot\overline{x} = x\cdot0, 1 = x\vee\overline{x} = x\vee1$
В качестве Б используем систему $\text{Б} = \{xy, x\vee y, \overline{x}\}$.

*Элементарной конъюкцией* назовём конъюкцию букв попарно различных переменных или их отрицаний.
*Элементарной дизъюнкией*, соответственно, дизъюнкцию букв переменных и их отрицанией.
ДНФ - дизъюнкция попарно неэквивалентных ЭК, КНФ - конъюкция попарно неэквивалентных ЭД.
Для любой неконстантной функции существуют *совершенные* ДНФ и КНФ - ДНФ и КНФ, в которой все
ЭК(или ЭД) имеют равные ранги, совпадающие с арностью функции.
*Ранг* формулы - число вхождений в неё булевых переменных. *Сложность* формулы - число
вхождений функциональных символов.

Пусть $F = K_1 \vee K_2 \vee \ldots \vee K_s$ - ДНФ. $K_1, \ldots, K_s$ - *слагаемые* ДНФ $F$,
$\lambda(F) = s$ - длина ДНФ $F$. Аналогично вводятся *множители* КНФ.

Рассмотрим $B^n$ - булев куб размерности $n$. Вес $\tilde{\alpha} = (\alpha_1, \ldots, \alpha_n) \in B^n$:
#+begin_export latex
\begin{equation*}
||\tilde{\alpha}|| = \sum_{i = 1}^n\alpha_i
\end{equation*}
\begin{equation*}
B_k^n = \{\tilde{\alpha} | \tilde{\alpha} \in B^n, ||\tilde{\alpha}|| = k\}(k = \overline{0, n})
\end{equation*}
#+end_export
Множество $B_k^n$ называется *k-м слоем* булева куба.

*Хэммингово расстояние* между векторами есть вес их суммы по модулю 2:
#+begin_export latex
\begin{equation*}
\rho(\tilde{\alpha}, \tilde{\beta}) = \sum_{i = 1}^n|\alpha_i - \beta_i|
\end{equation*}
#+end_export
*Сфера(шар)* радиуса $r$ с центром в $\tilde{\alpha}$:
#+begin_export latex
\begin{equation*}
S_{n, r}^{\tilde{\alpha}} = \{\tilde{\beta} | \tilde{\beta}, \rho(\tilde{\alpha}, \tilde{\beta} = r)\}
\end{equation*}
\begin{equation*}
(\tilde{S_{n, r}^{\tilde{\alpha}}} = \{\tilde{\beta} | \tilde{\beta}, \rho(\tilde{\alpha}, \tilde{\beta} \leq r)\})
\end{equation*}
#+end_export
Пусть $\tilde{\gamma} = (\gamma_1, \ldots, \gamma_n) \in \{0, 1, 2\}^n$. *Гранью* куба $B^n$,
соответствующей набору $\tilde{\gamma}$ назовём множество:
#+begin_export latex
\begin{equation*}
\Gamma_{\gamma} = \{(\alpha_1, \ldots, \alpha_n) | \alpha_i \in \{0, 1\},
\text{ при этом если }\gamma_i \neq 2, \text{ то } \alpha_i = \gamma_i(i = \overline{1, n})\}
\end{equation*}
#+end_export
Набор $\tilde{\gamma}$ называется *кодом* этой грани.

Число '2' в $\tilde{\gamma}$ -- *размерность* $\Gamma_{\gamma}$($\dim \Gamma_{\gamma}$),
$\operatorname{rank}\Gamma_{\gamma} = n - \dim\Gamma_{\gamma}$ - *ранг* $\Gamma_{\gamma}$.

*Характеристическим* множеством $f(\tilde{x}^n)$ называется множество:
#+begin_export latex
\begin{equation*}
N_f = \{\tilde{\alpha} | \tilde{\alpha} \in B^n\text{ и }f(\tilde{\alpha}) = 1\}
\end{equation*}
#+end_export
В этой части курса не рассматриваются БФ, тождественно равные 0 и 1. Рассмотрим ЭК и ЭД:
#+begin_export latex
\begin{equation*}
K = x_{i_1}^{\sigma_{i_1}}x_{i_2}^{\sigma_{i_2}}\ldots x_{i_r}^{\sigma_{i_r}}
\end{equation*}
\begin{equation*}
J = x_{i_1}^{\overline{\sigma_{i_1}}}\vee x_{i_2}^{\overline{\sigma_{i_2}}}\ldots\vee x_{i_r}^{\overline{\sigma_{i_r}}}
\end{equation*}
#+end_export
Геометрическая интерпретация: $N_k = \Gamma_{\tilde{\gamma}} = N_{\overline{J}}$,
где $\tilde{\gamma} = (\gamma_1, \ldots, \gamma_n)$ причём для $\forall \nu \in \{1, \ldots, r\}$
$\gamma_{ij} = \sigma_{ij}$, а остальные $\gamma_j$ равны '2'.

Пусть $f = K_1 \vee \ldots \vee K_s = J_1J_2\ldots J_t$. Геометрическая интерпретация ДНФ(КНФ):
#+begin_export latex
\begin{equation*}
N_f = N_{K_1}\cup\ldots\cup N_{K_s}
\end{equation*}
\begin{equation*}
(N_{\overline{f}} = N_{\overline{J_1}}\cap\ldots\cap N_{\overline{J_t}})
\end{equation*}
#+end_export
Иными словами, характеристическое множество покрывется гранями, соответствующими слагаемым ДНФ
(соответственно, множителями КНФ). В случае совершенной ДНФ покрытие осуществляется
нульмерными гранями, т. е. точками.
#+begin_export latex
\begin{Statement}
Совершенная ДНФ ФАЛ $f$, $f \not\equiv 0, f \in P_2(n)$ является единственной ДНФ от $X(n)$,
реализующей эту ФАЛ, тогда и только тогда, когда в $N_f$ нет соседних наборов.
\end{Statement}
\begin{proof}
Совершенная ДНФ существует всегда $\Rightarrow$ нет других $\Rightarrow$ все грани в $N_f$
имеют размерность 0, т. е. в $N_f$ нет соседних наборов.
\end{proof}
\textbf{Счётчик чётности} порядка n:
\begin{equation*}
l = l_n(x_1, \ldots, x_n) = x_1 \oplus x_2 \oplus \ldots \oplus x_n
\end{equation*}
\begin{Consequence}
Совершенная ДНФ ФАЛ $l, \overline{l}$, является единственной ДНФ этой ФАЛ от БП $X(n)$.
\end{Consequence}
#+end_export
** Сокращённая ДНФ и способы её построения
Булева функция $f_1$ *имплицирует* булеву функцию $f_2 \Leftrightarrow N_{f_1} \subset N_{f_2}$.
Или: $f_1 \rightarrow f_2 \equiv 1 \Leftrightarrow f_1 \vee f_2 = f_2 \Leftrightarrow f_1f_2 = f_1$.

ЭК K называется *импликантой* булевой функции $f \Leftrightarrow K$ имплицирует $f$. ДНФ $D$
функции $f$ есть дизъюнкция некоторых импликант функции $f$. ЭК $K_1$ поглощается ЭК
$K_2 \Leftrightarrow K_1$ имплицирует $K_2$.

ДНФ *без поглощений* -- такая ДНФ, в которой никакое слагаемое не поглощается другим. ЭК $K$
называется *простой импликантой* $f$, если:
1. $K$ - импликанта $f$.
2. $K$ не поглощается никакой другой импликантой $f$.

*Сокращённая ДНФ* БФ $f$ - ДНФ, представляющая собой дизъюнкцию всех простых импликант БФ $f$.
Грань, соответствующая простой импликанте, называется *максимальной гранью*.
#+begin_export latex
\begin{Statement}
Пусть $A', A''$ - сокращённые ДНФ ФАЛ $f'$ и $f''$ соответственно, а ДНФ $A$ без поглощений
ЭК получается из формулы $A'A''$ в результате раскрытия скобок и приведения подобных слагаемых.
Тогда $A$ - сокращённая ДНФ ФАЛ $f = f'f''$.
\end{Statement}
\begin{proof}
Достаточно доказать, что все простые импликанты $f$ возникнут в результате раскрытия скобок.
Пусть в $A$ имелось $K'$, в $A''$ -- $K''$ -- слагаемые, имплицируемые $K$. Тогда в $A$ есть
либо $\tilde{K} = K'K''$, либо $\overline{K}$, поглощающее $\tilde{K}$. Тогда $K$ имплицирует
$\tilde{K}$ и $\overline{K}$, но $K$ простая импликанта $f \Rightarrow K = \tilde{K} = \overline{K}$,
что и требовалось показать.
\end{proof}
\begin{Consequence}
Если ДНФ $A$ без поглощений ЭК получается из КНФ $B$ ФАЛ $f$ в результате раскрытия скобок и
приведения подобных слагаемых, то $A$ - сокращённая ДНФ ФАЛ $f$.
\end{Consequence}
\textbf{Тождество обобщённого склеивания}:\\
\begin{equation*}
xK'\vee\overline{x}K'' = xK'\vee\overline{x}K''\vee K'K''
\end{equation*}
#+end_export
Пусть ДНФ $D'$ получена из ДНФ $D$ применением тождества обобщённого склеивания. Если в $D'$
есть слагаемые, не поглощаемые никаким слагаемым $D$, то $D'$ называется *строгим расширением*
$D$.
#+begin_export latex
\begin{Statement}
ДНФ без поглощений ЭК является сокращённой ДНФ тогда и только тогда, когда она не имеет
строгих расширений.
\end{Statement}
\begin{proof}
Пусть $\smallsmile{K}$ - простая импликанта $f$, не входящая в ДНФ $A$ без поглощений, не
имеющая строгих расширений от переменных $X(n)$. Пусть $Z$ -- множество всех импликант $f$,
не поглощаемых слагаемыми $A$: $\smallsmile{K} \in Z$.\\
В $Z$ нет ЭК ранга $n$. Пусть $\dot{K}$ - ЭК максимального ранга из $Z$ и пусть $x_i$ не
встречается в $K$. Тогда $x_iK$ поглощается слагаемым $x_iK'$ в $A$, $\overline{x}_iK$
поглощается \ldots
\end{proof}
\begin{Consequence}[Алгоритм Блейка]
Из любой ДНФ $A$ ФАЛ $f$ можно получить сокращённую ДНФ этой ФАЛ в результате построения
последовательных строгих расширений и приведения подобных до получения ДНФ без поглощений ЭК,
не имеющей строгих расширений.
\end{Consequence}
#+end_export
** Тупиковые ДНФ, ядро и ДНФ пересечение тупиковых. ДНФ Квайна, критерий вхождения простых импликант в ДНФ сумма тупиковых, его локальность
*Минимальной(кратчайшей) ДНФ* БФ $f$ называется ДНФ наименьшего ранга(наименьшей длины),
реализующая $f$.

ДНФ $A$, реализующая БФ $f$, называется *тупиковой*, если всякая ДНФ $A'$, полученная из $A$
удалением слагаемых и/или множителей, реализует БФ, отличную от $f$. Тупиковая ДНФ состоит из
простых импликант и является ДНФ без поглощений, а с геометрической точки зрения она отвечает
тупиковому покрытию множества $N_f$.

Минимальная ДНФ всегда является тупиковой. Среди тупиковых ДНФ всегда содержится кратчайшая.

Набор $\alpha$ называется *ядровой точкой* БФ $f$, если $\alpha$ покрывается ровно одной гранью.
Максимальная грань, содержащая ядровую точку, называется *ядровой*. *Ядро* БФ $f$ - совокупность
всех ядровых граней $f$. *Ядровой* называется БФ, у которой все максимальные грани -- ядровые.

ДНФ *"пересечение тупиковых"* БФ $f$ представляет собой дизъюнкцию тех и только тех импликант,
каждая из которых является слагаемым каждой тупиковой ДНФ БФ $f$. Эта ДНФ может быть пустой и
не обязана реализовывать $f$.
#+begin_export latex
\begin{Statement}
ДНФ "пересечение тупиковых" ФАЛ $f$ состоит из тех и только тех простых импликант $f$, которые соответствуют
ядровым граням этой ФАЛ.
\end{Statement}
\begin{proof}
Пусть $K$ - ядровая импликанта БФ $f$(т. е. простая импликанта, соответствующая ядровой грани
$f$), а $D$ - тупиковая ДНФ БФ $f$, в которую $K$ не входит как слагаемое. $K$ -- ядровая,
поэтому в $N_K$ есть ядровая точка $\alpha$. Но тогда получается, что $f(\alpha) = 0$, т. е.
$\alpha \notin N_f$. Противоречие.

Пусть теперь $K$ -- простая импликанта, не являющаяся ядровой для БФ $f$, но при этом входит в
каждую тупиковую ДНФ БФ $f$. Пусть $N_k = \{\alpha_1, \ldots, \alpha_s\}$, тогда
$\forall i = \overline{1, s}$ точка $\alpha_i$ покрывается гранью $N_{K_i} \neq N_K$. Так как
$\alpha_i$ - не ядровая точка, то объединение всех максимальных граней, кроме $N_K$, равно $N_f$.
Тогда выбирая из множества всех максимальных граней, кроме $N_K$, тупиковое покрытие, можно
построить соответствующую тупиковую ДНФ, не содержащую $N_K$.
\end{proof}
\begin{Consequence}
Сокращённая ДНФ ФАЛ $f$ является её единственной тупиковой ДНФ тогда и только тогда, когда $f$
-- ядровая ФАЛ, т. е. все её максимальные грани входят в ядро.
\end{Consequence}
#+end_export
*ДНФ Квайна* БФ $f$ -- ДНФ, получающаяся из сокращённой ДНФ $f$ удалением тех и только тех
простых импликант, максимальные грани которых не входят в ядро, но покрываются им.

ДНФ *"сумма тупиковых"* БФ $f$ представляет собой дизъюнкцию тех и только тех простых импликант,
каждая из которых входит хотя бы в одну тупиковую ДНФ.

Пусть $\alpha \in N_f$. *Пучок*, проходящий через $\alpha$ -- это множество $\Pi_{\alpha}$
всех максимальных граней $f$, содержащих $\alpha$. Набор $\alpha$ из $N_f$ называется
*регулярной точкой* БФ $f$, если $\exists \beta \in N_f: \Pi_{\beta} \subset \Pi_{\alpha}$.
Максимальная грань $N_K$ БФ $f$ называется *регулярной*, если каждый набор $\alpha \in N_K$ --
регулярная точка $f$. Для каждой регулярной точки $\alpha$ БФ $f$ существует нерегулярная
точка $\gamma: \Pi_{\gamma} \subset \Pi_{\alpha}$. В частности, пусть
$\gamma: \Pi_{\gamma} \subset \Pi_{\alpha}$ и при этом
#+begin_export latex
\begin{equation*}
|\Pi_{\gamma}| = \min_{\beta \in N_f, \Pi_{\beta} \subset \Pi_{\alpha}}|\Pi_{\beta}|
\end{equation*}
#+end_export
#+begin_export latex
\begin{Statement}
Простая импликанта $K$ ФАЛ $f$ входит в ДНФ "сумма тупиковых" тогда и только тогда, когда
грань $N_K$ не является регулярной гранью этой ФАЛ.
\end{Statement}
\begin{proof}
Пусть $N_K$ является регулярной гранью $f$. Пусть $N_K = \{\alpha_1, \ldots, \alpha_s\}$, для
каждой (регулярной) точки $\alpha_i$ имеется нерегулярная точка $\beta_i$, такая что всякая
максимальная грань, проходящая через $\beta_i$, проходит и через $\alpha_i$. Тогда всякая
тупиковая ДНФ $D$ должна покрывать точки $\beta_1, \ldots, \beta_s$ соответствующими слагаемым
максимальными гранями $\Rightarrow$ эти грани(среди которых нет $N_K$) покроют $N_K$, т. е.
$N_K$ не входит в ДНФ "сумма тупиковых" БФ $f$.

Пусть теперь $N_K = \{\alpha_1, \ldots, \alpha_s\}$ - максимальная грань БФ $f$, не являющаяся
регулярной. Тогда $\exists i = \overline{1, s} \exists \alpha_i$, не являющаяся регулярной
точкой. $\forall \beta \in N_f \backslash N_K$: $\Pi_{\beta}$ не содержится строго в
$\Pi_{\alpha_i}$. Кроме того, $\Pi_{\beta} \neq \Pi_{\alpha_i}$, так как
$\beta \notin N_K, N_K \in \Pi_{\alpha_i}$. Тогда для всякой точки $\beta_i \in N_f \backslash N_K$
$\exists$ грань $N_{K_i} \forall \beta_i \exists N_{K_i}$ - максимальная грань, проходящая через
$\beta_i$, но не через $\alpha_i$. Тогда из покрытия $N_f$ максимальными гранями
$N_{K_1}, \ldots, N_{K_q}$ нельзя удалить $N_K$, так как только она содержит $\alpha$,
соответстсвенно, найдётся покрытие $N_f$ максимальными гранями, содержащее $N_K$, т. е. $K$
входит в ДНФ "сумма тупиковых" БФ $f$, ч. т. д.
\end{proof}
#+end_export
*** О локальных алгоритмах
Пусть БФ $f \not\equiv const$ задана с помощью перечня всех максимальных граней, покрывающих
$N_f$. Пусть $N$ -- максимальная грань БФ $f$. Тогда $S_0(f, N) = \{N\}$ -- *окрестность
нулевого порядка* максимальной грани $N$ БФ $f$. Обозначим через $S_r(f, N)$ -- множество тех
и только тех максимальных граней БФ $f$, которые имеют непустое пересечение с $S_{r - 1}(f, N)$.
$S_r(f, N), r \in \mathbb{N}_0$ - *окрестность r-го порядка* максимальной грани $N$ БФ $f$.

Построение ядра БФ $f$ требует изучения окрестностей первого порядка максимальных граней:
распознавание принадлежности $N$ к ядру сводится к выяснению, покрывается ли $N$ остальными
гранями из $S_1(f, N)$.

Чтобы выяснить по максимальной грани $N$ БФ $f$, входит ли соответствующая простая импликанта
в ДНФ Квайна, достаточно изучения $S_2(f, N)$: надо установить, какие максимальные грани из
$S_1(f, N)$ ядровые и покрывают ли ядровые грани из $S_1(f, N)$, отличные от $N$, $N$. Если
заранее проверить, являются ли эти грани ядровыми, можно обойтись $S_1(f, N)$.

По утверждению 5 для установления принадлежности максимальной грани $N$ в перечень граней для
ДНФ "сумма тупиковых", достаточно изучить $S_2(f, N)$, так как достаточно установить, является
ли $N$ нерегулярной.
** Особенности ДНФ линейных и монотонных функций. Функция покрытия, таблица Квайна и построение всех тупиковых ДНФ
БФ $f$ называется *линейной*, если $f$ представима в виде
#+begin_export latex
\begin{equation*}
f = \oplus_{k = 1}^na_kx_k, a_i \in \{0, 1\} \forall i = \overline{1, n}.
\end{equation*}
БФ $f$ \textbf{линейно} зависит от БП $x_i$, если
\begin{equation*}
f = x_i \oplus f(x_1, \ldots, x_{i - 1}, 0, x_{i + 1}, \ldots, x_n).
\end{equation*}
\begin{Statement}
Во всяком слагаемом всякой ДНФ БФ $f$, линейной по $x_i$, есть множитель, содержащий $x_i$, с
отрицанием или без.
\end{Statement}
\begin{proof}
От противного.
\end{proof}
\begin{Consequence}
У линейной БФ в любое слагаемое, любой ДНФ, реализующей $f$, входит каждая буква каждой
существенной БП $x_i$.
\end{Consequence}
Пусть $\alpha = (\alpha_1, \ldots, \alpha_n), \beta = (\beta_1, \ldots, \beta_n) \in B^n$.
$\alpha \preceq \beta$($\alpha$ \textbf{предшествует} $\beta$), если
$\forall i = \overline{1, n}: \alpha_i \leq \beta_i$. БФ $f$ называется \textbf{монотонной}, если
$\forall \alpha, \beta: \alpha \preceq \beta: f(\alpha) \leq f(\beta)$.

Набор $\alpha$ из $B^n$ называется \textbf{нижней единицей} БФ $f$, если $f(\alpha) = 1$ и
$\forall \beta \neq \alpha$ и $\beta \preceq \alpha f(\beta) = 0$.
\begin{Statement}
В простых импликантах монотонных БФ не встречается отрицания переменных.
\end{Statement}
\begin{proof}
Пусть $K$ - импликанта монотонной БФ $f$, содержащая множитель $\overline{x}$. Тогда $K'$,
полученная из $K$ удалением $\overline{x_i}$ -- тоже импликанта $f$. В самом деле, пусть
$\alpha = (\alpha_1, \ldots, \alpha_{i - 1}, 0, \alpha_{i + 1}, \ldots, \alpha_n)$ -- произвольный
набор такой, что $K(\alpha) = 1$. Тогда так как $f$ -- монотонная БФ, то
$f(\alpha_1, \ldots, \alpha_{i - 1}, 1, \alpha_{i + 1}, \ldots, \alpha_n) = 1$, что означает, что
$K'$ -- импликанта БФ $f$, т. е. $K$ не является простой импликантой. Противоречие.
\end{proof}
\begin{Consequence}
В тупиковых и сокращённых ДНФ монотонных БФ нет отрицаний.
\end{Consequence}
Обозначим $N_f^+$ множество всех нижних единиц $f$.

Пусть $\beta = (\beta_1, \ldots, \beta_n) \in B^n, \beta \neq 0$. Сопоставим набору $\beta$
монотонную ЭК $K_\beta^+(x_1, \ldots, x_n)$ следующим образом: $x_i$ входит в
$K_{\beta}^+ \Leftrightarrow \beta_i = 1$.

Пусть $f$ - монотонная БФ. В простых импликантах $f$ нет отрицаний, поэтому всякая простая
импликанта $K$ БФ $f$ имеет вид $K_{\beta}^+$ для некоторого $\beta \in B^n$. Заметим, что
$K_{\beta''}^+$ имплицирует ЭК $K_{\beta'}^+ \Leftrightarrow \beta' \preceq \beta''$.
ЭК $K_{\beta}^+$ имплицирует монотонную БФ $f \Leftrightarrow f(\beta) = 1$. Таким образом,
получаем
\begin{Statement}
Все простые импликанты монотонной БФ $f$ имеют вид $K_{\beta}^+, \beta \in N_f^+$.
При этом все наборы из $N_f^+$ являются ядровыми точками ФАЛ $f$.
\end{Statement}
\begin{Consequence}
Монотонная ФАЛ является ядровой ФАЛ.
\end{Consequence}
#+end_export
*** Построение всех тупиковых покрытий
Пусть имеется множество $N$ и семейство его подмножеств $\mathfrak{M} = \{N_1, \ldots, N_p\}$,
образующих покрытие $N$. Пусть $N = \{\alpha_1, \ldots, \alpha_s\}$. Сопоставим паре
$(N, \mathfrak{M})$ матрицу $M = (m_{ij}) \in B^{p\times s}$:
#+begin_export latex
\begin{equation*}
m_{ij} = \begin{cases}
1, \alpha_j \in N_i, \\
0, \text{ иначе.}
\end{cases}
\end{equation*}
#+end_export
Так как $\mathfrak{M}$ покрывает $N$, в $M$ нет нулевых столбцов.

Будем говорить, что множество строк $I$ матрицы $M$ является *покрытием* этой матрицы $M$,
если в подматрице матрицы $M$, составленной из строк $I$, нет нулевых столбцов. Аналогично,
множество строк $I$ матрицы $M$ *покрывает* подмножество $H$ столбцов матрицы $M$, если в
подматрице матрицы $M$, составленной из строк $I$ и столбцов $H$, нет нулевых столбцов.
Пусть $M \in B^{p\times s}$ -- матрица без нулевых столбцов. $\forall i = \overline{1, p}$
сопоставим $i$-й строке $M$ переменную $y_i$, каждому набору значений $\beta = (\beta_1, \ldots, \beta_p)$,
$\beta \in B^p$ поставим в соответствие множество строк $I<\beta>$: строка $i$ матрицы $M$
входит в $I<\beta>$ тогда и только тогда, когда $\beta_i = 1$.
Пусть БФ $F(y_1, \ldots, y_p)$ определена следующим образом: $\forall \beta \in B^p F(\beta) = 1$
тогда и только тогда, когда $I<\beta>$ -- покрытие матрицы $M$. Функция $F$ называется
*функцией покрытия* матрицы $M$. Заметим, что $F$ является монотонной, так как всем тупиковым
покрытиям $M$ взаимно однозначно соответствуют все нижние единицы $F$.
#+begin_export latex
\begin{Statement}
Функция покрытия $F(y_1, \ldots, y_p)$ матрицы $M \in B^{p\times s}$ без нулевых столбцов задаётся
КНФ вида:
\begin{equation*}
F(y_1, \ldots, y_p) = \wedge_{j = 1}^s\left(\vee_{1 \leq i \leq p, M(i, j) = 1}y_i\right)
\end{equation*}
\end{Statement}
\begin{proof}
Рассмотрим $\forall \beta \in B^p$. $I<\beta>$ -- покрытие матрицы $M \Leftrightarrow I<\beta>$
покрывает каждый $j$-й столбец $M \Leftrightarrow \forall j: \vee_{1 \leq i \leq p, M(i, j) = 1} = 1$
$\Leftrightarrow \wedge_{j = 1}\left(\vee_{1 \leq i \leq p, M(i, j) = 1}\right) = 1 \Leftrightarrow F$
-- функция покрытия.
\end{proof}
\begin{Consequence}
В результате раскрытия скобок и приведения подобных из этой КНФ можно получить сокращённую ДНФ
ФАЛ $F(y)$, простые импликанты которой взаимно однозначно соответствуют тупиковым покрытиям
матрицы $M$.
\end{Consequence}
#+end_export
Пусть $f(\tilde{x}^n)$ - БФ, $\mathfrak{M}$ - множество всех максимальных граней $F$, $N_f$ --
характеристическое множество $f$:
#+begin_export latex
\begin{equation*}
\mathfrak{M} = \{N_{k_1}, \ldots, N_{k_p}\}, N_f = \{\alpha_1, \ldots, \alpha_s\}.
\end{equation*}
#+end_export
*Таблицей Квайна* называется матрица $M = M(f) \in B^{p \times s}: \forall(i, j)$
$\in \{1, \ldots, \beta\}\times\{1, \ldots, s\} M(i, j) = 1 \Leftrightarrow K_i(\alpha_j) = 1$.
Всякая тупиковая ДНФ соответствует покрытию таблицы Квайна БФ $f$ строками(и обратно).
*** Модифицированный алгоритм построения всех тупиковых ДНФ БФ f
Пусть $\hat{N}$ -- множество всех ядровых и регулярных точек $f$.

Будем считать, что максимальные грани $N_{k_{q + 1}}, \ldots, N_{K_t}$ -- ядровые,
$N_{K_{t + 1}}, \ldots, N_{K_p}$ -- регулярные. $\forall i = \overline{1, p}:$
$N_i = N_{K_i} \backslash \hat{N}$.

Задача построения всех тупиковых ДНФ БФ $f$ сводится к задаче построения всех тупиковых
покрытий матрицы, построенной из таблицы Квайна, путём вычёркивания строк, соответствующих
$N_{K_{q + 1}}, \ldots, N_{K_p}$ и столбцов, соответствующих элементам $\hat{N}$. При этом
каждое тупиковое покрытие $\{\hat{N_{i_1}}, \ldots, \hat{N_{i_{\mu}}}\}$ этой матрицы
порождает тупиковую ДНФ БФ $f$, максимальные грани которой есть $N_{K_{i_1}}, \ldots, N_{K_{i_{\mu}}}, N_{K_{q + 1}}, \ldots, N_{K_t}$.
** Градиентный алгоритм и оценка длины градиентного покрытия, лемма о протыкающих наборах. Использование градиентного алгоритма для построения ДНФ
*** Градиентный алгоритм построения покрытия матрицы M
На каждом шаге в покрытие добавляется строка, покрывающая наибольшее число ещё не покрытых
столбцов(если таких строк несколько, выбирается строка с наименьшим номером). Затем из матрицы
$M$ вычёркиваются выбранная строка(номера остальных строк сохраняются) и все покрытые этой
строкой столбцы. Признак конца работы: вычёркивание последнего столбца. Замечание: градиентный
алгоритм не всегда строит тупиковое покрытие. Например:
#+begin_export latex
\zall
\begin{equation*}
M = \begin{pmatrix}
1 & 1 & 1 & 0 & 0 & 0 \\
1 & 0 & 0 & 1 & 0 & 0 \\
0 & 1 & 0 & 0 & 1 & 0 \\
0 & 0 & 1 & 0 & 0 & 1.
\end{pmatrix}
\end{equation*}
\begin{Statement}
Пусть для $\gamma \in \mathbb{R}, 0 < \gamma \leq 1$ в каждом столбце матрицы $M \in B^{p\times s}$
имеется не меньше, чем $\gamma\cdot p$. Тогда покрытие границы $M$, получаемое с помощью
градиентного алгоритма, имеет длину не больше, чем
\begin{equation*}
\left\lceil\frac1{\gamma}\ln^+(\gamma s)\right\rceil + \frac1{\gamma},
\end{equation*}
где
\begin{equation*}
\ln^+x = \begin{cases}
\ln x, x \geq 1, \\
0, 0 < x < 1.
\end{cases}
\end{equation*}
\end{Statement}
\begin{proof}
Пусть градиентный алгоритм построил покрытие матрицы $M \in B^{p\times s}$, имеющее мощность $q$
и состоящее из строк с номерами $i_1, i_2, \ldots i_q$. На каждом шаге $t$($t = \overline{1, q}$)
вычёркивались строка $i_t$ и покрывемые ею столбцы так, что получалась матрица $M_t$ с $p_t = p - t$
строками и $s_t = \delta_t\cdot s$ столбцами($M_q$ -- пустая матрица), $\delta_0 = 1, \delta_q = 0$.
Число единиц в $M_t$ по условию не меньше $\gamma\cdot p\cdot s_t = \gamma\cdot p\cdot s\delta_t$.
По принципу Дирихле в строке, покрывающей наибольшее число столбцов $M_t$, имеется хотя бы
$\gamma \leq \delta_t$ единиц.
\end{proof}
Пусть $N$ -- множество точек, $\mathfrak{M} = \{N_1, \ldots, N_p\}$ -- множество непустых
подмножеств $N$. Множество $\breve{N}$ называется \textbf{протыкающим} для семейства $\mathfrak{M}$,
если $\forall i = \overline{1, p} \exists \alpha \in \breve{N}: \alpha \in N_i$.

Задача о построении протыкающего множества $\breve{N} = \{\alpha_1, \ldots, \alpha_t\}$
эквивалентна задаче о построении покрытия $\{\breve{N}_{\alpha_1}, \ldots, \breve{N}_{\alpha_t}\}$
множества $\mathfrak{M}$ подмножествами вида $\breve{N}_\alpha = \{N_i | \alpha \in N_i\}$.
\begin{Statement}
$\forall n, m \in \mathbb{N}, m \leq n$ в $B^n$ всегда найдётся подмножество мощности не более,
чем $n\cdot 2^m$, протыкающее все грани ранга $m$.
\end{Statement}
\begin{proof}
Всего в кубе $B^n$ имеется $\begin{pmatrix}n\\m\end{pmatrix}\cdot2^m$ граней ранга $m$. Каждая
из них содержит $2^{n - m}$ точек. $|B^n| = 2^n \Rightarrow$ имеется $2^n$ множеств вида
$\breve{N}_{\alpha}(\alpha \in B^n)$, т. е. множеств, состоящих из тех и только тех граней ранга
$m$, содержащих $\alpha$.

Рассмотрим матрицу $M$ из нулей и единиц, каждому столбцу которой соответствует грань ранга $m$,
а каждой строке -- множество вида $\breve{N}_{\alpha}$. $M \in B^{2^n\times\begin{pmatrix}n\\m\end{pmatrix}\cdot2^m}$.
На пересечении строки, соответствующей $\breve{N}_{\alpha}$ и столбца, соответствующего грани
$N_i$ стоит единица, если $\alpha \in N_i$ и ноль в противном случае.
\begin{equation*}
2^{n - m} = \gamma\cdot p = \gamma\cdot2^n \text{ -- число единиц в каждом столбце }
\Rightarrow
\end{equation*}
$\gamma = \frac1{2^m}$. Используя утверждение 1, построим градиентное покрытие для $M$(и,
соответственно, протыкающее множество для всех граней ранга $m$) мощности не больше, чем
\begin{equation*}
\left\lceil\frac1{\gamma}\ln^+(\gamma s)\right\rceil + \frac1{\gamma} \leq
\left\lceil2^m\ln^+\left(\begin{pmatrix}n\\m\end{pmatrix}\right)\right\rceil + 2^m \leq
\left\lceil2^m\log_2\left(\begin{pmatrix}n\\m\end{pmatrix}\right)\right\rceil + 2^m \leq
\lceil2^m\cdot(n - 1)\rceil + 2^m = n\cdot2^m,
\end{equation*}
что и требовалось показать.
\end{proof}
#+end_export
** Задача минимизации ДНФ. Поведение функций Шеннона и оценки типичных значений для ранга и длины ДНФ
Пусть $\psi$ - сложностной функционал, определённый на множестве всех ДНФ, $\forall \text{ ДНФ } A: \psi(A) \geq 0$
(неотрицательность), а также, что для любой ДНФ $A'$, полученной из $A$ удалением букв или символов
$\psi(A') \leq \psi(A)$(монотонность).

Пусть $f(\tilde{x}^n) \in P_2(n)$. Тогда $\psi(f) = \min\psi(A)$, где минимум берётся по всем
ДНФ $A$, реализующим $f$. Если $\psi(f)$ достигается на $\hat{A}$, то $\hat{A}$ -- \psi-минимальная
ДНФ для $f$. *Функцией Шеннона* сложностного функционала $\psi$ называется функция:
#+begin_export latex
\zall
\begin{equation*}
\psi(n) = \max_{f(\tilde{x}^n) \in P_2(n)}\psi(f), n \in \mathbb{N}
\end{equation*}
\begin{Statement}
\begin{equation*}
\forall n \in \mathbb{N} \lambda(n) = 2^{n - 1}, R(n) = n\cdot2^{n - 1},
\end{equation*}
где $\lambda(n)$ - функция Шеннона для длины ДНФ, а $R(n)$ -- функция Шеннона для ранга ДНФ.
\end{Statement}
\begin{proof}
Нижние оценки: рассмотрим $l_n(\tilde{x}^n) = x_1 \oplus \ldots \oplus x_n$. По утверждению 2.1 и
следствию из него: $\lambda(l_n) = 2^{n - 1}, R(l_n) = n\cdot2^{n - 1}$. Тогда
$R(n) \geq R(l_n) = n\cdot2^{n - 1}, \lambda(n) \geq \lambda(l_n) = 2^{n - 1}$.

Верхние оценки: рассмотрим любую БФ $f(\tilde{x}^n) \in P_2(n)$. Разложим $f$ по $x_1$:
\begin{equation*}
f(\tilde{x}^n) = \vee_{\beta \in B^{n - 1}}x_2^{\beta_2}\ldots x_n^{\beta_n}f_{\beta}(x_1) \Rightarrow
\lambda(f(\tilde{x}^n)) \leq 2^{n - 1}, R(f(\tilde{x}^n)) \leq n\cdot2^{n - 1},
\end{equation*}
что и требовалось доказать.
\end{proof}
Если некоторое свойство имеет место для булевых функций $n$ переменных, чья доля от множества
$P_2(n)$ стремится к 1 при $n \to +\infty$, то говорят, что это свойство выполняется
\textbf{почти для всех} БФ.
Пусть для почти всех БФ $f(\tilde{x}^n) \psi(f(\tilde{x}^n)) \in (\psi_1(n), \psi_2(n))$ для
некоторых $\psi_1(n)$ и $\psi_2(n)$. Тогда если $\psi_1(n) \sim \psi(n)$ и
$\psi_2(n) \sim \psi(n)$, то говорят, что для функционала $\psi$ имеет место \textbf{эффект Шеннона}.
\begin{Statement}
Для почти всех ФАЛ $f \in P_2(n)$ выполнены неравенства:
\begin{equation*}
\lambda(f) \leq \frac342^{n - 1}(1 + O(n\cdot2^{-n/2})),
\end{equation*}
\begin{equation*}
R(f) \leq \frac34n\cdot2^{n - 1}(1 + O(n\cdot2^{-n/2})).
\end{equation*}
\end{Statement}
\begin{proof}
Пусть $\alpha \in B^n$. Пусть $\xi_{\alpha}$ -- случайная величина, принимающая значения 0 и 1 с
вероятностью $\frac12$. Если $\alpha', \alpha'' \in B^n, \alpha' \neq \alpha''$, то случайные
величины $\xi_{\alpha'}$ и $\xi_{\alpha''}$ независимы. Рассмотрим теперь случайный вектор
$\tilde{\xi} = (\xi_{\tilde{0}^n}, \xi_{(0, \ldots, 0, 1)}, \ldots, \xi_{\tilde{1}^n})$,
являющийся реализацией БФ $f(\tilde{x}^n)$. Вероятность того, что случайная величина $\tilde{\xi}$
равна некоторой БФ $f(\tilde{x}^n)$, есть $\frac1{2^{2^n}}$, т. е. на $P_2(n)$ задано равномерное
распределение.
\begin{equation*}
\forall \alpha \in B^n: \mathbb{E}\xi_{\alpha} = \frac12, \mathbb{D}\xi_{\alpha} = \frac14
\end{equation*}
Пусть
\begin{equation*}
\eta = \sum_{\alpha \in B^n}\xi_{\alpha}
\end{equation*}
Поскольку случайные величины $\xi_{\alpha}$ независимы, то
\begin{equation*}
\mathbb{E}\eta = \sum_{\alpha \in B^n}\mathbb{E}\xi_{\alpha} = 2^{n - 1}
\end{equation*}
и
\begin{equation*}
\mathbb{D}\eta = \sum_{\alpha \in B^n}\mathbb{D}\xi_{\alpha} = 2^{n - 2}
\end{equation*}
Если реализация случайной величины $\tilde{\xi}$ есть БФ $f(\tilde{x}^n)$, то соответствующая
реализация случайной величины $\eta$ есть $|N_f|$. Положим $m = \lfloor n\cdot2^{n/2}\rfloor$,
$I(n) = (2^{n - 1} - m; 2^{n + 1} + m)$.
По неравенству Чебышёва:
\begin{equation*}
\mathbb{P}(|X - \mathbb{E}X| \geq a) \leq \frac{\mathbb{D}X}{a^2}
\end{equation*}
В нашем случае
\begin{equation*}
\mathbb{P}(\eta \notin I(n)) \leq \frac{\mathbb{D}\eta}{m^2} \leq \frac{2^{n - 2}}{n^2\cdot2^n} =
\frac1{4n^2} \to_{n \to \infty} 0.
\end{equation*}
Таким образом, для почти всех булевых функций $f(\tilde{x}^n)$:
\begin{equation*}
2^{n - 1} - \lfloor n\cdot2^{n/2}\rfloor < |N_f| < 2^{n - 1} + \lfloor n\cdot2^{n/2}\rfloor
\end{equation*}
\end{proof}
#+end_export
