#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+OPTIONS: toc:nil
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

\zall

Лектор Гуров Сергей Исаевич

На одной из лекции будет КР. Допуск к экзамену <- зачёт по КР.

*Группа* - тройка $<G, \circ, e>$, где $G$ - непустое множество, e - единичный(нейтральный) элемент, причём выполнены следующие аксиомы:
1. Замкнутость(устойчивость) $G$ относительно операции.
2. Ассоциативность операции.
3. $(x \circ e) = (e \circ x) = x$
4. $\forall x \in G \exists y \in G x \circ y = e$
Таблица Кэли - аналог таблицы умножения.

$V_4 = \{e, a, b, c\}$

#+BEGIN_EXPORT latex
\begin{tabular}{|c|c|c|c|c|}
\hline
$\circ$  & e & a & b & c \\
\hline
e        & e & a & b & c \\
\hline
a        & a & e & c & b \\
\hline
b        & b & c & e & a \\
\hline
c        & c & b & a & e \\
\hline
\end{tabular}
#+END_EXPORT

Примеры групп: $\mathbb{Q}, \mathbb{Z}, \mathbb{R}, \mathbb{C}$ относительно сложения.
$n\mathbb{Z}, B^n, S_n$.

В случае, если операция коммутативна, группа называется *коммутативной* или *абелевой*.

Пусть $a \in G$. Наименьшее $n$ такое, что $a^n = e$ называется *порядком* элемента $a$($\operatorname{ord} a$).

Подгруппой G называется $H \subset G$ являющееся подгруппой: $H \leq G$.
Каждый элемент порождает группу $\{a, a^2, \ldots, a^{\operatorname{ord} a}\}$.

Пусть $H \leq G, x \in G$. *Правым(левым) смежным классом* x называют множество:
$$xH = \{x \circ n | n \in H\}, Hx = \{n \circ x | n \in H\}$$
Подгруппа, для которой левые и правые классы с одинаковым представителем совпадают, называется
*нормальной*.

#+BEGIN_EXPORT latex
\begin{Theorem}
Правые(левые) смежные классы разных элементов либо совпадают, либо не пересекаются.
\end{Theorem}
#+END_EXPORT

*Изоморфизм* - биекция, сохраняющая операцию. Группы, между которыми существуют изоморфизмы,
называются *изоморфными*.

#+BEGIN_EXPORT latex
\begin{Theorem}[Теорема Кэли]
Любая конечная группа порядка $n$ изоморфна некоторой подгруппе $S_n$.
\end{Theorem}
#+END_EXPORT

*Гомоморфизм* - отображение меджу группами, сохраняющее операцию.

#+BEGIN_EXPORT latex
\begin{Theorem}
Пусть $H$ - нормальная подгруппа $G$. Тогда
$$|G| = |H| \cdot [G: H]$$
Число $[G: H]$ называется индексом группы $G$ относительно нормальной подгруппы $H$.
\end{Theorem}
#+END_EXPORT

*Циклическими* называют группы, порождённые одним элементом. Бесконечные циклические группы изоморфны
группе целых чисел по сложению. Циклические группы порядка n изоморфны группе вычетов порядка n.

Все порождающие элементы $\mathbb{Z}_n$ это числа, взаимно простые с $n$.

*Функция Эйлера* - количество чисел, взаимно простых с p, меньших p.
Свойства функции Эйлера:
1. $\varphi(p^k) = p^{k - 1}\varphi(p)$.
2. Если $(a, b) = 1$, то $\varphi(ab) = \varphi(a)\varphi(b)$.

Абелева группа называется *кольцом*, если на ней определена операция умножения, связанная
с операцией сложения дистрибутивностью.

Если умножение ассоциативно(коммутативно), кольцо называется *ассоциативным(коммутативным)*.
Если у умножения существует нейтральный элемент, кольцо называется *кольцом с единицей*.
Если $\forall a \neq 0, b \neq 0 ab \neq 0$, кольцо называется *кольцом без делителей нуля*.
Ассоциативное коммутативное кольцо с единицей без делителей нуля называется *целостным*.

Пусть R - кольцо.
Множество обратимых элементов R обозначаем R^*.

Элемент кольца называется *неразложимым*, если он не может быть представлен в виде произведения двух других.

*Факториальным* называется кольцо, каждый ненулевой элемент которого либо обратим, либо однозначно
с точностью до порядка сомножителей и умножения на обратимые элементы раскладывается на неразложимые
множители. Такое разложение числа называется *примарным*.

Рассмотрим $S \subset R$, являющееся кольцом. Такое множество называется *подкольцом*. Условия:
1. S - подгруппа по сложению
2. S замкнуто по умножению.

(Двухсторонним)*Идеалом* называется подкольцо коммутативного кольца, замкнутое относительно
и умножения на элементы кольца.

Идеал $I$ коммутативного кольца $R$ называется *главным* с представителем \(a \in R\)(идеалом, порождённым $a$), если
$$I = \{r\cdot a | r \in R\} = (a)$$

Кольца, в которых все идеалы являются главными, называются *кольцами главных идеалов*. *Максимальным*
называется идеал, такой что $I_{max} \subset I \Rightarrow I = R$.

*Утверждение*: В коммутативном кольце всегда существует максимальный идеал.

*Классом вычетов* по модулю идеала $I$ коммутативного кольца $R$ с представителем $r \in R$
называется множество $r + I = \{r + i | i \in I\} = \overline{r_I}$.

*Фактор-кольцом* $R/I$ называется кольцо классов вычетов $\overline{r_I}$.

*Утверждение*: Фактор-кольцо по максимальному идеалу является полем.

Целостное кольцо $R$ называется *евклидовым*, если $\forall a \in R, a \neq 0 \exists N(a) \in \mathbb{N}$,
такая, что $\forall b \neq 0 a = bq + r$, причём $r = 0$ или $N(r) < N(b)$.

Целостное кольцо, в котором каждый ненулевой элемент обратим, называется *полем*. У поля есть
мультипликативная группа(абелева группа по умножению).

Будем обозначать $R^*$ множество обратимых элементов кольца $R$.

У поля существуют только тривиальные идеалы.

Структура, аналогичная полю, в которой умножение некоммутативно, называется *телом*.
#+BEGIN_EXPORT latex
\begin{Theorem}
В теле нет нетривиальных идеалов.
\end{Theorem}
#+END_EXPORT
*Линейным векторным пространством* V над полем P называется аддитивная группа по сложению,
для элементов которой определено умножение на элементы поля, обладающая свойствами:
$$a(v_1 + v_2) = av_1 + av_2 \forall a \in P, v_1, v_2 \in V$$
$$(a + b)v = av + bv \forall a, b \in P, v \in V$$
$$a(bv) = (ab)v \forall a, b \in P, v \in V$$
$$1v = v \forall v \in V$$
и замкнутая относительно линейной комбинации с коэффициентами из P.

Поля вычетов по модулю $p$, где $p$ - простое, называются *простыми полями Галуа*. Минимальное
число $p$ такое, что $\underbrace{1 + 1 + \ldots + 1}_{p} = 0$, называется *характеристикой* поля.
Если $p = \infty$, считается, что $p = 0$. Поле дробей-многочленов имеет конечную характеристику,
но является бесконечным.

*Утверждение(тождество Фробениуса)*: $\forall a, b \in GF(p) (a + b)^p = a^p + b^p$

Пусть $F^*_p = F_p \ \{0\}$.

*Утверждение*: $|F^*_q| = q - 1$.

Рассмотрим $K[x]$ -  кольцо многочленов над полем $K$ от переменной $x$. Будем считать, что $a_n = 1$.
Рассмотрим $\mathbb{F}_p[x]$.
В $\mathbb{F}_2[x]$ неприводимыми являются многочлены $x^2 + x + 1, x^3 + x^2 + 1, x^3 + x + 1$.
В $\mathbb{F}_5[x]$ неприводимыми являются 6 многочленов.
#+BEGIN_EXPORT latex
\begin{Theorem}
В $\mathbb{F}_p \forall n < p$ существует неприводимый многочлен степени n.
\end{Theorem}
Пусть $a(x) \in \mathbb{F}_p[x]$ - неприводимый многочлени степени n. Рассмотрим
$(a(x)) = \{q(x)a(x) | q(x) \in \mathbb{F}_p[x]\}$. Тогда $\mathbb{F}_p[x] / (a(x))$ - множество
остатков от деления многочленов на a(x) - является полем. Если $a(x)$ - многочлен степени $n$, то
все остатки - многочлены степени до $n - 1$. Получили \textbf{расширение} поля Галуа $\mathbb{F}_p^n$,
$GF(p^n)$.

\textbf{Пример}:\\
$\mathbb{F}_3^2$ - ?

\begin{equation}
\mathbb{F}_3^2[x] = \mathbb{F}_3^2[x]/(x^2 + 1) = \{0, 1, 2, x, 2x, x + 1, x + 2, 2x + 1, 2x + 2\}
\end{equation}

\textbf{Пример 2}:\\
Рассмотрим $\mathbb{R}[x], a(x) = x^2 + 1$. Тогда
\begin{equation}
\mathbb{R}[x]/(x^2 + 1) = \{ax + b | a, b \in \mathbb{R}\} \text{ - поле комплексных чисел}
\end{equation}
\begin{Theorem}
Поля расширения по разным многочленам изоморфны.
\end{Theorem}
\begin{Theorem}[Соотношение Безу]
$\forall a, b \in \mathbb{N} \exists d \in \mathbb{N}, x, y \in \mathbb{Z}: ax + by = d, d = (a, b)$.
\end{Theorem}

\textbf{Расширенный алгоритм Евклида}:
\begin{equation*}
E = \begin{Vmatrix}
1 & 0 \\
0 & 1 \\
\end{Vmatrix},
r = 0.
\end{equation*}
Если $r = 0$, то второй столбец $E$ даёт $x$ и $y$.

Иначе \begin{equation}
E \to E \cdot \begin{Vmatrix}
0 & 1 \\
1 & -q
\end{Vmatrix}
\end{equation}
и $(a, b) \to (b, r)$.
#+END_EXPORT

#+BEGIN_EXPORT latex
Алгоритм Евклида позволяет искать обратный элемент в $\mathbb{Z}_m$:

1. Пусть $(c, m) = 1$. \\
2. Рассмотрим матрицу \begin{equation}
\begin{Vmatrix}
m & 0 \\
c & 1.
\end{Vmatrix}
\end{equation}\\
3. Поделим $m$ на $c$ с остатком: $m = qc + r$.\\
4. Вторую строку домножаем на $q$ и вычитаем из первой.\\
5. Когда первый элемент последней строки становится равным нулю, второй элемент даёт $c^{-1}$.
#+END_EXPORT

*Обобщённый алгоритм Евклида для нахождения в* $\mathbb{F}_p/(a(x)) y(x)$, *обратного к* $b(x)$:
#+BEGIN_EXPORT latex
Шаг 0: $r_{-2}(x) = a(x), r_{-1}(x) = b(x), y_{-2}(x) = 0, y_{-1}(x) = 1$.\\
Шаг 1: $$r_{-2} / r_{-1} \Rightarrow q_0, r_0$$
$$r_{-2}(x) = r_{-1}(x)q_0(x) + r_0(x)$$
$$y_0(x) = -q_0(x)$$
Если $\operatorname{deg} r_0(x) \geq 1$ - к следующему шагу, иначе к $(n + 1)$-му шагу.\\
Шаг 2: $$r_{i - 3}(x) = r_{i - 2}(x)q_{i - 1}(x) + r_{i - 1}(x)$$
$$y_{i - 1}(x) = y_{i - 3}(x) - y_{i - 2}(x)q_{i - 1}(x)$$
Если $\operatorname{deg}r_{i - 1} > 0$, продолжаем итерации.
#+END_EXPORT

Элементы поля можно рассматривать как элементы некоторого векторного пространства с естественным
базисом.

Рассмотрим $\mathbb{F}_2^4 \approx \mathbb{F}_2[x] / (a(x))$, где $a(x) = x^4 + x + 1$.
Составим таблицу перехода от векторов к полиномам.

#+BEGIN_EXPORT latex
\begin{equation}
\begin{tabular}{|c|c|c|c|c|}
             & 1 & $x$ & $x^2$ & $x^3$ \\
$\alpha$     & 0 & 1   & 0     & 0 \\
$\alpha^2$   & 0 & 0   & 1     & 0 \\
$\alpha^3$   & 0 & 0   & 0     & 1 \\
$\alpha^4$   & 1 & 1   & 0     & 0 \\
$\alpha^5$   & 0 & 1   & 1     & 0 \\
$\alpha^6$   & 0 & 0   & 1     & 1 \\
$\alpha^7$   & 1 & 1   & 0     & 1 \\
$\alpha^8$   & 1 & 0   & 1     & 0 \\
$\alpha^9$   & 0 & 1   & 0     & 1 \\
$\alpha^{10}$ & 1 & 1   & 1     & 0 \\
$\alpha^{11}$ & 0 & 1   & 1     & 1 \\
$\alpha^{12}$ & 1 & 1   & 1     & 1 \\
$\alpha^{13}$ & 1 & 0   & 1     & 1 \\
$\alpha^{14}$ & 1 & 0   & 0     & 1 \\
$\alpha^{15}$ & 1 & 0   & 0     & 0.
\end{tabular}
\end{equation}
#+END_EXPORT
* Корни многочленов над конечными полями
Рассмотрим поле $\mathbb{F}_p^n$, $\beta \in \mathbb{F}_p^n$.

*Минимальным многочленом* элемента $\beta \in \mathbb{F}_p^n$ называется нормированный
многочлен минимальной степени, для которого $\beta$ - корень.

Рассмотрим поле $\mathbb{F}_p[x] / (a(x)) \approx \mathbb{F}_p^n$. Тогда $x$ - корень $a(x)$.
Если $a(x)$ неприводимый, то $m_x(x) = a_n^{-1}a(x)$. Если $x$ - корень многочлена меньшей
степени, то базис в пространстве многочленов оказывается линейно зависим.

Любой минимальный многочлен:
1. Существует
2. Неразложим
3. Единственен
#+BEGIN_EXPORT latex
\begin{Theorem}
$$\forall \beta \in \mathbb{F}_p^n \exists m_{\beta}(x), \deg m_{\beta}(x) \leq n$$
\begin{proof}
Рассмотрим элементы $1, \beta, \ldots, \beta^n$. Существуют коэффициенты $C_0, \ldots, C_n$,
одновременно не равные нулю, такие, что $C_01 + C_1\beta + \ldots + C_n\beta^n = 0$.
Тогда для многочлена $C(x) = C_0 + C_1x + \ldots + C_nx^n$ $\beta$ является корнем, из него
можно получить минимальный.
\end{proof}
\end{Theorem}
\begin{Theorem}
Минимальный многочлен неразложим.
\begin{proof}
Пусть $m_{\beta}(x) = m_1(x)m_2(x)$. При $x = \beta$ $0 = m_1(\beta)m_2(\beta) \Rightarrow m_1(\beta) = 0$
или $m_2(\beta) = 0$, что невозможно, если $m_1(x)$ и $m_2(x)$ не константы.
\end{proof}
\end{Theorem}
\begin{Theorem}
Пусть $m_{\beta}(x)$ - минимальный многочлен, $f(x)$ - многочлен, корнем которого является $\beta$.
Тогда $m_{\beta}(x) | f(x)$.
\begin{proof}
\begin{equation}
f(x) = m_{\beta}(x)q(x) + r(x)
\end{equation}
Подставим $\beta$:
\begin{equation}
0 = 0q(\beta) + r(\beta) \Rightarrow r(\beta) = 0 \Rightarrow r(x) = 0.
\end{equation}
\end{proof}
\end{Theorem}
\begin{Consequence}
Минимальный многочлен единственен.
\begin{proof}
Если бы было два минимальных многочлена, они бы делили друг друга $\Rightarrow$ они должны быть равны.
\end{proof}
\end{Consequence}
Минимальный многочлен примитивного элемента поля называется \textbf{примитивным многочленом}.

Рассмотрим $f(x) \in \mathbb{F}_p[x]$. Наименьшее поле, в котором $f(x)$ раскладывается на
линейные множители, называется \textbf{полем разложения} $f(x)$.

Каждый ненулевой элемент $\mathbb{F}_p^n$ удовлетворяет уравнению $x^{p^n - 1} - 1 = 0$, т. е.
$\mathbb{F}_p^n$ - поле разложения полинома $f(x) = x^{p^n - 1} - 1$. Отсюда следует МТФ.
\begin{Theorem}
\begin{equation}
(x^m - 1) \vdots (x^n - 1) \Leftrightarrow m \vdots n
\end{equation}
\end{Theorem}
\begin{Theorem}
Все неприводимые многочлены степени $n$ над $\mathbb{F}_p$ делят $x^{p^n} - x$.
\begin{proof}
При $n = 1$ утверждение тривиально. Пусть $n > 1$, $f(x)$ - неприводимый. Строим поле
$\mathbb{F}_p[x] / (f(x))$. $x$ - корень $f(x)$, и при этом $x^{p^n - 1} - 1 = 0$, что и даёт
требуемое.
\end{proof}
\end{Theorem}
\begin{Theorem}
Любой неприводимый делитель $x^{p^n} - 1$ имеет степень не выше $n$.
\end{Theorem}
\begin{Theorem}
Пусть $\beta \in \mathbb{F}_p^n$ - корень неприводимого многочлена $f(x) \in \mathbb{F}_p[x]$ степени n.
Тогда $\beta$, $\beta^p$, \ldots, $\beta^{p^{n - 1}}$ - все корни $f(x)$.
\begin{proof}
При $n = 1$ утверждение тривиально. Пусть $f(\beta) = 0$. Тогда $0 = (f(\beta))^p = f(\beta^p) = 0
\Rightarrow \beta^p$ - корень.
\end{proof}
\end{Theorem}
#+END_EXPORT
*** Задача 1
#+BEGIN_EXPORT latex
  Найти корни многочлена $f(x) = x^4 + 2x^3 + x^2 + x + 1 \in \mathbb{F}_3[x]$.

$f(1) = 0 \Rightarrow f(x) = (x - 1)(x^3 + x + 2)$. $f(2) = 0 \Rightarrow f(x) = (x - 1)(x - 2)(x^2 + 2x + 2)$.
Последний многочлен не имеет корней в $\mathbb{F}_3$. Строим поле $\mathbb{F}_3[x]/(x^2 + 2x + 2)$.
В этом поле многочлен имеет два корня, один из которых это $x$.

Второй корень по теореме (14) это $x^3$. Таким образом, в поле $\mathbb{F}_3[x] / (x^2 + 2x + 1)$ многочлен имеет корни
$1, 2, x, x^3$.
#+END_EXPORT
#+BEGIN_EXPORT latex
Пусть $\beta \in \mathbb{F}_p[x] / (a(x))$. Корнями минимального многочлена будут числа $\beta^{p^n}, n \in \mathbb{N}$.
Это даёт вид минимального многочлена $m_{\beta}(x) = (x - \beta)\ldots(x - \beta^{p^d - 1})$, если
$\beta^{p^d} = \beta$. Если для некоторого $d$ $\beta^{pd} = x$, минимальным многочленом будет
нормированный $a(x)$.
#+END_EXPORT
#+BEGIN_EXPORT latex
Рассмотрим многочлен из $\mathbb{F}_p[x]$. Обозначим через $I^n_p$ число неприводимых многочленов
степени $n$ в $\mathbb{F}_p[x]$.
\begin{Theorem}[Формула Гаусса]
\begin{equation}
\sum_{d|n}dI_p^d = p^n
\end{equation}
\end{Theorem}
Функция Мёбиуса $\mu(n)$: $\mu(1) = 1$
\begin{equation}
\mu(n) = \begin{cases}1, \text{ чётное произведение различных простых(чётное количество сомножителей)} \\
-1, \text{ нечётное число различных простых}\\
0, \text{ не свободно от квадратов}.
\end{cases}
\end{equation}
\begin{Theorem}[Альтернативная формула]
\begin{equation}
I_p^n = \frac1n\sum_{d|n}\mu(d)p^{\frac{n}d}
\end{equation}
\end{Theorem}
#+END_EXPORT
* Циклические подпространства колец вычетов
#+BEGIN_EXPORT latex
Рассмотрим $f \in \mathbb{F}_p[x]$ и образуем фактор-кольцо $R = \mathbb{F}_p[x]/(f)$.
\begin{Theorem}
Рассмотрим $f, \varphi \in \mathbb{F}_p[x], \varphi | f, \varphi$ - неприводим и нормирован.
Тогда в $R = \mathbb{F}_p[x] / f$:\\
1. $(\varphi)$ - идеал.\\
2. $\varphi$ - единственный нормированный многочлен степени $k$.\\
3. $\operatorname{dim}(\varphi) = n - k, n = \operatorname{deg} f$.\\
\end{Theorem}
Подпространство $L$ векторного пространства $V$ называется \textbf{циклическим}, если оно
инвариантно относительно операции циклического сдвига вектора.
\begin{Theorem}
Если $a(x) = x^n - 1$, то $R$ - циклическое пространство.
\end{Theorem}

Рассмотрим многочлены вида $x^n - 1 \in \mathbb{F}_p[x]$.

1. $n = kp$, тогда многочлен переписывается в виде $(x^k - 1)^p$. Тогда $x^k - 1$ уже
раскладывается.

2. $x^n - 1 = f_1(x)\ldots f_k(x)$.
#+END_EXPORT
11 ноября контрольная
Коды БЧХ - циклические коды, для которых заранее известно о кодовом расстоянии. Рассмотрим поле $\mathbb{F}_p^t = F$, его мультипликативную группу $F^*$.

*Циклотомический класс* $F^*$ - набор элементов $F$, являющиеся корнями одного минимального многочлена. В $\mathbb{F}^t_2$ все элементы можно получить из одного путём домножения на 2.

Построение БЧХ-кодов:
1. Выбираем $t, n = 2^t - 1$.
2. Рассматривается многочлен $x^n - 1$ и его разложение. Пусть код должен исправлять $r$ ошибок. Число $2r + 1 = \delta$ называется *конструктивным кодовым расстоянием*.
3. В $\mathbb{F}^t_n$ есть порождающий элемент $\alpha$. Выбираем элементы $\alpha, \alpha^2, \ldots, \alpha^{2r}$ - *нули кода*.
4. Порождающий полином $g(x)$ выбирается так, чтобы все нули кода были его корнями.
*Синдромами* принятого кодового слова $w$ называются значения полинома в нулях кода.
1. $t, n = 2^t - 1 > 2r + 1$
2. $\alpha(x), \operatorname{deg}\alpha(x) = t$, $\mathbb{F}_2[x] / (\alpha(x))$, $\alpha(x)$ неприводим.
3. $\alpha, \alpha^2, \ldots, \alpha^{2r}$. Пусть $h$ - количество классов, в который попало (?).
4. $g_1(x), \ldots, g_n(x)$.
5. $g(x) = g_1(x)\ldots g_n(x)$.

Декодирование:
Известны $(n, k, d), \alpha$, поле $F = \mathbb{F}_2^t = F_2[x] / (a(x))$, $n = 2^t - 1, g(x), w(x)$.
1. Находим все синдромы $S_i = w(\alpha^i), i = 1, \ldots, 2r$.
2. $\sigma(x)$ - *полином локаторов ошибок*. Считаем, что произошло $\mu \leq r$ ошибок. Составляется система линейных алгебраических уравнений, её решение даёт $\sigma(x)$. $\operatoname{deg}\sigma(x) = \nu$.
3. По корням полинома ошибок находятся позиции ошибок: $\alpha^{k_1}, \ldots, \alpha^{k_{\nu}}, j_i \equiv -k_i, i = \overline{1, v}$.
4. $e(x) = x^{j_1} + \ldots + x^{j_{\nu}}$.
5. $v(x) = w(x) + e(x)$.
Нахождение полинома локаторов ошибок:
1. По синдромам составляется *синдромный полином* $S(x) = 1 + S_1(x) + \ldots + S_{2r}x^{2r}$.
$$S(x)\sigma(x) = 1 + \lambda_1x + \lambda_2x^2 + \ldots + \lambda_{2r + \nu}x^{2r + \nu}$$
Правая часть представляется в виде:
$$S(x)\sigma(x) = \lambda(x) + x^{2r + \nu}(\lambda_{2r + 1} + \ldots)$$
Или, по модулю $x^{2r + 1}$:
$$S(x)\sigma(x) = \lambda(x)$$
Используется расширенный алгоритм Евклида.
