#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}\setcounter{stnmt}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{stnmt}\setcounter{stnmt}{0}
#+LATEX_HEADER:\def\st{\par\smallskip\refstepcounter{stnmt}\textbf{\arabic{stnmt}}}
#+LATEX_HEADER:\newtheorem*{Statement}{Утверждение \st}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

+ Интеграл Лебега без меры
+ Пространство с обобщёнными производными и обобщённые функции
+ Задача управления подъёмным краном в штормящем море.
+ Задача управления колебаниями понтографа. Найти материалы для проводов и перемычек.

* Уравнения смешанного типа
+ Трансзвуковая гидродинамка
Уравнение кого-то-кого-то:
#+begin_export latex
u = u(x, y)
\begin{equation}
yu_{xx} + u_{yy} = 0
\end{equation}
В верхней полуплоскости уравнение эллиптическое, в нижней -- гиперболическое. Нужно найти
решение $u \in C(\overline{D}) \cap C^1(D) \cap C^2(D^+) \cap C^2(D^-)$.

Положим $\nu(x) = \frac{\partial u(x, 0)}{\partial y}$.
#+end_export
Уравнение Лаврентьева-Бицадзе:
#+begin_export latex
\begin{equation}
\operatorname{sgn}(y)u_{xx} + u_{yy} = 0
\end{equation}
#+end_export
Метод разделения переменных приводит к уравнениям:
#+begin_export latex
\begin{equation}
\begin{cases}
X''(x) + \lambda X(x) = 0, \\
X(0) = X(1) = 0
\end{cases}
\end{equation}
\begin{equation}
X_n(x) = \sin \pi nx, n = 1, 2, 3, \ldots.
\end{equation}
#+end_export
Задача нагруженной струны приводит к уравнению вида:
#+begin_export latex
\begin{equation}
\begin{cases}
X'' + \lambda X = 0, \\
X(0) = 0, X'(1) = d\lambda X(1).
\end{cases}
\end{equation}
\begin{equation}
X_n = \sin \sqrt{\lambda_n}x, \ctg\sqrt{\lambda} = d\sqrt{\lambda}
\end{equation}
#+end_export
Множество $M$ называется *метрическим пространством*, если для каждой пары точек задано
расстояние между ними($\rho(x, y) \geq 0$), удовлетворяющей аксиомам:
1. $\rho(x, y) = 0 \Leftrightarrow x = y$(аксиома тождества)
2. $\rho(x, y) = \rho(y, x)$(симметрия)
3. $\rho(x, z) \leq \rho(x, y) + \rho(y, z)$(неравенство треугольника)
На любом множестве можно задать метрику:
#+begin_export latex
\begin{equation}
\rho(x, y) = \begin{cases}
1, x \neq y, \\
0, x = y.
\end{cases}
\end{equation}
#+end_export
Является ли прямая с метрикой $\rho(x, y) = \arctg|x - y|$ метрическим пространством?
Первые две аксиомы проверяются тривиально, проверим третью:
#+begin_export latex
\begin{equation}
\arctg\alpha + \arctg\beta \geq \arctg(\alpha + \beta)
\end{equation}
Рассмотрим функцию:
\begin{equation}
f(\alpha) = \arctg\alpha + \arctg\beta - \arctg(\alpha + \beta)
\end{equation}
\begin{equation}
f'(\alpha) = \frac1{1 + \alpha^2} - \frac1{1 + (\alpha + \beta)^2} > 0, f(0) = 0
\end{equation}
Последовательность элементов $M$ называется \textbf{фундаментальной}, если
$\lim_{n \to \infty, m \to \infty}\rho(x_m, x_n) = 0$. Последовательность $x_n$ \textbf{сходится} к
$x$, если $\lim_{n \to \infty}\rho(x_n, x) = 0$. Если в $M$ любая фундаментальная последовательность
сходится, оно называется \textbf{полным}.

\textbf{Шар} с центром в точке $a$ и радиусом $r$: $B(a, r): \{x \in M, \rho(x, a) < r\}$.
\textbf{Замкнутый шар}: $\overline{B(a, r)}: \{x \in M, \rho(x, a) \leq r\}$. Множество,
целиком содержащееся в каком-либо шаре, называется \textbf{ограниченным}.

Пусть $X \subset M$. Точка $a$ называется \textbf{предельной} точкой $X$, если
$B(a, r) \cap [X \backslash \{a\}] \neq \not\emptyset, \forall r > 0$. Множество, содержащее
все свои предельные точки, называется \textbf{замкнутым}. Дополнение замкнутого множества
называется \textbf{открытым}. Множество называется \textbf{нигде не плотным}, если в любой
окрестности пространства есть шар без его точек. Множество называется \textbf{всюду плотным},
если его замыкание совпадает со всем пространством.

Пусть $|E| = p > 0$, то $\forall q \in [0, p) \exists E_q \subset E: |E_q| = q$. В самом деле,
пусть $|E|$ ограничено. Тогда $E \subset [a, b]$. Рассмотрим функцию
\begin{equation}
f(x) = |E(x)|,
\end{equation}
где
\begin{equation}
E(x) = [a, x] \cap E, x \in [a, b].
\end{equation}
Тогда
\begin{equation}
f(a) = 0, f(b) = |E|,
\end{equation}
\begin{equation}
f(x + \Delta x) - f(x) = |[x, x + \Delta x] \cap E| \leq \Delta x,
\end{equation}
т. е. $f(x)$ непрерывна, т. е. принимает все значения на области значений, что и доказывает
утверждение. Пусть теперь $E$ не ограничено. Тогда рассмотрим множества $E_n = [-n, n] \cap E$.
Так как $|E_n| \to |E| \Rightarrow |E_{n_0}| > q$. К такому $E_{n_0}$ применим результат
предыдущего пункта.

Линейное пространство называется \textbf{нормированным}, если каждому его элементу сопоставлено
действительное неотрицательное число, называемое \textbf{нормой}, если для неё выполнены аксиомы:
\begin{itemize}
\item $||x|| = 0 \Leftrightarrow x = 0$,
\item $||\alpha x|| = |\alpha|||x||$,
\item $||x + y|| \leq ||x|| + ||y||$.
\end{itemize}
Расстояние вводится так: $\rho(x, y) = ||x - y||$. Бесконечномерное нормированное линейное
пространство называется \textbf{гильбертовым}.

Пусть $D$ - ограниченная односвязная область евклидова пространства. Пространство $C^m(D)$,
$m \in \mathbb{Z}, m \geq 0$ -- пространство $m$ раз дифференцируемых функций на $D$, $C(D)$ --
пространство непрерывных на $D$ функций. Аналогичное пространство рассматривается для
компакта. Для компакта справедлива \textbf{лемма Гейне-Бореля}. На $C^m(\overline{D})$ можно
ввести норму: $||f|| \equiv ||f||_{C(\overline{D})} = \max_{x \in \overline{D}}|f(x)|$. К сожалению,
такое пространство всегда будет неполным. В пространстве $C^1[0, 1]$ можно построить
фундаментальную последовательность, сходящуюся к функции вне $C^1[0, 1]$. Можно получить
полноту, поправив норму: $||f|| = \max_{x \in [0, 1]}|f(x)| + \max_{x \in [0, 1]}|f'(x)|$.

\textbf{Мультииндекс}: $\alpha = (\alpha_1, \ldots, \alpha_n), \alpha_i \geq 0, \alpha_i \in \mathbb{Z}$,
$|\alpha| = \sum_{i = 1}^n\alpha_i$. В таких обозначениях частная производная записывается как:
\begin{equation}
D^{\alpha}f(x) = \frac{\partial^{|\alpha|}f(x)}{\partial x_n^{\alpha_n}\ldots\partial x_1^{\alpha_1}}
\end{equation}
Тогда
\begin{equation}
||f||_{C^m(\overline{D})} = \sum_{|\alpha| \leq m}\max|D^{\alpha}f(x)|.
\end{equation}
С другой стороны, можно ввести норму так:
\begin{equation}
||f||_{C^m(\overline{D})} = \max_{|\alpha| \leq m}\max|D^{\alpha}f(x)|.
\end{equation}
Величина
\begin{equation}
|f|_{C^m(\overline{D})} = \max_{|\alpha| = m}\max|D^{\alpha}f(x)|
\end{equation}
называется \textbf{полунормой}. Для неё не выполняется первая аксиома.

В n-мерном пространстве множество называется \textbf{множеством меры ноль}, если существует
счётная система, покрывающая это множество n-мерных параллелепипедов/шаров, суммарным объёмом
сколь угодно малая. Свойство выполнено \textbf{почти всюду}, если оно не выполнено на множестве
точек меры ноль. Будем называть функцию \textbf{измеримой}, если её можно представить в виде
предела последовательности почти всюду сходящихся функций из $C(\overline{Q})$. Множество
называется \textbf{измеримым}, если её характеристическая функция является измеримой.

$\operatorname{supp} f(x) = \{x \in Q: f(x) \neq 0\}$ - \textbf{носитель функции}. Функция называется
\textbf{финитной} на Q, если $\operatorname{supp} f(x) \subset Q$.
Класс $L^+(Q)$ - класс функций, для которых есть последовательность финитных на Q функций $f_n(x)$,
сходящихся почти всюду к $f(x)$, таких, что $\lim_{n \to \infty}\int_Qf_n(x)dx = \int_Qf(x)dx$.
#+end_export
* Задача о нагруженной струне
Уравнение колебаний струны:
#+begin_export latex
\begin{equation}
(k(x)u_x(x, t))_x = \rho(x)u_{tt}(x, t)
\end{equation}
Предположим, что концы струны закреплены, а в точках $0 < x_1 < x_2 < \ldots < x_n < l$
закреплены грузы массы $M_i$.
Условие непрерывности струны:
\begin{equation}
u(x_i - 0, t) = u(x_i + 0, t)
\end{equation}
\begin{equation}
k(x_i)u_x|^{x_i + 0}_{x_i - 0} = -F_i(x_i)
\end{equation}
Из второго закона Ньютона:
\begin{equation}
F(x_i) = -M_iu_{tt}(x_i, t),
\end{equation}
что даёт граничные условия:
\begin{equation}
\begin{cases}
u(0, t) = u(l, t) = 0, \\
k_i(x_i)u_x|^{x_i + 0}_{x_i - 0} = M_iu_{tt}(x_i, t), i = \overline{1, n}, \\
u(x, 0) = \varphi(x), \\
u_t(x, 0) = \psi(x).
\end{cases}
\end{equation}
Ищем решение в виде $u(x, t) = X(x)T(t)$, что приводит к уравнениям
\begin{equation}
T'' + \lambda T = 0, \\
\frac{d}{dx}\left(k(x)\frac{dX}{dx}\right) + \lambda\rho(x)X(x) = 0, \\
X(0) = X(l), \\
k(x_i)[X'(x_i + 0) - X'(x_i - 0)] + \lambda M_iX(x_i) = 0, i = \overline{1, n}.
\end{equation}
\begin{equation}
\int_0^l\rho(x)X_n(x)X_m(x) + \sum_{i = 1}^mM_iX_n(x_i)X_m(x_i) = 0
\end{equation}
Пусть $E$ - произвольное измеримое множество. Множество функций, для которых существует интеграл
\begin{equation}
\int_E|f(x)|^pdx, p \geq 1,
\end{equation}
обозначается $L_p(E)$. Норма на этом пространстве:
\begin{equation}
||f||_p \equiv ||f||_{L(E)} \equiv \left(\int_E|f(x)|^pdx\right)^{1/p}
\end{equation}
Равенство нужно понимать в смысле эквивалентности. Неравенство треугольника в этом пространстве
называется \textbf{неравенством Минковского} и следует из \textbf{неравенства Гёльдера}.
Пространство $L_p$ является полным.
Полное линейное пространство называется \textbf{банаховым}. Линейное пространство называется
\textbf{гильбертовым}, если на нём определено скалярное произведение, обладающее свойствами:
\begin{enumerate}
\item $(x, y) = \overline{(y, x)}$
\item $(\lambda x, y) = \lambda(x, y)$
\item $(x, x) \geq 0 \text{ и } (x, x) = 0 \Leftrightarrow x = 0$
\end{enumerate}
Норма в гильбертовом пространстве определяется как $||x|| = \sqrt{(x, x)}$. Гильбертово
пространство является полным и бесконечномерным.
\textbf{Неравенство Коши-Буняковского}:
\begin{equation}
|(x, y)| \leq ||x||\cdot||y||
\end{equation}
\textbf{Неравенство параллелограмма}:
\begin{equation}
||x + y||^2 + ||x - y||^2 = 2(||x||^2 + ||y||^2)
\end{equation}
$L_p$ является гильбертовым только при $p = 2$. Скалярное произведение: $\int_Efgdx = (f, g)$.
Пусть $X_i$ -- конечное линейное пространство. Система $\{\Psi_i\}^{\infty}_{i = 1}$ называется
\textbf{линейно независимой}, если любая её конечная подсистема линейно независима. Система
называется \textbf{замкнутой}, если $\forall \varepsilon > 0 \forall f \in X \exists$
$\sum_{i = 1}^n\alpha_i\Psi_i: ||f - \sum_{i = 1}^n\alpha_i\Psi_i|| < \varepsilon$. Система
называется \textbf{базисом}, если для любой функции справедливо представление:
\begin{equation}
f = \sum_{i = 1}^{\infty}\alpha_i\Psi_i
\end{equation}
В $L_2$ тригонометрическая система является базисом.

В пространстве $L_2(0, l)\times\mathbb{R}^n$ система решений ЗШЛ является ортогональной.

\begin{equation}
\begin{cases}
X'' + \lambda X = 0, \\
X(0) = 0, X'(1) = d\lambda X(1).
\end{cases}
\end{equation}
\begin{equation}
\int_0^lX_nX_m(x) + dX_n(1)X_m(1) = 0
\end{equation}
Система $\Psi_i$ называется \textbf{минимальной}, если никакой её элемент нельзя с наперёд
заданной точностью приблизить конечными комбинациями других элементов системы.
\begin{equation}
\begin{cases}
X_n(x) = \sin\sqrt{\lambda_n}x, \\
\ctg\sqrt{\lambda} = d\sqrt{\lambda}
\end{cases}
\end{equation}
Из этой системы для минимальности нужно выкинуть одну функцию.

Если выкинуть $\sin(\sqrt{\lambda} lx)x$, то функция раскладывается в ряд если и только если:
\begin{equation}
\int_0^lf(x)\sin(\sqrt{\lambda}lx)dx + df(1)\sin\sqrt{\lambda}l = 0
\end{equation}
А если $d$ комплексное?

Если $d = \frac{\ctg z}z$, где $\sin z\cos z + z = 0$, то вся система является базисом, и
появляется корень кратности 2.
#+end_export
