#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+OPTIONS: toc:nil
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

#+LATEX_HEADER:\renewcommand{\div}{\operatorname{div}}
#+LATEX_HEADER:\newcommand{\rot}{\operatorname{rot}}
#+LATEX_HEADER:\newcommand{\grad}{\operatorname{grad}}

\zall

ДЗ: 6.5, 6.13, 6.14, 7.22, 7.25, 7.26, 7.19, 7.20
* Задача 6.5
Проверить, являются ли функции гармоническими:
1. $u_5 = e^{\frac{y}x}, x \neq 0$
2. $u_6 = e^{xy}$
3. $u_7 = \mathrm{Re}(z^2\cdot e^z), z = x + iy$
4. $u_8 = e^{x^2 + y^2}$
5. $u_9 = \mathrm{Im}(\sin z - \ch z), z = x + iy$
6. $u_{10} = \nu^2(x, y)$, где $\nu(x, y)$ - гармоническая, $\nu(x, y) \neq const$.
** Решение
#+BEGIN_EXPORT latex
$$\grad u_5 = \left\{ye^{\frac{y}x}\left(-\frac{y}{x^2}\right); \frac1xe^{\frac{y}x}\right\}$$
$$\Delta u_5 = \div\grad u_5 = e^{\frac{y}x}\left(-\frac{y}{x^2}\right) + y^2\left(\frac{y}{x^2}\right)^2e^{\frac{y}x} + 2\frac{y^2}{x^3}e^{\frac{y}x} + \frac1{x^2}e^{\frac{y}x} \neq 0$$
Поэтому $u_5$ не гармоническая.
$$\grad u_6 = \left\{ye^{yx}; xe^{yx}\right\}$$
$$\Delta u_6 = \div\grad u_6 = y^2e^{yx} + x^2e^{yx} \neq 0$$
Поэтому $u_6$ не гармоническая.
$u_7$ является гармонической как действительная часть аналитической функции.
$$\grad u_8 = \{2xe^{x^2 + y^2}; 2ye^{x^2 + y^2}\}$$
$$\Delta u_8 = \div\grad u_8 = 2e^{x^2 + y^2} + 4x^2e^{x^2 + y^2} + 2e^{x^2 + y^2} + 4y^2e^{x^2 + y^2} \neq 0$$
Поэтому $u_8$ не гармоническая.
$u_9$ является гармонической как мнимая часть аналитической функции.
$$\grad u_{10} = \{2\nu\nu_x; 2\nu\nu_y\}$$
$$\Delta u_{10} = \div\grad u = 2\nu_x^2 + 2\nu\nu_{xx} + 2\nu_y^2 + 2\nu\nu_{yy} = 2(\nu_x^2 + \nu_y^2) \neq 0$$
Поэтому $u_{10}$ не гармоническая.
#+END_EXPORT
* Задача 6.13
#+BEGIN_EXPORT latex
Пусть $u(x, y) = u(r(x, y), \varphi(x, y))$. Найти $u_x, u_y, u_{xx}, u_{yy}, \Delta u$ в
полярных и цилиндрических координатах.
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
$$u_x = u_rr_x + u_{\varphi}\varphi_x$$
$$u_{xx} = u_{rr}r_x^2 + 2u_{r\varphi}r_x\varphi_x + u_{\varphi\varphi}\varphi_x^2 + u_rr_{xx} + u_{\varphi}\varphi_{xx}$$
$$u_y = u_rr_y + u_{\varphi}\varphi_y$$
$$u_{yy} = u_{rr}r_y^2 + 2u_{r\varphi}r_y\varphi_y + u_{\varphi\varphi}\varphi_y^2 + u_rr_{yy} + u_{\varphi}\varphi_{yy}$$
\begin{multline}
\Delta u = u_{xx} + u_{yy} = \\
= u_{rr}(r_x^2 + r_y^2) + 2u_{r\varphi}(r_x\varphi_x + r_y\varphi_y) +
u_{\varphi\varphi}(\varphi_x^2 + \varphi_y^2) + u_r(r_{xx} + r_{yy}) + u_{\varphi}(\varphi_{xx} + \varphi_{yy}) = \\
= u_{rr}(r_x^2 + r_y^2) + 2u_{r\varphi}(r_x\varphi_x + r_y\varphi_y) + u_{\varphi\varphi}(\varphi_x^2 + \varphi_y^2)
+ u_r\Delta r + u_{\varphi}\Delta\varphi
\end{multline}
В случае цилиндрических координат добавляется слагаемое $u_{zz}$. В центрально-симметричном
случае $u_{\varphi} = 0$, поэтому формула принимает вид:
\begin{equation}
\Delta u = u_{rr}(r_x^2 + r_y^2) + u_r\Delta r
\end{equation}
#+END_EXPORT
* Задача 6.14
#+BEGIN_EXPORT latex
Пусть $u(x, y, z) = u(r(x, y, z), \varphi(x, y, z), \theta(x, y, z))$. Найти $u_x, u_y, u_z,
u_{xx}, u_{yy}, u_{zz}, \Delta u$. Найти вид уравнения и общее решение в симметричном случае.
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
$$u_x = u_rr_x + u_{\varphi}\varphi_x + u_{\theta}\theta_x$$
\begin{equation*}
u_{xx} = u_{rr}r_x^2 + u_{\varphi\varphi}\varphi_x^2 + u_{\theta\theta}\theta_x^2 +
2u_{r\varphi}r_x\varphi_x + 2u_{r\theta}r_x\theta_x + 2u_{\varphi\theta}\varphi_x\theta_x +
u_rr_{xx} + u_{\varphi}\varphi_{xx} + u_{\theta}\theta_{xx}
\end{equation*}
$$u_y = u_rr_y + u_{\varphi}\varphi_y + u_{\theta}\theta_y$$
\begin{equation*}
u_{yy} = u_{rr}r_y^2 + u_{\varphi\varphi}\varphi_y^2 + u_{\theta\theta}\theta_y^2 +
2u_{r\varphi}r_y\varphi_y + 2u_{r\theta}r_y\theta_y + 2u_{\varphi\theta}\varphi_y\theta_y +
u_rr_{yy} + u_{\varphi}\varphi_{yy} + u_{\theta}\theta_{yy}
\end{equation*}
$$u_z = u_rr_z + u_{\varphi}\varphi_z + u_{\theta}\theta_z$$
\begin{equation*}
u_{zz} = u_{rr}r_z^2 + u_{\varphi\varphi}\varphi_z^2 + u_{\theta\theta}\theta_z^2 +
2u_{r\varphi}r_z\varphi_z + 2u_{r\theta}r_z\theta_z + 2u_{\varphi\theta}\varphi_z\theta_z +
u_rr_{zz} + u_{\varphi}\varphi_{zz} + u_{\theta}\theta_{zz}
\end{equation*}
\begin{multline}
\Delta u = u_{xx} + u_{yy} + u_{zz} = u_{rr}(r_x^2 + r_y^2 + r_z^2)
+ u_{\varphi\varphi}(\varphi_x^2 + \varphi_y^2 + \varphi_z^2)
+ u_{\theta\theta}(\theta_z^2 + \theta_y^2 + \theta_z^2) + \\
+ 2u_{r\varphi}(r_x\varphi_x + r_y\varphi_y + r_z\varphi_z)
+ 2u_{r\theta}(r_x\theta_x + r_y\theta_y + r_z\theta_z) +
+ 2u_{\varphi\theta}(\varphi_x\theta_x + \varphi_y\theta_y + \varphi_z\theta_z) + \\
+ u_r\Delta r + u_{\varphi}\Delta\varphi + u_{\theta}\Delta\theta
\end{multline}
В сферически-симметричном случае $u_{\varphi} = u_{\theta} = 0$, поэтому
\begin{equation}
\Delta u = u_{rr}(r_x^2 + r_y^2 + r_z^2) + u_r\Delta r
\end{equation}
Учитывая, что $r = \sqrt{x^2 + y^2 + z^2}$, получаем, что
\begin{equation}
\begin{cases}
r_x = -\frac{2x}{2\sqrt{x^2 + y^2 + z^2}}, \\
r_y = -\frac{2y}{2\sqrt{x^2 + y^2 + z^2}}, \\
r_z = -\frac{2z}{2\sqrt{x^2 + y^2 + z^2}}, \\
r_{xx} = -\left(\frac1{\sqrt{x^2 + y^2 + z^2}} - \frac{2x^2}{2(\sqrt{x^2 + y^2 + z^2})^3}\right) =
-\frac{y^2 + z^2}{(x^2 + y^2 + z^2)^{\frac32}}, \\
r_{yy} = -\frac{x^2 + z^2}{(x^2 + y^2 + z^2)^{\frac32}}, \\
r_{zz} = -\frac{x^2 + y^2}{(x^2 + y^2 + z^2)^{\frac32}}.
\end{cases}
\end{equation}
Подставляя в (4), находим:
\begin{equation*}
\Delta u = u_{rr}\left(-\frac{x^2 + y^2 + z^2}{x^2 + y^2 + z^2}\right) +
u_r\left(-\frac{2x^2 + 2y^2 + 2z^2}{(x^2 + y^2 + z^2)^{\frac32}}\right) = 
-u_{rr} - \frac2{\sqrt{x^2 + y^2 + z^2}}u_r = -u_{rr} - \frac2ru_r = 0
\end{equation*}
Получили уравнение:
\begin{equation}
u_{rr} + \frac2ru_r = 0
\end{equation}
Обозначим $z(r) = u_r$, тогда
\begin{equation*}
z_r + \frac2rz = 0 \Rightarrow \frac{z_r}z = -\frac2r \Rightarrow \ln z = -2\ln r + \ln |C|, C \neq 0
\Rightarrow z = \frac{C}{r^2}, \forall C.
\end{equation*}
Тогда для $u$:
\begin{equation*}
u_r = \frac{C}{r^2} \Rightarrow u = \frac{C_1}r + C_2
\end{equation*}
Или, подставляя $r$:
\begin{equation}
u(x, y, z) = \frac{C_1}{\sqrt{x^2 + y^2 + z^2}} + C_2
\end{equation}
#+END_EXPORT
* Задача 7.22
#+BEGIN_EXPORT latex
Решить задачу:
\begin{equation}
\begin{cases}
\Delta u = 0, 0 < x < a, 0 < y < b, \\
u|_{y = 0} = \sin\frac{\pi x}a, 0 \leq x \leq a, \\
u|_{x = a} = 0, 0 \leq y \leq b, \\
u|_{y = b} = \sin\frac{2\pi x}a, 0 \leq x \leq a, \\
u|_{x = 0} = 0, 0 \leq y \leq b.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u(x, y) = \sum_{n = 0}^{\infty}X_n(x)Y_n(y)$. Получаем задачи:
\begin{equation}
\begin{cases}
X_n''Y_n + X_nY''_n = 0, \\
X_n(x)Y_n(0) = \varphi_{1n}(x), \\
X_n(a)Y_n(y) = 0, \\
X_n(x)Y_n(b) = \varphi_{2n}(x), \\
X_n(0)Y_n(y) = 0.
\end{cases}
\end{equation}
Каждая из которых приводится к виду:
\begin{equation*}
\begin{cases}
X_n'' + \lambda X_n = 0, \\
X_n(0) = X_n(a) = 0, \\
Y_n'' - \lambda Y_n = 0.
\end{cases}
\end{equation*}
Собственные значения и собственные функции задачи Штурма-Лиувилля:
\begin{equation*}
\begin{cases}
\lambda_n = \left(\frac{\pi n}a\right)^2, \\
X_n = \sin\frac{\pi n}ax,
\end{cases}
\end{equation*}
Ищем $Y_n$ в виде
\begin{equation*}
Y_n = C_1\exp\left\{-\left(\frac{\pi n}a\right)^2y\right\} + C_2\exp\left\{\left(\frac{\pi n}a\right)^2y\right\}
= A_n\sh\frac{\pi n}ay + B_n\sh\frac{\pi n}a(b - y)
\end{equation*}
Тогда для $u$:
\begin{equation*}
u = \sum_{n = 0}^{\infty}(A_n\sh\frac{\pi n}ay + B_n\sh\frac{\pi n}a(b - y))\sin\frac{\pi n}ax
\end{equation*}
Подставим краевые условия:
\begin{equation*}
\begin{cases}
u|_{y = 0} = \sum_{n = 0}^{\infty}B_n\sh\frac{\pi n b}a\sin\frac{\pi n a}x = \sin\frac{\pi x}a, \\
u|_{y = b} = \sum_{n = 0}^{\infty}A_n\sh\frac{\pi n b}a\sin\frac{\pi n a}x = \sin\frac{2\pi x}a.
\end{cases}
\end{equation*}
Получаем, что $A_n = 0, n \neq 2, A_2 = \frac1{\sh\frac{2\pi b}a}$, $B_n = 0, n \neq 1, B_1 = \frac1{\sh\frac{\pi b}a}$, итого:
\begin{equation}
u(x, y) = \frac{\sh\frac{\pi(b - y)}a}{\sh\frac{\pi b}a}\sin\frac{\pi x}a +
\frac{\sh\frac{2\pi y}a}{\sh\frac{2\pi b}a}\sin\frac{2\pi x}a
\end{equation}
#+END_EXPORT
* Задача 7.25
#+BEGIN_EXPORT latex
Решить задачу
\begin{cases}
\Delta u = 0, 0 < x < \pi, 0 < y < \pi, \\
\frac{\partial u}{\partial y}\bigg|_{y = 0} = \sin2x, 0 < x < \pi, \\
u|_{x = \pi} = \cos2y, 0 \leq y \leq \pi, \\
\frac{\partial u}{\partial y}\bigg|_{y = \pi} = \sin3x, 0 < x < \pi, \\
u|_{x = 0} = 0, 0 \leq y \leq \pi.
\end{cases}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Разобьём задачу на две:
\begin{equation}
\begin{cases}
\Delta u = 0, \\
\frac{\partial u}{\partial y}\bigg|_{y = 0} = \sin2x, \\
u|_{x = \pi} = 0, \\
\frac{\partial u}{\partial y}\bigg|_{y = \pi} = \sin3x, \\
u|_{x = 0} = 0,
\end{cases}
\text{ и }
\begin{cases}
\Delta u = 0, \\
\frac{\partial u}{\partial y}\bigg|_{y = 0} = 0, \\
u|_{x = \pi} = \cos 2y, \\
\frac{\partial u}{\partial y}\bigg|_{y = \pi} = 0, \\
u|_{x = 0} = 0.
\end{cases}
\end{equation}
Ищем решение первой задачи в виде
\begin{equation*}
u_1 = \sum_{n = 0}^{\infty}X_n(x)Y_n(y)
\end{equation*}
Получаем задачи
\begin{equation*}
\begin{cases}
X_n'' - \lambda X_n = 0, \\
X_n(0) = X_n(\pi) = 0, \\
Y_n'' + \lambda Y_n = 0.
\end{cases}
\end{equation*}
Собственные значения и собственные функции ЗШЛ:
\begin{equation*}
\begin{cases}
\lambda_n = n^2, \\
X_n = \sin nx.
\end{cases}
\end{equation*}
$Y_n$ ищем в виде
\begin{equation*}
Y_n = A_n\sh ny + B_n\sh n(\pi - y)
\end{equation*}
Тогда получаем:
\begin{equation*}
u_1 = \sum_{n = 0}^{\infty}(A_n\sh ny + B_n\sh n(\pi - y))\sin nx
\end{equation*}
Подставив в краевые условия, найдём:
\begin{equation*}
\begin{cases}
\frac{\partial u}{\partial y}\bigg|_{y = 0} = \sum_{n = 0}^{\infty}(nA_n - nB_n\ch\pi)\sin nx = \sin 2x, \\
\frac{\partial u}{\partial y}\bigg|_{y = \pi} = \sum_{n = 0}^{\infty}(nA_n\ch\pi - nB_n)\sin nx = \sin 3x.
\end{cases}
\end{equation*}
При $n \notin \{2, 3\} A_n = B_n = 0$. При $n = 2$:
\begin{equation*}
\begin{cases}
2A_2 - 2B_2\ch\pi = 1, \\
2A_2\ch\pi - 2B_2 = 0
\end{cases}
\Rightarrow
\begin{cases}
A_2 = -\frac1{2sh^2\pi}, \\
B_2 = -\frac{\ch\pi}{2\sh^2\pi}.
\end{cases}
\end{equation*}
При $n = 3$:
\begin{equation*}
\begin{cases}
3A_3 - 3B_3\ch\pi = 0, \\
3A_3\ch\pi - 3B_3 = 1
\end{cases}
\Rightarrow
\begin{cases}
A_3 = \frac{\ch\pi}{3\sh^2\pi}, \\
B_3 = \frac{1}{3\sh^2\pi}.
\end{cases}
\end{equation*}
Окончательно для $u_1$ имеем:
\begin{equation}
u_1 = -\left(\frac{\sh2y}{2\sh^2\pi} + \frac{\sh2(\pi - y)\ch\pi}{2\sh^2\pi}\right)\sin2x +
\left(\frac{\ch\pi\sh3y}{3\sh^2\pi} + \frac{\sh(\pi - y)}{3\sh^2\pi}\right)\sin3x
\end{equation}
Теперь найдём решение задачи (11.2) в виде
\begin{equation*}
u_2 = \sum_{n = 0}^{\infty}X_n(x)Y_n(y)
\end{equation*}
Получаем задачи
\begin{equation*}
\begin{cases}
Y_n'' - \lambda Y_n = 0, \\
Y_n'(0) = Y_n'(\pi) = 0, \\
X_n'' + \lambda X_n = 0.
\end{cases}
\end{equation*}
Собственные значения и собственные функции ЗШЛ:
\begin{equation*}
\begin{cases}
\lambda_n = n^2, \\
Y_n = \cos ny.
\end{cases}
\end{equation*}
$X_n$ имеют вид:
\begin{equation*}
X_n = A_n\sh nx + B_n\sh n(\pi - x)
\end{equation*}
Подставим в краевые условия:
\begin{equation*}
\begin{cases}
u|_{x = \pi} = \sum_{n = 0}^{\infty}A_n\sh\pi n\cos ny = \cos2y, \\
u|_{x = 0} = \sum_{n = 0}^{\infty}B_n\sh\pi n\cos ny = 0.
\end{cases}
\end{equation*}
Отсюда $A_n = B_n = 0, n \neq 2, A_2 = \frac1{\sh2\pi}, B_2 = 0$. Для $u_2$ получаем:
\begin{equation}
u_2 = \frac{\sh2x}{\sh2\pi}\cos2y.
\end{equation}
Тогда
\begin{multline}
u(x, y) = u_1(x, y) + u_2(x, y) = \\
= \frac{\sh2x}{\sh2\pi}\cos2y -
\left(\frac{\sh2y + \sh2(\pi - y)\ch\pi}{2\sh^2\pi}\right)\sin2x +
\left(\frac{\ch\pi\sh3y + \sh(\pi - y)}{3\sh^2\pi}\right)\sin3x
\end{multline}
#+END_EXPORT
* Задача 7.26
#+BEGIN_EXPORT latex
Решить задачу:
\begin{equation}
\begin{cases}
\Delta u = \sin2x, 0 < x < \frac{\pi}2, 0 < y < \infty, \\
u|_{x = 0} = 0, 0 < y < \infty, \\
u|_{y = 0} = \sin4x, 0 \leq x \leq \frac{\pi}2, \\
u|_{x = \frac{\pi}2} = 0 \leq y < \infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
 Положим $u = -\frac14\sin2x + v$. Получим задачу для $v$:
 \begin{equation*}
 \begin{cases}
 \Delta v = 0, \\
 v|_{x = 0} = 0, \\
 v|_{y = 0} = \sin4x - \frac14\sin2x, \\
 v|_{x = \frac{\pi}2} = 0.
 \end{cases}
 \end{equation*}
 Ищем решение в виде
 \begin{equation*}
 v(x, y) = \sum_{n = 0}^{\infty}X_n(x)Y_n(y)
 \end{equation*}
 Получаем задачи:
 \begin{equation*}
 \begin{cases}
 X_n'' - \lambda X_n = 0, \\
 X_n(0) = X_n\left(\frac{\pi}2\right) = 0, \\
 Y_n'' + \lambda Y_n = 0.
 \end{cases}
 \end{equation*}
 Собственные значения и собственные функции ЗШЛ:
 \begin{equation*}
 \begin{cases}
 \lambda_n = (2n)^2, \\
 X_n = \sin2nx.
 \end{cases}
 \end{equation*}
$Y_n$ ищем в виде:
\begin{equation*}
Y_n = A_ne^{(2n)^2y} + B_ne^{-(2n)^2y}.
\end{equation*}
Подставим в краевое условие:
\begin{equation*}
u(x, 0) = \sum_{n = 0}^{\infty}(A_n + B_n)\sin2nx = \sin4x - \frac14\sin2x
\end{equation*}
Тогда $A_n = B_n = 0, n \notin \{1, 2\}$. Для $n = 1$:
\begin{equation*}
\begin{cases}
A_1 + B_1 = -\frac14, \\
A_1 = 0, \text{ т. к. } v(x, y) \text{ ограничена.}
\end{cases}
\end{equation*}
При $n = 2$:
\begin{equation*}
\begin{cases}
A_2 + B_2 = 1, \\
A_2 = 0, \text{ т. к. } v(x, y) \text{ ограничена.}
\end{cases}
\end{equation*}
Итого получаем, что
\begin{equation}
u(x, y) = -\frac14\sin2x - \frac14e^{-4y}\sin2x + e^{-16y}\sin4x.
\end{equation}
#+END_EXPORT
* Задача 7.19
#+BEGIN_EXPORT latex
Решить задачу Дирихле для уравнения Лапласа в полуполосе:
\begin{equation}
\begin{cases}
\Delta u = 0, 0 < x < \infty, 0 < y < a, \\
u(0, y) = f(y), 0 \leq y \leq a, f(y) \in C[0, a], \\
u(x, 0) = f(0) = const, 0 \leq x < \infty, \\
u(x, a) = f(a) = const, 0 \leq x < \infty, \\
|u(x, y)| < const.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u = U + v$, где $U = Ay + B$ - гармоническая функция, удовлетворяющая
краевым условиям:
\begin{equation*}
\begin{cases}
B = f(0), \\
Aa + B = f(a)
\end{cases}
\Rightarrow
\begin{cases}
A = \frac{f(a) - f(0)}a, \\
B = f(0).
\end{cases}
\end{equation*}
Таким образом, $u = \frac{f(a) - f(0)}ay + f(0) + v$. Подставив в (17), получим:
\begin{equation}
\begin{cases}
\Delta v = 0, \\
v(0, y) = f(y) - \frac{f(a) - f(0)}ay - f(0) = g(y), \\
v(x, 0) = v(x, a) = 0.
\end{cases}
\end{equation}
Ищем решение (18) в виде
\begin{equation*}
v(x, y) = \sum_{n = 0}^{\infty}X_n(x)Y_n(y).
\end{equation*}
Получаем задачи
\begin{equation*}
\begin{cases}
X_n'' + \lambda_n X_n = 0, \\
Y_n'' - \lambda_n Y_n  = 0, \\
Y_n(0) = Y_n(a) = 0.
\end{cases}
\end{equation*}
Собственные значения и собственные функции соответствующей ЗШЛ:
\begin{equation*}
\begin{cases}
\lambda_n = \left(\frac{\pi n}a\right)^2, \\
Y_n = \sin\frac{\pi n}ay.
\end{cases}
\end{equation*}
$X_n$ ищем в виде
\begin{equation}
X_n = C_1\exp\left(-\left(\frac{\pi n}a\right)^2x\right) + C_2\exp\left(\left(\frac{\pi n}a\right)^2x\right)
\end{equation}
Вследствие ограниченности $u(x, y)$ $C_2 = 0 \forall n$.

Разложим $g(y)$ по $Y_n$:
\begin{equation*}
g(y) = \sum_{n = 0}^{\infty}g_nY_n(y), g_n = \frac2a\int_0^ag(y)Y_n(y)dy.
\end{equation*}
Подставим (19) в краевые условия, получим:
\begin{equation*}
u(0, y) = \sum_{n = 0}^{\infty}C_{2n}\sin\frac{\pi n}ay = \sum_{n = 0}^{\infty}g_n\sin\frac{\pi n}ay
\Rightarrow C_{2n} = g_n
\end{equation*}
Окончательно получаем:
\begin{equation}
u(x, y) = \frac{f(a) - f(0)}ay + f(0) + \sum_{n = 0}^{\infty}g_n\exp\left(-\left(\frac{\pi n}a\right)^2x\right)\sin\frac{\pi n}ay
\end{equation}
#+END_EXPORT
* Задача 7.20
#+BEGIN_EXPORT latex
Решить задачу с непрерывным краевым условием на границе прямоугольника:
\begin{equation}
\begin{cases}
\Delta u = 0, 0 < x < a, 0 < y < b, \\
u|_{y = 0} = f_1(x), 0 \leq x \leq a, \\
u|_{x = a} = f_2(y), 0 \leq y \leq b, \\
u|_{y = b} = f_3(x), 0 \leq x \leq a, \\
u|_{x = 0} = f_4(y), 0 \leq y \leq b.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
В силу непрерывности краевого условия $f_1(0) = f_4(0), f_1(a) = f_2(0), f_2(b) = f_3(a), f_3(0) = f_4(b)$.

Будем искать решение в виде $u = U + v$, где $U = A + Bx + Cy + Dxy$ - гармоническая функция,
такая, что краевые условия для $v = u - U$ обращаются в ноль в вершинах:
\begin{equation}
\begin{cases}
v|_{y = 0} = \varphi_1(x) = f_1(x) - U(x, 0), \\
v|_{x = a} = \varphi_2(y) = f_2(y) - U(a, y), \\
v|_{y = b} = \varphi_3(x) = f_3(x) - U(x, b), \\
v|_{x = 0} = \varphi_4(y) = f_4(y) - U(0, y).
\end{cases}
\end{equation}
Тогда
\begin{equation*}
\begin{cases}
f_1(0) - U(0, 0) = f_1(0) - A = 0, \\
f_1(a) - U(a, 0) = f_1(a) - A - Ba = 0, \\
f_3(0) - U(0, b) = f_3(0) - A - Cb = 0, \\
f_3(a) - U(a, b) = f_3(b) - A - Ba - Cb - Dab = 0,
\end{cases}
\Rightarrow
\begin{cases}
A = f_1(0), \\
A + Ba = f_1(a), \\
A + Cb = f_3(0), \\
A + Ba + Cb + Dab = f_3(b),
\end{cases}
\end{equation*}
\begin{equation}
\begin{dcases}
A = f_1(0), \\
B = \frac{f_1(a) - f_1(0)}a, \\
C = \frac{f_3(0) - f_1(0)}b, \\
D = \frac{f_3(b) - f_3(0) - f_1(a) + f_1(0)}ab.
\end{dcases}
\end{equation}
Решение задачи (22) будем искать в виде суммы решений задач:
\begin{equation}
\begin{cases}
\Delta v_1 = 0, \\
v_1|_{y = 0} = \varphi_1(x), \\
v_1|_{y = b} = \varphi_3(x), \\
v_1|_{x = 0} = v_1|_{x = b} = 0,
\end{cases}
\begin{cases}
\Delta v_2 = 0, \\
v_2|_{x = a} = \varphi_2(y), \\
v_2|_{x = 0} = \varphi_4(y), \\
v_2|_{y = 0} = v_2|_{y = b} = 0.
\end{cases}
\end{equation}
Решение задачи ищем в виде:
\begin{equation}
v_1 = \sum_{n = 0}^{\infty}X_n(x)Y_n(y).
\end{equation}
Получаем задачи
\begin{equation*}
\begin{cases}
X'' - \lambda X = 0, \\
X(0) = X(a) = 0, \\
Y'' + \lambda Y = 0.
\end{cases}
\end{equation*}
Собственные значения и собственные функции ЗШЛ:
\begin{equation*}
\begin{cases}
\lambda_n = \left(\frac{\pi n}a\right)^2, \\
X_n = \sin\frac{\pi n}ax.
\end{cases}
\end{equation*}
$Y_n$ ищем в виде:
\begin{equation*}
Y_n = A_n\sh\frac{\pi n}ay + B_n\sh\frac{\pi n}a(b - y)
\end{equation*}
Для $u_1$ получаем:
\begin{equation}
v_1(x, y) = \sum_{n = 0}^{\infty}\left(A_n\sh\frac{\pi n}ay + B_n\sh\frac{\pi n}a(b - y)\right)\sin\frac{\pi n}ax
\end{equation}
Разложим $\varphi_1(x)$ и $\varphi_3(x)$ по $X_n(x)$:
\begin{equation}
\begin{cases}
\varphi_1(x) = \sum_{n = 0}^{\infty}\varphi_{1n}X_n(x), \\
\varphi_3(x) = \sum_{n = 0}^{\infty}\varphi_{3n}X_n(x).
\end{cases}
\end{equation}
Подставим (26) и (27) в краевые условия, получим систему:
\begin{equation*}
\begin{dcases}
v_1|_{y = 0} = \sum_{n = 0}^{\infty}B_n\sh\frac{\pi nb}a\sin\frac{\pi n}ax = \sum_{n = 0}^{\infty}\varphi_{1n}\sin\frac{\pi n}ax, \\
v_1|_{y = b} = \sum_{n = 0}^{\infty}A_n\sh\frac{\pi nb}a\sin\frac{\pi n}ax = \sum_{n = 0}^{\infty}\varphi_{3n}\sin\frac{\pi n}ax,
\end{dcases}
\Rightarrow
\begin{dcases}
A_n = \frac{\varphi_{3n}}{\sh\frac{\pi nb}a}, \\
B_n = \frac{\varphi_{1n}}{\sh\frac{\pi nb}a}.
\end{dcases}
\end{equation*}
Подставляя найденные $A_n$ и $B_n$ в (26), получаем:
\begin{equation}
v_1(x, y) = \sum_{n = 0}^{\infty}\left(\varphi_{3n}\frac{\sh\frac{\pi ny}a}{\sh\frac{\pi nb}a} + \varphi_{1n}\frac{\sh\frac{\pi n(b - y)}a}{\sh\frac{\pi nb}a}\right)\sin\frac{\pi n}ax
\end{equation}
Аналогичным образом находим решение второй задачи:
\begin{equation}
v_2(x, y) = \sum_{n = 0}^{\infty}\left(\varphi_{2n}\frac{\sh\frac{\pi nx}b}{\sh\frac{\pi na}b} + \varphi_{4n}\frac{\sh\frac{\pi n(a - y)}b}{\sh\frac{\pi na}b}\right)\sin\frac{\pi n}by
\end{equation}
Собирая вместе (23), (28) и (29), для $u$ получаем:
\begin{multline}
u(x, y) = U + v = f_1(0) + \frac{f_1(a) - f_1(0)}ax + \frac{f_3(0) - f_1(0)}by + \frac{f_3(b) - f_3(0) - f_1(a) + f_1(0)}abxy + \\
+ \sum_{n = 0}^{\infty}\left(\left(\varphi_{3n}\frac{\sh\frac{\pi ny}a}{\sh\frac{\pi nb}a} + \varphi_{1n}\frac{\sh\frac{\pi n(b - y)}a}{\sh\frac{\pi nb}a}\right)\sin\frac{\pi nx}a +
\left(\varphi_{2n}\frac{\sh\frac{\pi nx}b}{\sh\frac{\pi na}b} + \varphi_{4n}\frac{\sh\frac{\pi n(a - y)}b}{\sh\frac{\pi na}b}\right)\sin\frac{\pi ny}b\right)
\end{multline}
#+END_EXPORT
