#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+OPTIONS: toc:nil
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

ДЗ: 5.2, 5.3, 5.5, 5.6, 5.7, 5.9, 5.15, 5.19, 5.20
* Задача 5.2
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = 4u_{xx} + t + e^t, -\infty < x < +\infty, t > 0, \\
u(x, 0) = 2, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u(x, t) = V(t)$. Тогда:
\begin{equation}
\begin{cases}
V' = t + e^t, \\
V(0) = 2
\end{cases}
\Rightarrow
\begin{cases}
V = \frac{t^2}2 + e^t + C, \\
V(0) = C + 1 = 2
\end{cases}
\Rightarrow
V = \frac{t^2}2 + e^t + 1.
\end{equation}
В силу теоремы единственности других решений нет.
#+END_EXPORT
* Задача 5.3
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + 3t^2, -\infty < x < +\infty, t > 0, \\
u(x, 0) = \sin x, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде суммы решений задач:
\begin{equation}
\begin{cases}
u_{1t} = u_{1xx}, -\infty < x < +\infty, t > 0, \\
u_1(x, 0) = \sin x, -\infty < x < +\infty.
\end{cases}
\end{equation}
и
\begin{equation}
\begin{cases}
u_{2t} = u_{2xx} + 3t^2, -\infty < x < +\infty, t > 0, \\
u_2(x, 0) = 0, -\infty < x < +\infty.
\end{cases}
\end{equation}
Задача (5) имеет решение $u_2(x, t) = t^3$. Решение задачи (4) ищем в виде $u_1(x, t) = F(t)\sin x$.
Получим:
\begin{equation*}
\begin{cases}
F'\sin x = -F\sin x, \\
F(0)\sin x = \sin x.
\end{cases}
\end{equation*}
или, после сокращения
\begin{equation}
\begin{cases}
F' = -F, \\
F(0) = 1.
\end{cases}
\end{equation}
Решением этой задачи является функция $F(t) = e^{-t}$. Окончательно для $u(x, t)$ получаем:
\begin{equation}
u(x, t) = t^3 + e^{-t}\sin x.
\end{equation}
#+END_EXPORT
* Задача 5.5
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + e^t\sin x, -\infty < x < +\infty, t > 0, \\
u(x, 0) = \sin x, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u(x, t) = F(t)\sin x$. Подставив, найдём:
\begin{equation*}
\begin{cases}
F'\sin x = -F\sin x + e^t\sin x, \\
F(0)\sin x = \sin x.
\end{cases}
\end{equation*}
После сокращения получим задачу Коши для $F(t)$:
\begin{equation}
\begin{cases}
F' = -F + e^t, \\
F(0) = 1.
\end{cases}
\end{equation}
Ищем решение в виде $F(t) = C(t)e^{-t}$. Для $C(t)$ получим задачу:
\begin{equation}
\begin{cases}
C'e^{-t} = e^t, \\
C(0) = 1,
\end{cases}
\end{equation}
решением которой является функция $C(t) = \frac12e^{2t}$. Тогда $F(t) = \frac12e^t$ и
окончательно получаем:
\begin{equation}
u(x, t) = \frac12e^t\sin x.
\end{equation}
#+END_EXPORT
* Задача 5.6
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + \sin t, -\infty < x < +\infty, t > 0, \\
u(x, 0) = e^{-x^2}, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде суммы решений задач
\begin{equation}
\begin{cases}
u_{1t} = u_{1xx} + \sin t, -\infty < x < +\infty, t > 0, \\
u_1(x, 0) = 0, -\infty < x < +\infty
\end{cases}
\end{equation}
и
\begin{equation}
\begin{cases}
u_{2t} = u_{2xx}, -\infty < x < +\infty, t > 0, \\
u_2(x, 0) = e^{-x^2}, -\infty < x < +\infty.
\end{cases}
\end{equation}
Решение первой задачи ищем в виде $u_1(x, t) = F(t)$. Получим:
\begin{equation}
\begin{cases}
F' = \sin t, \\
F(0) = 0.
\end{cases}
\end{equation}
Решением этой задачи является функция $u_1(x, t) = F(t) = 1 - \cos t$.

Пусть $U(x, t)$ - решение уравнения $u_t = u_{xx}$. Тогда функция
$$U_2(x, t) = \frac1{\sqrt{1 + 4ct}}\exp\left(-\frac{cx^2}{1 + 4c^2t}\right)U\left(\frac{x}{1 + 4ct}, \frac{t}{1 + 4ct}\right)$$
также является решением этого уравнения. Положим $U(x, t) \equiv 1$ и подставим $U_2$ в начальные
условия:
\begin{equation*}
U_2(x, 0) = e^{-cx^2} = e^{-x^2} \Rightarrow c = 1
\end{equation*}
Получили, что
$u_2(x, t) = \frac1{\sqrt{1 + 4t}}\exp\left(-\frac{x^2}{1 + 4t}\right)$, откуда для $u(x, t)$:
\begin{equation}
u(x, t) = 1 - \cos t + \frac1{\sqrt{1 + 4t}}\exp\left(-\frac{x^2}{1 + 4t}\right)
\end{equation}
#+END_EXPORT
* Задача 5.7
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx}, -\infty < x < +\infty, t > 0, \\
u(x, 0) = xe^{-x^2}, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Пусть $U(x, t)$ - решение уравнения теплопроводности. Тогда функция
\begin{equation*}
U_2(x, t) = \frac1{\sqrt{1 + 4ct}}\exp\left(-\frac{cx^2}{1 + 4c^2t}\right)U\left(\frac{x}{1 + 4ct}, \frac{t}{1 + 4ct}\right)
\end{equation*}
также является его решением. Положим $U(x, t) = x$ и подставим $U_2(x, t)$ в начальное условие:
\begin{equation}
U_2(x, 0) = xe^{-cx^2} = xe^{-x^2} \Rightarrow c = 1.
\end{equation}
Получили, что
\begin{equation}
u(x, t) = U_2(x, t) = \frac1{\sqrt{1 + 4t}}\exp\left(-\frac{x^2}{1 + 4t}\right)\frac{x}{1 + 4t}.
\end{equation}
#+END_EXPORT
* Задача 5.9
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
4u_t = u_{xx}, -\infty < x < +\infty, t > 0, \\
u(x, 0) = \sin xe^{-x^2} -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Пусть $U(x, t)$ - решение уравнения теплопроводности. Тогда функция
\begin{equation*}
U_2(x, t) = \frac1{\sqrt{1 + 4ct}}\exp\left(-\frac{cx^2}{1 + 4c^2t}\right)U\left(\frac{x}{1 + 4ct}, \frac{t}{1 + 4ct}\right)
\end{equation*}
тоже является его решением. Положим $U(x, t) = e^{-\frac14t}\sin x$ и подставим в начальное условие:
\begin{equation*}
U_2(x, 0) = e^{-cx^2}\sin x = e^{-x^2}\sin x \Rightarrow c = 1
\end{equation*}
Откуда
\begin{multline}
u(x, t) = U_2(x, t) = \frac1{\sqrt{1 + 4ct}}\exp\left(-\frac{x^2}{1 + 4t}\right)U\left(\frac{x}{1 + 4t}, \frac{t}{1 + 4t}\right) = \\
= \frac1{\sqrt{1 + 4t}}\exp\left(-\frac{x^2}{1 + 4t}\right)\exp\left(-\frac{t}{4 + 16t}\right)\sin\frac{x}{1 + 4t} =
\frac1{1 + 4t}\exp\left(-\frac{4x^2 + t}{4 + 16t}\right)\sin\frac{x}{1 + 4t}.
\end{multline}
#+END_EXPORT
* Задача 5.15
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, -\infty < x < +\infty, t > 0, \\
u(x, 0) = \varphi(x) =
\begin{cases}
u_1 = const, x < 0, \\
u_2 = const, x > 0.
\end{cases}
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Решение имеет вид
\begin{multline}
u(x, t) = \frac1{2\sqrt{\pi a^2t}}\int_{-\infty}^{+\infty}\exp\left(-\frac{(x - \xi)^2}{4a^2t}\right)\varphi(\xi)d\xi = \\
= \frac{u_1}{2\sqrt{\pi a^2t}}\int_{-\infty}^0\exp\left(-\frac{(x - \xi)^2}{4a^2t}\right)d\xi +
\frac{u_2}{2\sqrt{\pi a^2t}}\int_0^{+\infty}\exp\left(-\frac{(x - \xi)^2}{4a^2t}\right)d\xi = \\
= -\frac{u_1\cdot2a\sqrt{t}}{2\sqrt{\pi a^2t}}\int_{-\infty}^0\exp\left(-\frac{(x - \xi)^2}{4a^2t}\right)d\left(\frac{x - \xi}{2a\sqrt{t}}\right) -
\frac{u_2\cdot2a\sqrt{t}}{2\sqrt{\pi a^2t}}\int_0^{+\infty}\exp\left(-\frac{(x - \xi)^2}{4a^2t}\right)d\left(\frac{x - \xi}{2a\sqrt{t}}\right) = \\
= -\frac{u_1}{\sqrt{\pi}}\int_{+\infty}^{\frac{x}{2a\sqrt{t}}}e^{-\xi^2}d\xi - \frac{u_2}{\sqrt{\pi}}\int_{\frac{x}{2a\sqrt{t}}}^{-\infty}e^{-\xi^2}d\xi =
\frac{u_1}2\left(1 - \Phi\left(\frac{x}{2a\sqrt{t}}\right)\right) + \frac{u_2}2\left(1 - \Phi\left(-\frac{x}{2a\sqrt{t}}\right)\right) = \\
= \frac{u_1 + u_2}2\left(1 - \Phi\left(\frac{x}{2a\sqrt{t}}\right)\right)
\end{multline}
#+END_EXPORT
* Задача 5.19
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, 0 < x < +\infty, t > 0, \\
u_x(0, t) = 0, t > 0, \\
u(x, 0) = \varphi(x) =
\begin{cases}
u_0 = const \neq 0, 0 \leq x \leq l, \\
0, l < x < +\infty.
\end{cases}
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Продолжим функцию $\varphi(x)$ чётным образом, получим задачу:
\begin{equation}
u_t = a^2u_{xx}, 0 < x < +\infty, t > 0, \\
u(x, 0) = \begin{cases}
u_0, |x| \leq l, \\
0, |x| > l.
\end{cases}
\end{equation}
Вследствие чётности $\varphi(x)$ второе условие (24) выполнено автоматически. Решение задачи
(25) имеет вид
\begin{multline}
u(x, t) = \frac{u_0}{2\sqrt{\pi a^2t}}\int_{-l}^l\exp\left(-\frac{(x - \xi)^2}{4a^2t}d\xi\right) =
-\frac{u_0\cdot2\sqrt{a^2t}}{2\sqrt{\pi a^2t}}\int_{-l}^l\exp\left(-\frac{(x - \xi)^2}{4a^2t}\right)d\left(\frac{x - \xi}{\sqrt{4a^2t}}\right) = \\
= -\frac{u_0}{\sqrt{\pi}}\int_{\frac{-l-\xi}{2a\sqrt{t}}}^{\frac{l-\xi}{2a\sqrt{t}}}e^{-\xi^2}d\xi = 
\Phi\left(\frac{l + t}{2a\sqrt{t}}\right) - \Phi\left(\frac{l - t}{2a\sqrt{t}}\right)
\end{multline}
#+END_EXPORT
* Задача 5.20
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, 0 < x < +\infty, t > 0, \\
u_x(0, t) = 0, t > 0, \\
u(x, 0) = \varphi(x) = e^{-\alpha x^2}, \alpha = const > 0.
\end{cases}
\end{equation}
#+END_EXPORT
** Решение
#+BEGIN_EXPORT latex
Продолжим $\varphi(x)$ чётным образом. Получим задачу на прямой:
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, -\infty < x < +\infty, t > 0, \\
u(x, 0) = e^{-\alpha x^2}.
\end{cases}
\end{equation}
Второе условие выполнено за счёт чётности $\varphi(x)$.
Пусть $U(x, t)$ - решение уравнения теплопроводности. Тогда функция
\begin{equation*}
U_2(x, t) = \frac1{\sqrt{1 + 4ct}}\exp\left(-\frac{cx^2}{1 + 4c^2t}\right)U\left(\frac{x}{1 + 4ct}, \frac{t}{1 + 4ct}\right)
\end{equation*}
также его решение. Положим $U(x, t) \equiv 1$ и подставим $U_2(x, t)$ в начальное условие:
\begin{equation*}
U_2(x, 0) = e^{-cx^2} = e^{-\alpha x^2} \Rightarrow c = \alpha.
\end{equation*}
Отсюда находим вид решения:
\begin{equation}
u(x, t) = \frac1{\sqrt{1 + 4\alpha t}}\exp\left(-\frac{\alpha x^2}{1 + 4\alpha^2t}\right)
\end{equation}
#+END_EXPORT
