#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+OPTIONS: toc:nil
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+LATEX_HEADER:\def\zall{\setcounter{lem}{0}\setcounter{cnsqnc}{0}\setcounter{th}{0}\setcounter{Cmt}{0}\setcounter{equation}{0}}

#+LATEX_HEADER:\newcounter{lem}\setcounter{lem}{0}
#+LATEX_HEADER:\def\lm{\par\smallskip\refstepcounter{lem}\textbf{\arabic{lem}}}
#+LATEX_HEADER:\newtheorem*{Lemma}{Лемма \lm}

#+LATEX_HEADER:\newcounter{th}\setcounter{th}{0}
#+LATEX_HEADER:\def\th{\par\smallskip\refstepcounter{th}\textbf{\arabic{th}}}
#+LATEX_HEADER:\newtheorem*{Theorem}{Теорема \th}

#+LATEX_HEADER:\newcounter{cnsqnc}\setcounter{cnsqnc}{0}
#+LATEX_HEADER:\def\cnsqnc{\par\smallskip\refstepcounter{cnsqnc}\textbf{\arabic{cnsqnc}}}
#+LATEX_HEADER:\newtheorem*{Consequence}{Следствие \cnsqnc}

#+LATEX_HEADER:\newcounter{Cmt}\setcounter{Cmt}{0}
#+LATEX_HEADER:\def\cmt{\par\smallskip\refstepcounter{Cmt}\textbf{\arabic{Cmt}}}
#+LATEX_HEADER:\newtheorem*{Note}{Замечание \cmt}

#+LATEX_HEADER:\renewcommand{\div}{\operatorname{div}}
#+LATEX_HEADER:\newcommand{\rot}{\operatorname{rot}}
#+LATEX_HEADER:\newcommand{\grad}{\operatorname{grad}}

\zall

Захаров, Дмитриев, Орлик "Уравнения математической физики".
6 вопросов, 3 теории, 3 задачи

* Семинар 1
\zall
** Уравнения в частных производных второго порядка
 #+BEGIN_EXPORT latex
 Это уравнения вида
 \begin{equation}
 a_{11}(x, y)u_{xx} + 2a_{12}(x, y)u_{xy} + a_{22}u_{yy} + f(x, y, u, u_x, u_y) = 0
 \end{equation}
 #+END_EXPORT
 Делаем замену
 #+BEGIN_EXPORT latex
 \begin{equation*}
 \begin{cases}
 u(x, y) = v(\xi, \eta), \\
 \xi = \xi(x, y), \\
 \eta = \eta(x, y).
 \end{cases}
 \end{equation*}
 #+END_EXPORT
 Тогда уравнение приводится к виду
 #+BEGIN_EXPORT latex
 \begin{equation*}
 \overline{a_{11}}v_{\xi\xi} + 2\overline{a_{12}}v_{\xi\eta} + \overline{a_{22}}v_{\eta\eta} + f = 0
 \end{equation*}
 #+END_EXPORT
 Характеристическое уравнение:
 #+BEGIN_EXPORT latex
 \begin{equation}
 a_{11}(dy)^2 - 2a_{12}dxdy + a_{22}(dx)^2 = 0
 \end{equation}
 Дискриминант:
 \begin{equation*}
 D = (a_{12})^2 - a_{11}a_{22}
 \end{equation*}
 #+END_EXPORT
 D > 0 - гиперболический тип, D < 0 - эллиптический, D = 0 - параболический.
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_{xx} = v_{\xi\xi}\xi_x^2 + 2v_{\xi\eta}\xi_x\eta_x + v_{\eta\eta}\eta_x^2 + v_{\xi}\xi_{xx} + v_{\eta}\eta_{xx}, \\
 u_{yy} = v_{\xi\xi}\xi_y^2 + 2v_{\xi\eta}\xi_y\eta_y + v_{\eta\eta}\eta_y^2 + v_{\xi}\xi_{yy} + v_{\eta}\eta_{yy}, \\
 u_{xy} = v_{\xi\xi}\xi_x\xi_y + v_{\xi\eta}(\xi_x\eta_y + \xi_y\eta_x) + v_{\eta\eta}\eta_x\eta_y
 + v_{\xi}\xi_{xy} + v_{\eta}\eta_{xy}
 \end{cases}
 \end{equation}
 \begin{equation*}
 \begin{cases}
 \alpha = \xi + \eta, \\
 \beta = \xi - \eta.
 \end{cases}
 \end{equation*}
 #+END_EXPORT
** Задача 6
 #+BEGIN_EXPORT latex
 \begin{equation}
 u_{xx} + yu_{yy} = 0
 \end{equation}
 Характеристическое уравнение:
 \begin{equation}
 (dy)^2 + y(dx)^2 = 0
 \end{equation}
 #+END_EXPORT
 Первый случай:
 $y < 0 \Rightarrow D = -y > 0$, откуда уравнение гиперболического типа.
 #+BEGIN_EXPORT latex
 \begin{equation*}
 \frac{dy}{dx} = \pm\sqrt{-y} \Rightarrow \frac{dy}{\sqrt{-y}} = dx
 \end{equation*}
 \begin{equation*}
 \int{\frac{dy}{\sqrt{-y}}} = -\int{(-y)^{-\frac12}}d(-y) = -2\sqrt{-y}
 \end{equation*}
 Откуда
 \begin{equation*}
 -2\sqrt{-y} = x + C
 \end{equation*}
 И, соответственно
 \begin{equation*}
 \begin{cases}
 \xi = x + 2\sqrt{-y}, \\
 \eta = -x + 2\sqrt{-y}.
 \end{cases}
 \end{equation*}
 Найдём $u_{xx}$ и $u_{yy}$:
 \begin{equation*}
 \begin{cases}
 \xi_{yy} = \frac12\frac{-1}{(-y)^{\frac32}}, \\
 \eta_{yy} = \frac12\frac{-1}{(-y)^{\frac32}}.
 \end{cases}
 \end{equation*}
 \begin{equation*}
 \begin{cases}
 u_{xx} = v_{\xi\xi}*1^2 + 2v_{\xi\eta}*1*(-1) + v_{\eta\eta}*1 + v_{\xi}\frac12\frac{-1}{(-y)^{\frac32}}
 + v_{\eta}\frac12\frac{-1}{(-y)^{\frac32}}, \\
 u_{yy} = -\frac1yv_{\xi\xi} + 2v_{\xi\eta}\left(-\frac1y\right) + v_{\eta\eta}\left(-\frac1y\right)
 + v_{\xi} + v_{\eta}.
 \end{cases}
 \end{equation*}
 Подставляя найденные значения в исходное уравнение, получаем:
 \begin{equation}
 2v_{\xi\eta} + \frac1{\xi + \eta}(v_{\xi} + v_{\eta}) = 0
 \end{equation}
 #+END_EXPORT
 Второй случай: $y > 0 \Rightarrow D = -y < 0 \Rightarrow \frac{dy}{dx} = \pm i\sqrt{y}$,
 т. е. уравнение эллиптического типа.
 #+BEGIN_EXPORT latex
 \begin{equation*}
 \frac{dy}{\sqrt{y}} = \pm idx \Rightarrow 2\sqrt{y} = \pm ix + C
 \end{equation*}
 Откуда
 \begin{equation*}
 \begin{cases}
 \xi = x, \\
 \eta = 2\sqrt{y}, \\
 \xi_x = 1, \\
 \eta_y = \frac1{\sqrt{y}}
 \eta_{yy} = -\frac12\frac1{y^{\frac32}}.
 \end{cases}
 \end{equation*}
 Подставляя вторые производные в исходное уравнение, получаем первую каноническую форму:
 \begin{equation}
 v_{\xi\xi} + y\left(v_{\eta\eta}\frac1y + \eta_n\left(-\frac12\right)\frac1{y^{\frac32}}\right) = 0.
 \end{equation}
 #+END_EXPORT
 Третий случай: $y = 0$ - параболический вид. Выберем $\xi$ и $\eta$:
 #+BEGIN_EXPORT latex
 \begin{equation*}
 \begin{cases}
 \xi = y, \\
 \eta = x, \\
 \xi_y = 1, \\
 \eta_x = 1.
 \end{cases}
 \end{equation*}
 Подставив в исходное уравнение, получим первую каноническую форму:
 \begin{equation}
 v_{\eta\eta} = 0.
 \end{equation}
 #+END_EXPORT
** Задача 6.10
 #+BEGIN_EXPORT latex
 \begin{equation}
 y^2u_{xx} - x^2u_{yy} = 0.
 \end{equation}
 Характеристическое уравнение:
 \begin{equation}
 y^2(dy)^2 - x^2(dx)^2 = 0 \Rightarrow ydx = \pm xdx \Rightarrow D = x^2y^2
 \end{equation}
 Если $x \neq 0$ и $y \neq 0$, то получим $x^2 + y^2 = C$, откуда
 \begin{equation}
 \begin{cases}
 \xi = y^2 + x^2, \\
 \eta = y^2 - x^2,
 \end{cases}
 \end{equation}
 что даёт
 \begin{equation}
 \begin{cases}
 \alpha = y^2, \\
 \beta = x^2.
 \end{cases}
 \end{equation}
 После замены получим:
 \begin{equation}
 y^2(v_{\beta\beta}*4x^2 + 2v_{\beta}) - x^2(v_{\alpha\alpha}*4y^2 + 2v_{\alpha}) = 0
 \end{equation}
 Откуда
 \begin{equation}
 v_{\beta}2y^2 - 2v_{\alpha}x^2 = 0
 \end{equation}
 Случай y = 0:
 \begin{equation}
 y = x = 0, u_{yy} = u_{xx} = 0, v_{\beta\beta} - v_{\alpha\alpha} + \frac{v_{\beta}}{2\alpha} + \frac{v_{\alpha}}{2\alpha} = 0
 \end{equation}
 #+END_EXPORT
** Задача 15
 #+BEGIN_EXPORT latex
 \begin{equation}
 x^2u_{xx} + 2xyu_{xy} + y^2u_{yy} = 0.
 \end{equation}
 Характеристическое уравнение:
 \begin{equation}
 x^2(dy^2) - 2xydxdy + y^2(dx)^2 = (xdy - ydx)^2 = 0
 \end{equation}
 Тогда $xdy = ydx \Rightarrow \frac{y}x = C$, откуда
 \begin{equation}
 \begin{cases}
 \xi = \frac{y}x, \\
 \eta = x, \\
 \xi_x = -\frac{y}{x^2}, \\
 \xi_{xx} = \frac{2y}{x^3}, \\
 \xi_{yy} = \frac1x, \\
 \xi_{xy} = -\frac1{x^2}, \\
 \eta_x = 1.
 \end{cases}
 \end{equation}
 Подставив это в (1), получим:
 \begin{equation}
 x^2\left(v_{\xi\xi}\left(\frac{2y}{x^3}\right)^2 - 2v_{\xi\eta}\frac{y}{x^2} + v_{\eta\eta} + v_{\eta}\frac{2y}{x^3}\right) +
 2xy\left(v_{\xi\xi}\frac1x\left(-\frac{y}x^2\right) + v_{\xi\eta}\frac1x + v_{\eta}\left(-\frac1{x^2}\right)\right) +
 y^2v_{\xi\xi}\frac1{x^2} = 0
 \end{equation}
 После преобразований останется:
 \begin{equation}
 v_{\eta\eta} = 0
 \end{equation}
 #+END_EXPORT
** Задача 24
 #+BEGIN_EXPORT latex
 \begin{equation}
 u_{xx} - 2u_{xy} + u_{yy} + 6u_x - 2u_y + u = 0.
 \end{equation}
 Характеристическое уравнение
 \begin{equation}
 (dy)^2 + 2dxdy + (dy)^2 = 0
 \end{equation}
 Дискриминант равен нулю $\Rightarrow$ уравнение параболического типа.
 \begin{equation}
 \begin{cases}
 \xi = y + x, \\
 \eta = x, \\
 \xi_x = 1, \\
 \xi_y = 1, \\
 \eta_x = 1, \\
 \end{cases}
 \end{equation}

 После подстановки:
 \begin{equation}
 v_{\xi\xi} + 2v_{\xi\eta} + v_{\eta\eta} - 2(v_{\xi\xi} + v_{\xi\eta}) + v_{\xi\xi} + 6u_{\xi} + 6u_{\eta}
 - 2u_{\xi} + u = 0.
 \end{equation}
 Откуда
 \begin{equation}
 u_{\eta\eta} + 4u_{\xi} + 6u_{\eta} + u = 0.
 \end{equation}
 #+END_EXPORT
 Д. з.: 1.11, 1.14, 1.8, 1.19, 1.23
 Начало в 12:15
* Семинар 2
\zall
** Уравнение теплопроводности
 #+BEGIN_EXPORT latex
 \begin{equation}
 u_t = a^2u_{xx} - b(u - u_{avg}) + f(x, t), 0 < x < C
 \end{equation}
 А также граничные/краевые условия.

 Первого рода:
 \begin{equation}
 u(x, 0) = \varphi(x)
 \end{equation}
 Второго рода:
 \begin{equation}
 u_x(0, t) = \nu_1(t)
 \end{equation}
 #+END_EXPORT
** Задача 2.5
 #+BEGIN_EXPORT latex
 \begin{equation}
 a^2 = 1, u_t = u_{xx}.
 \end{equation}
 $U(x, t)$ - решение.
 $U_1(x, t) = U(x - c, t)$ - решение?
 $$U_{1t}(x, t) = U_t(x - c, t), U_{1xx} = U_{xx}(x - c, t)$$
 Т. е. решение.
 $$U_2(x, t) = U(x, t - c)$$
 $$U_{2t}(x, t) = U_t(x, t - c), U_{1xx} = U_{xx}(x, t - c)$$
 Т. е. решение.
 $$U_3(x, t) = U(cx, c^2t)$$
 $$U_{3t}(x, t) = U_t(cx, c^2t)\cdot c^2$$
 $$U_{3xx}(x, t) = U_{xx}(cx, c^2t)\cdot c^2$$
 Т. е. решение.
 $$U_4(x, t) = e^{-cx + c^2t}U(x - 2ct, t)$$
 $$U_{4t}(x, t) = e^{-cx+c^2t}c^2U(x - 2ct, t) + e^{-cx + c^2t}(U_x(x - 2ct, t)(-2c) + U_t(x - 2ct, t))$$
 $$U_{4xx}(x, t) = e^{-cx + c^2t}(-c)^2U(x - 2ct, t) + e^{-cx + cx^2}(-c)U_x(x - 2ct, t) + e^{-cx + cx^2}U_{xx}(x - 2ct, t)$$
 #+END_EXPORT
** Задача 2.10
 #+BEGIN_EXPORT latex
 \begin{equation*}
 0 \leq l \leq x, u_1 = \text{const}, u_2 = \text{const}
 \end{equation*}
 #+END_EXPORT
 Задача:
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, \\
 u(0, t) = u_1, \\
 u(l, t) = u_2, \\
 u(x, 0) = u_0x.
 \end{cases}
 \end{equation}
 #+END_EXPORT
** Задача 2.11
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx} - b(u - u_{out}), \\
 u_x(0, t) = 0, \\
 u(l, t) = u_{out}, \\
 u(x, 0) = u_0.
 \end{cases}
 \end{equation}
 #+END_EXPORT
** Задача 2.12
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, \\
 u_x(0, t) = -\frac{Q}{kS}, \\
 u_x(l, t) = -\frac{Q}{kS}, \\
 u(x, 0) = 0.
 \end{cases}
 \end{equation}
 #+END_EXPORT
** Задача 2.17(2)
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, \\
 u(0, t) = \mu_1(t), \\
 u(l, t) = \mu_2(t), \\
 u(x, 0) = \varphi(x).
 \end{cases}
 \end{equation}
 Ищем решение в виде:
 $$u(x, t) = U(x, t) + v(x, t)$$
 где $U(x, t) = a(t)x + b(t)$. Подставив в (33), получим:
 \begin{equation}
 \begin{cases}
 b(t) = \mu_1, \\
 a(t)l + b(t) = \mu_2.
 \end{cases}
 \end{equation}
 Откуда $a(t) = \frac{\mu_1 - \mu_2}l$.

 Теперь рассмотрим другие краевые условия:
 \begin{equation}
 \begin{cases}
 u(0, t) = \mu_1, \\
 u_x(l, t) = \nu_2.
 \end{cases}
 \end{equation}
 Воспользуемся той же заменой:
 \begin{equation}
 \begin{cases}
 b(t) = \mu_1, \\
 a(t) = \nu_2.
 \end{cases}
 \end{equation}
 Третий вариант:
 \begin{equation}
 \begin{cases}
 u_x(0, t) = \nu_1, \\
 u_x(l, t) = \nu_2.
 \end{cases}
 \end{equation}
 Ищем $U(x, t)$ в виде $U(x, t) = a(t)x^2 + b(t)x$:
 \begin{equation}
 \begin{cases}
 b(t) = \nu_1, \\
 2Ca(t) = b(t) = \nu_2.
 \end{cases}
 \end{equation}
 Откуда $a(t) = \frac{\nu_2 - \nu_1}{2C}$.
 #+END_EXPORT
** Задача 3.1
 Решить задачу
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, 0 < x < l, t > 0, \\
 u(0, t) = 0, u(l, t) = 0, t > 0, \\
 u(x, 0) = \varphi(x), 0 \leq x \leq l.
 \end{cases}
 \end{equation}
 Ищем $u(x, t)$ в виде $u(x, t) = X(x)T(t)$. Тогда:
 \begin{equation}
 XT' = a^2X''T \Rightarrow \frac{X''}X = \frac{T'}{a^2T} = -\lambda.
 \end{equation}
 Получили два уравнения
 \begin{equation}
 \begin{cases}
 X'' + \lambda X = 0, X(0) = X(l) = 0, \\
 T' + \lambda a^2T = 0.
 \end{cases}
 \end{equation}
 Характеристическое уравнение первой задачи:
 \begin{equation}
 k^2 + \lambda = 0.
 \end{equation}
 Возможны три случая:

 1. $\lambda > 0 \Rightarrow X = C_1\cos\sqrt{\lambda}x + C_2\sin\sqrt{\lambda}x, C_1 = 0, C_2\sin\sqrt{\lambda}l = 0 \Rightarrow \lambda = \left(\frac{\pi n}l\right)^2, n \in \mathbb{Z}$.
 Тогда $X_n = \sin\left(\frac{\pi n}l\right)^2x$.

 2. $\lambda = 0 \Rightarrow X'' = 0 \Rightarrow X = C_1x + C_2, C_2 = 0, C_1l = 0 \Rightarrow$ решений нет.

 3. $\lambda < 0 \Rightarrow k = \pm \sqrt{-\lambda} \Rightarrow X = C_1e^{\sqrt{-\lambda}x} + C_2e^{-\sqrt{-\lambda}}x, C_1 + C_2 = 0, C_1(e^{\sqrt{-\lambda}l} + e^{-\sqrt{-\lambda}l}) = 0 \Rightarrow C_1 = 0$ и решений нет.

 Решим теперь второе уравнение. Его решением будет $T(t) = Ce^{-\lambda a^2t} = Ce^{-\left(\frac{\pi n a}l\right)^2t}$.

 Общее решение будем искать в виде ряда
 $$u = \sum_{n = 1}^{\infty} C_ne^{-\left(\frac{\pi na}l\right)^2}\sin\frac{\pi n}lx.$$
 Для нахождения коэффициентов $C_n$ воспользуемся граничным условием:
 \begin{equation}
 u(x, 0) = \varphi(x) = \sum_{n = 1}^{\infty}C_n\cdot1\cdot\sin\frac{\pi n}lx\text{, где } C_n = \frac2l\int_{0}^l\varphi(\xi)\sin\frac{\pi n}l\xi d\xi
 \end{equation}
 Решим задачу (33) на отрезке $[0, \pi]$ с начальным условием $u(x, 0) = \sin 3x + 8\sin 5x$.
 В этих условиях
 $$\lambda_n = n^2, x_n = \sin nx, u = \sum_{n = 1}^{\infty}C_n\sin nxe^{-n^2a^2t}$$
 $$\sin 3x + 8\sin 5x = \sum_{n = 1}^{\infty}C_n\sin nx$$
 Получили решение:
 $$u = e^{-9a^2t}\sin3x + 8e^{-25a^2t^2}\sin 5x$$
 #+END_EXPORT
** Задача 3.2
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = \frac14u_{xx} + 1 - x, 0 \leq x \leq 1, t > 0, \\
 u(0, t) = t, \\
 u(1, t) = 0, \\
 u(x, 0) = 3\sin(2\pi x).
 \end{cases}
 \end{equation}
 Ищем решение в виде $u = U + v$, где $U = a(t)x + b(t)$. Тогда:
 \begin{equation}
 \begin{cases}
 b(t) = t, \\
 a(t) + b(t) = 0 \Rightarrow a(t) = -t.
 \end{cases}
 \end{equation}
 Получили что $U = -tx + t$. Запишем уравнение для $v$:
 \begin{equation}
 -x + 1 + v_t = \frac14v_{xx} + 1 - x, \\
 v(0, t) = 0, \\
 v(l, t) = 0, \\
 v(x, 0) = 3\sin(2\pi x).
 \end{equation}
 Из предыдущей задачи
 \begin{equation}
 v = \sum_{n = 1}^{\infty}C_ne^{-\frac14(\pi n)^2t}\sin(\pi nx).
 \end{equation}
 Подставим в начальное условие:
 \begin{equation}
 3\sin(2\pi x) = \sum_{n = 1}^{\infty}c_n\sin(\pi nx).
 \end{equation}
 Тогда $u = -tx + t + 3\sin(2\pi x)e^{-\pi^2 t}$.
 #+END_EXPORT
** Задача 3.3
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = 4u_{xx} + 2t, x \in (0, \pi), \\
 u(x, 0) = \frac{1 + \pi}{\pi}x - 1, \\
 u(0, t) = t^2 - 1, \\
 u(l, t) = t^2.
 \end{cases}
 \end{equation}
 Ищем $u$ в виде $u = U + v$, где $U = a(t)x + b(t)$. Тогда
 \begin{equation}
 \begin{cases}
 b(t) = t^2 - 1, \\
 a(t)\pi + t^2 - 1 = t^2 \Rightarrow a(t) = \frac1{\pi}.
 \end{cases}
 \end{equation}
 Подставив это в исходное уравнение, получм:
 \begin{equation}
 \begin{cases}
 v_t = 4v_{xx}, \\
 v(0, t) = 0, \\
 v(\pi, t) = 0, \\
 v(x, 0) = x.
 \end{cases}
 \end{equation}
 Собственные значения $\lambda_n = n^2, X_n = \sin(nx), v = \sum_{n = 1}^{\infty}C_ne^{-4n^2t}\sin nx$.
 Подставляя в начальное условие, получим:
 $$v(x, 0) = x = \sum_{n = 1}^{\infty}C_n\sin (nx)$$
 \begin{equation}
 C_n = \frac2{\pi}\int_0^{\pi}\xi\sin(n\xi)d\xi = \frac2{\pi}\left(-\frac1n\int_0^{\pi}\xi d(\cos\xi)\right) =
 -\frac2{\pi n}\left(\xi(\cos n\xi)\right)\bigg|_0^{\pi} - \int_0^{\pi}\cos(n\xi)d\xi = -\frac2n(-1)^n.
 \end{equation}
 Тогда
 \begin{equation}
 u = \frac{x}\pi + t^2 - 1 + \sum_{n = 1}^{\infty}\left(-\frac2n(-1)^n\right)e^{4n^2t}\sin(nx).
 \end{equation}
 #+END_EXPORT
 Д. з. 2.5, 13, 14, 15, 16, 18, 19, 3.3, 3.4

* Семинар 3
\zall
 Собственные значения и собственные функции ЗШЛ с разными краевыми условиями:\\
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{tabular}{ |c|c|c| }
 type    & $\lambda_n$                              & $X_n$ \\
 I - I   & $\left(\frac{\pi n}{l}\right)^2$         & $\sin\frac{\pi n}lx$ \\
 I - II  & $\left(\frac{\pi(2n + 1)}{2l}\right)^2$  & $\sin\frac{\pi(2n + 1)}{2l}$ \\
 II - I  & $\left(\frac{\pi(2n + 1)}{2l}\right)^2$  & $\cos\frac{\pi(2n + 1)}{2l}$ \\
 II - II & $\left(\frac{\pi n}l\right)^2$           & $\cos\frac{\pi n}lx$.
 \end{tabular}
 \end{equation}
 #+END_EXPORT
** Задача 3.5
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = u_{xx}, 0 < x < 1, t > 0, \\
 u_x(0, t) = u(l, t) = 0, \\
 u(x, 0) = x^2 - 1, 0 \leq x \leq 1.
 \end{cases}
 \end{equation}
 Ищем решение в виде $u(x, t) = X(x)T(t)$. Получим две задачи:
 \begin{equation}
 \frac{X''}X = \frac{T'}{T} = -\lambda
 \end{equation}
 Или
 \begin{equation}
 \begin{cases}
 X'' + \lambda X = 0, \\
 X'(0) = X(1) = 0, \\
 T' + \lambda T = 0.
 \end{cases}
 \end{equation}
 Собственные значения:
 \begin{equation}
 \lambda_n = \left(\frac{\pi(2n + 1)}{2l}\right)^2,
 \end{equation}
 \begin{equation}
 X_n = \cos\frac{\pi(2n + 1)}{2l}x
 \end{equation}
 Для $T_n$ получаем:
 \begin{equation}
 T = Ce^{-\lambda t}.
 \end{equation}
 Ищем общее решение в виде ряда:
 \begin{equation}
 u(x, t) = \sum_{n = 1}^{\infty}C_ne^{-\lambda_n t}\cos\frac{\pi(2n + 1)}{2l}x
 \end{equation}
 Чтобы найти $C_n$, разложим правую часть краевого условия в ряд Фурье:
 \begin{equation}
 x^2 - 1 = \sum_{n = 0}^{\infty}C_n\cos\frac{\pi(2n + 1)}{2l}x
 \end{equation}
 \begin{multline}
 C_n = \frac2l\int_0^l(x^2 - 1)\cos\frac{\pi(2n + 1)}{2l}xdx =
 \frac4{\pi(2n + 1)}\int_0^l(x^2 - 1)d\sin\frac{\pi(2n + 1)}{2l} = \\
 = \frac4{\pi(2n + 1)}\left((x^2 - 1)\sin\frac{\pi(2n + 1)}{2l}\bigg|_0^l -
 \int_0^l\sin\frac{\pi(2n + 1)}{2l}2xdx\right) = \\
 = \frac1{\pi^2}(2n + 1)^2\int_0^lxd\cos\frac{\pi(2n + 1)}2x =
 \frac{16}{\pi^2}\left(x\cos\frac{\pi(2n + 1)}{2l}\bigg|_0^l - \ldots\right)
 \end{multline}
 Откуда
 \begin{equation}
 u(x, t) = \sum_{n = 1}^{\infty}\frac{(-1)^n\cdot32}{\pi^3(2n + 1)^3}\exp\left\{-\left(\frac{\pi(2n + 1)}{2l}\right)^2\right\}
 \cos\frac{\pi(2n + 1)}{2l}x
 \end{equation}
 #+END_EXPORT
** Задача 3.6
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = u_{xx}, 0 < x < l, t > 0, \\
 u_x(0, t) = 1, \\
 u(l, t) = 0, \\
 u(x, 0) = 0.
 \end{cases}
 \end{equation}
 Ищем решение в виде $u(x, t) = U(x, t) + V(x, t)$, где $V(x, t) = A(t)x + B(t)$.
 Подставив в краевые условия, получим:
 \begin{equation}
 \begin{cases}
 A(t) = 1, \\
 l + B(t) = 0,
 \end{cases}
 \end{equation}
 т. е. $V = x - l$.

 Для $V(x, t)$ получаем однородную задачу:
 \begin{equation}
 \begin{cases}
 V_t = V_{xx}, \\
 V_x(0, t) = V(l, t) = 0, \\
 V(x, 0) = l - x.
 \end{cases}
 \end{equation}
 Собственные значения и собственные функции ЗШЛ:
 \begin{equation}
 \begin{cases}
 \lambda_n = \left(\frac{\pi(2n + 1)}{2l}\right)^2, \\
 X_n = \cos\frac{\pi(2n + 1)}{2l}.
 \end{cases}
 \end{equation}
 Тогда $V$ ищем в виде $V = \sum_{n = 0}^{\infty}C_ne^{-\lambda_nt}\cos\frac{\pi(2n + 1)}{2l}x$, где
 \begin{multline}
 C_n = \frac2l\int_0^l(l - x)\cos\frac{\pi(2n + 1)}{2l}xdx =
 \frac4{\pi(2n + 1)}\int_0^l(l - x)d\sin\frac{\pi(2n + 1)}{2l}x = \\
 = \frac4{\pi(2n + 1)}\left((l - x)\sin\frac{\pi(2n + 1)}{2l}x\bigg|_0^l +
 \int_0^l\sin\frac{\pi(2n + 1)}{2l}xdx\right) = \\
 = -\frac{8l}{\pi^2(4n + 1)^2}\cos\frac{\pi(2n + 1)}{2l}x\bigg|_0^l = \frac{2l}{\pi^2(2n + 1)^2}
 \end{multline}
 Откуда
 \begin{equation}
 u = x - l + \sum_{n = 0}^{\infty}\frac{8l}{\pi^2(2n + 1)^2}\exp\left\{-\left(\frac{\pi(2n + 1)}{2l}\right)^2t\right\}
 \cos\frac{\pi(2n + 1)}{2l}x
 \end{equation}
 #+END_EXPORT
** Задача 3.8
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, 0 < x < \pi, t > 0, \\
 u_x(0, t) = u(\pi, t) = 0, t > 0, \\
 u(x, 0) = \cos\left(\frac{3x}2\right), 0 \leq x \leq \pi.
 \end{cases}
 \end{equation}
 Собственные значения и собственные функции:
 \begin{equation}
 \begin{cases}
 \lambda_n = \left(\frac{2n + 1}{2}\right)^2, \\
 X_n = \cos\frac{2n + 1}2x.
 \end{cases}
 \end{equation}
 Ищем общее решение в виде
 \begin{equation}
 u = \sum_{n = 0}^{\infty}C_ne^{-\lambda_na^2t}\cos\frac{2n + 1}2x.
 \end{equation}
 $C_n$ находим с помощью разложения в ряд Фурье:
 \begin{equation}
 u(x, 0) = \sum_{n = 0}^{\infty}C_n\cos\frac{2n + 1}2x = \cos\frac{3x}2 \Rightarrow
 C_1 = 1, C_n = 0, n \neq 1.
 \end{equation}
 Получаем, что $u(x ,t) = e^{-\frac94}a^2t\cos\frac{3x}2$.
 #+END_EXPORT
** Задача next
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = \frac19u_{xx} + 1, \\
 u(0, t) = t, u_x(1, t) = 0, \\
 u(x, 0) = 2\sin\frac32\pi x.
 \end{cases}
 \end{equation}
 Ищем решение в виде $u = U + V$, где $U = A(t)x + B(t)$. Подставляя в граничные условия, получим:
 \begin{equation}
 B = t, \\
 A = 0.
 \end{equation}
 Для $V$ получаем задачу:
 \begin{equation}
 \begin{cases}
 v_t = \frac19v_{xx}, \\
 v(0, t) = v_x(1, t) = 0, \\
 v(x, 0) = 2\sin\frac32\pi x.
 \end{cases}
 \end{equation}
 Собственные значения и собственные функции ЗШЛ:
 \begin{equation}
 \lambda_n = \left(\frac{\pi(2n + 1)}2\right)^2, \\
 X_n = \sin\frac{\pi(2n + 1)}2x
 \end{equation}
 Ищем решение в виде
 \begin{equation}
 v(x, t) = \sum_{n = 0}^{\infty}C_ne^{-\lambda_n}\frac19t\sin\frac{\pi(2n + 1)}2x.
 \end{equation}
 Подставляя в начальное условие, получим:
 \begin{equation}
 v(x, 0) = \sum_{n = 0}^{\infty}C_n\sin\frac{\pi(2n + 1)}2x = 2\sin\frac32x
 \end{equation}
 Откуда
 \begin{equation}
 u(x, t) = t + 2\exp\left\{-\frac{\pi^2}4t\right\}\sin\frac32\pi x.
 \end{equation}
 #+END_EXPORT
** Задача next2
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = u_{xx} - u, \\
 u(0, t) = u(l, t) = 0, \\
 u(x, 0) = 1.
 \end{cases}
 \end{equation}
 Ищем решение в виде $u(x, t) = X(x)T(t)$:
 \begin{equation}
 XT' = X''T - XT \Rightarrow \frac{X''}X = \frac{T' + T}{T} = -\lambda.
 \end{equation}
 Получили две задачи:
 \begin{equation}
 \begin{cases}
 X'' + \lambda X = 0, \\
 T' + (\lambda + 1)T = 0.
 \end{cases}
 \end{equation}
 Собственные значения и собственные функции ЗШЛ:
 \begin{equation}
 \lambda_n = \left(\frac{\pi n}l\right)^2, \\
 X_n = \sin\frac{\pi n}l.
 \end{equation}
 Для $T$ получаем:
 \begin{equation}
 T(t) = Ce^{-(\lambda + 1)t}.
 \end{equation}
 Тогда общее решение ищется в виде:
 \begin{equation}
 u = \sum_{n = 1}^{\infty}C_ne^{-(\lambda + 1)t}\sin\frac{\pi n}lx
 \end{equation}
 Подставляя в начальное условие, находим $C_n$:
 \begin{equation}
 C_n = \frac2l\int_0^l\sin\frac{\pi n}lxdx = \frac2{\pi n}\cos\frac{\pi n}lx\bigg|_0^l = \frac2{\pi n}(1 - (-1)^n).
 \end{equation}
 Откуда для $u$:
 \begin{equation}
 u = \sum_{n = 1}^{\infty}\frac2{\pi n}(1 - (-1)^n)\exp\left\{-\left(\left(\frac{\pi n}l\right)^2 1\right)t\right\}\sin\frac{\pi n}lx
 \end{equation}
 #+END_EXPORT
** Задача 3.14
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, 0 < x < l, \\
 u_x(0, t) = 0, u_x(l, t) + hu(l, t) = 0, h > 0, \\
 u(x, 0) = \varphi(x).
 \end{cases}
 \end{equation}
 Ищем решение в виде $u(x, t) = X(x)T(t)$:
 \begin{equation}
 XT' = a^2X''T \Rightarrow \frac{X''}X = \frac{T'}{a^2T} = -\lambda
 \end{equation}
 Получили задачи:
 \begin{equation}
 \begin{cases}
 X'' + \lambda X = 0, \\
 T' + a^2\lambda T = 0.
 \end{cases}
 \end{equation}
 Решаем ЗШЛ:
 1. $\lambda > 0 \Rightarrow X = C_1\cos\sqrt{\lambda}x + C_2\sin\sqrt{\lambda}x$.
 Из граничных условий $C_2 = 0$ и $\tg\sqrt{\lambda}l = \frac{h}{\sqrt{\lambda}}$.
 Собственными значениями будут решения последнего уравнения, а собственными функциями -
 функции $X_n = \cos\sqrt{\lambda_n}x$
 Тогда общее решение имеет вид:
 \begin{equation}
 u(x, t) = \sum_{n = 0}^{\infty}C_ne^{-\lambda_na^2t}\cos\sqrt{\lambda_n}x
 \end{equation}
 \begin{equation}
 \varphi(x) = \sum_{n = 0}^{\infty}C_n\cos\sqrt{\lambda_n}x \Rightarrow C_n = \frac1{|X_n|^2}\int_0^l\varphi(\xi)\cos\sqrt{\lambda_n}\xi d\xi,
 \end{equation}
 где
 \begin{equation}
 |X_n|^2 = \int_0^l\cos^2\sqrt{\lambda_n}xdx
 \end{equation}
 #+END_EXPORT
** Задача 3.15
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 u_t = a^2u_{xx}, 0 < x < l, \\
 u_x(0, t) - hu(0, t) = 0, h > 0, \\
 u(l, t) = 0, \\
 u(x, 0) = \varphi(x).
 \end{cases}
 \end{equation}
 Ищем решение в виде $u = X(x)T(t)$, получаем уравнения:
 \begin{equation}
 \begin{cases}
 X'' + \lambda X = 0, X(l) = X'(0) - hX(0) = 0, \\
 T' + \lambda T = 0.
 \end{cases}
 \end{equation}
 В случае $\lambda > 0$:
 \begin{equation}
 X = C_1\cos\sqrt{\lambda}x + C_2\sin\sqrt{\lambda}x
 \end{equation}
 При подстановке граничных условий:
 \begin{equation}
 \begin{cases}
 C_2\sqrt{\lambda} - hC_1 = 0, \\
 C_1\cos\sqrt{\lambda}l + C_2\sin\sqrt{\lambda}l = 0.
 \end{cases}
 \end{equation}
 Откуда $\tg\sqrt{\lambda}l = -\frac{\sqrt{\lambda}}h$. $\lambda_n$ будут решениями этого
 уравнения, а собственные функции будут иметь вид: $X_n = \cos\sqrt{\lambda}x + \frac{h}{\sqrt{\lambda}}\sin\sqrt{\lambda}x$
 #+END_EXPORT

 Д. з. 3.7, 9, 10, 11, 12
* Семинар 4
\zall
ДЗ: 4.4, 4.6, 4.7, 4.8, 4.11
** Задача 4.5
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx} + f_0, 0 < x < l, t > 0, f_0 = \text{const}, \\
u(0, t) = u_x(l, t) = 0, t > 0, \\
u(x, 0) = 0, 0 \leq x \leq l.
\end{cases}
\end{equation}
Собственные значения и собственные функции соответствующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = \left(\frac{\pi(2n + 1)}{2l}\right)^2, \\
X_n = \sin\frac{\pi(2n + 1)}{2l}x
\end{cases}
\end{equation}
Ищем решение в виде
\begin{equation}
u(x, t) = \sum_{n = 0}u_n(t)\sin\sqrt{\lambda_n}x.
\end{equation}
\begin{equation}
f_n = \frac2l\int_0^lf_0\sin\frac{\pi(2n + 1)}{2l}xdx = -\frac{4f_0}{\pi(2n + 1)}\cos\frac{\pi(2n + 1)}{2l}x\bigg|_0^l =
\frac{4f_0}{\pi(2n + 1)}
\end{equation}
Получаем набор задач:
\begin{equation}
\begin{cases}
u_n' = -a^2\lambda_nu_n + f_n, \\
u_n(0) = 0.
\end{cases}
\end{equation}
Решением этой задачи Коши будет функция
\begin{equation}
u_n = \frac{f_n}{a^2\lambda_n}(1 - e^{-a^2\lambda_nt}).
\end{equation}
Тогда решение будет иметь вид:
\begin{equation}
u(x, t) \sum_{n = 0}^{\infty}\frac{16f_0l^2}{\pi^3(2n + 1)^3a^2}\left(1 - \exp\left\{-\left(\frac{\pi(2n + 1)a}{2l}\right)^2\right\}\right)\sin\frac{\pi(2n + 1)}{2l}x
\end{equation}
#+END_EXPORT
** Задача 4.9
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + 2, 0 < x < \frac{\pi}2, t > 0, \\
u(0, t) = 2t, u_x\left(\frac{\pi}2, t\right) = 0, t > 0, \\
u(x, 0) = \sin5x, 0 \leq x \leq \frac{\pi}2
\end{cases}
\end{equation}
Ищем решение в виде $u = U + v$, где $U = a(t)x + b(t)$. Подставляя в граничные условия, найдём,
что $a(t) = 0, b(t) = 2t$. Для $v$ получим задачу
\begin{equation}
\begin{cases}
v_t = v_{xx}, \\
v(0, t) = v_x\left(\frac{\pi}2, t\right) = 0, \\
v(x, 0) = \sin5x.
\end{cases}
\end{equation}
Собственные задачи и собственные функции соответствующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = (2n + 1)^2, \\
X_n = \sin(2n + 1)x.
\end{cases}
\end{equation}
Ищем решение в виде $v = \sum_{n = 0}^{\infty}C_ne^{-a^2\lambda_nt}\sin(2n + 1)x$. Получим, что
$C_2 = 1, C_n = 0, n \neq 2$, откуда
\begin{equation}
u(x, t) = 2t + e^{-25t}\sin5x.
\end{equation}
#+END_EXPORT
** Задача 4.10
Решить задачу
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + 2 + 2\sin5x, \\
u(0, t) = 2t, u_x\left(\frac{\pi}2, t\right) = 0, \\
u(x, 0) = 0, 0 \leq x \leq \frac{\pi}2
\end{cases}
\end{equation}
Собственные значения и собственные функции те же, задача после редукции примет вид:
\begin{equation}
\begin{cases}
v_t = v_{xx} + 2\sin5x, \\
v(0, t) = v_x(\frac{\pi}2, t) = 0, \\
v(x, 0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде
\begin{equation}
v = \sum_{n = 0}^{\infty}v_n(t)\sin(2n + 1)x.
\end{equation}
Получим систему
\begin{equation}
\begin{cases}
v_n'(t) = -\lambda_nv_n + f_n, \\
v_n(0) = 0.
\end{cases}
\end{equation}
$f_2 = 2, f_n = 0, n \neq 2 \Rightarrow v_n = 0, n \neq 2$. При $n = 2$:
\begin{equation}
\begin{cases}
v_2' = -25v_2 + 2, \\
v_2(0) = 0.
\end{cases}
\end{equation}
Откуда $v_2 = -\frac2{25}e^{-25t} + \frac2{25}$. Решение имеет вид:
\begin{equation}
u = 2t + \left(\frac2{25}e^{-25t} + \frac2{25}\right)\sin5x
\end{equation}
#+END_EXPORT
** Задача next
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, 0 < x < l, t > 0, \\
u(0, t) = At, t > 0 \\
u(l, t) = 0, t > 0 \\
u(x, 0) = 0, 0 \leq x \leq l.
\end{cases}
\end{equation}
Ищем решение в виде $u = U + v$, где $U = a(t)x + b(t)$. Подставляя в граничные условия, находим:
\begin{equation}
\begin{cases}
a(t)l + At = 0, \\
b(t) = At,
\end{cases}
\Rightarrow
\begin{cases}
a(t) = -\frac{A}lt, \\
b(t) = At.
\end{cases}
\end{equation}
Тогда $u = v + \frac{l - x}lAt$. После редукции задача приобретёт вид:
\begin{equation}
\begin{cases}
v_t = a^2v_{xx} - \frac{A(l - x)}l, \\
v(0, t) = v(l, t) = 0, \\
v(x, 0) = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = \left(\frac{\pi n}l\right)^2, \\
X_n = \sin\frac{\pi n}lx
\end{cases}
\end{equation}
Найдём $f_n$:
\begin{equation}
f_n = \frac2l\int_0^l\frac{A}l(x - l)\sin\frac{\pi n}lxdx = \ldots = -\frac{2A}{\pi n}.
\end{equation}
Ищем решение в виде
\begin{equation}
v(x, t) = \sum_{n = 0}^{\infty}v_n(t)\sin\frac{\pi n}lx
\end{equation}
Из этого получим систему:
\begin{equation}
\begin{cases}
v_n' = -a^2\lambda_nv_n + f_n, \\
v_n(0) = 0.
\end{cases}
\end{equation}
Решением этой задачи Коши будет функция $v_n = \frac{f_n}{a^2\lambda_n}(1 - e^{-a^2\lambda_nt})$.
Решение задачи (117) будет иметь в таком случае вид:
\begin{equation}
u(x, t) = -\frac{At}l(x - l) + \sum_{n = 1}^{\infty}-\frac{2Al^2}{\pi^3n^3d^2}\left(1 - \exp\left\{-a^2\ldots\right\}\right)\sin
\end{equation}
#+END_EXPORT
** Задача next2
Решить задачу
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + u + 2\sin2x\sin x, 0 < x < \frac{\pi}2, t > 0, \\
u_x(0, t) = u\left(\frac{\pi}2, t\right) = 0, \\
u(x, 0) = 0
\end{cases}
\end{equation}
$$2\sin2x\sin x = \cos x - \cos3x$$
Ищем решение в виде
\begin{equation}
u(x, t) = \sum_{n = 0}^{\infty}u_n(t)\cos(2n + 1)x,
\end{equation}
$$f_0 = 1, f_1 = -1, f_n = 0, n \notin \{0, 1\}$$
Получим систему
\begin{equation}
\begin{cases}
u'_n = -a^2\lambda_nu_n + u_n + f_n, \\
u_n(0) = 0.
\end{cases}
\end{equation}
При $n > 1 u_n = 0$.

$n = 0$:
\begin{equation}
\begin{cases}
u'_0 = -u_0 + u_0 + 1, \\
u_0(0) = 0
\end{cases} \Rightarrow u_0 = t.
\end{equation}
$n = 1$:
\begin{equation}
\begin{cases}
u'_1 = -9u_1 + u_1 - 1, \\
u_1(0) = 0
\end{cases} \Rightarrow u_1 = -\frac18e^{-8t} - \frac18.
\end{equation}
Тогда решение задачи (125) имеет вид
\begin{equation}
u(x, t) = t\cos x + \left(\frac18e^{-8t} - \frac18\right)\cos3x.
\end{equation}
#+END_EXPORT
* Семинар 5
\zall
** Задача 4.13
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + u, 0 < x < 1, t > 0, \\
u(0, t) = 0, u(l, t) = t, t > 0, \\
u(x, 0) = 0, 0 \leq x \leq 1
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u = U + v$. $U = a(t)x + b(t)$. Подставляя в начальные условия, получим:
\begin{equation}
a(t) = t, b(t) = 0.
\end{equation}
Получаем, что $u = tx + v$. Получаем задачу на $v$:
\begin{equation}
\begin{cases}
v_t + x = v_{xx} + v + tx, \\
v(0, t) = v(l, t) = 0, \\
v(x, 0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде $v = e^{bt}z$. Тогда:
\begin{equation}
be^{bt}z + e^{bt}z_t = e^{bt}z_{xx} + e^{bt}z + x(t - 1)
\end{equation}
Положим $b = 1$. Тогда
\begin{equation}
\begin{cases}
z_t = z_{xx} + x(t - 1)e^{-t}, \\
z(0, t) = z(l, t) = 0, \\
z(x, 0) = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции соответствующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = (\pi n)^2, \\
X_n = \sin\pi nx.
\end{cases}
\end{equation}
Ищем решение в виде
\begin{equation}
z = \sum_{n = 1}^{\infty}z_n\sin\pi nx.
\end{equation}
Разложим источник в ряд Фурье:
\begin{equation}
f_n = 2(t - 1)e^{-t}\int_0^1\xi\sin n\xi d\xi = \ldots = 2(t - 1)e^{-t}\frac{(-1)^{n + 1}}{\pi n}.
\end{equation}
Получаем систему задач Коши на $z_n$:
\begin{equation}
\begin{cases}
z_n' = -(\pi n)^2z_n + 2(t - 1)e^{-t}\frac{(-1)^{n + 1}}{\pi n}, \\
z_n(0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде $z_n = C(t)e^{-\pi^2n^2t}$. Тогда:
\begin{equation}
C' = 2(t - 1)\exp\{t(\pi^2n^2 - 1)\}
\end{equation}
\begin{equation}
C = \frac{2(-1)^{n + 1}}{\pi n}\int_0^t(\tau - 1)e^{(\pi n^2 - 1)\tau}d\tau = \ldots =
\frac{2(-1)^{n + 1}}{\pi n((\pi n)^2 - 1)}\left[e^{(\pi n)^2 - 1}\left(t - 1 - \frac1{\pi^2n^2 - 1}\right)\right]
= B_n(t)
\end{equation}
Тогда
\begin{equation}
u(x, t) = tx + e^t\left(\sum_{n = 1}^{\infty}B_n(t)e^{-\pi^2n^2t}\sin\pi nx\right)
\end{equation}
#+END_EXPORT
** Задача 4.15
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} - u, 0 < x < 1, t > 0 \\
u(0, t) = 0, u_x(1, t) = t, t > 0, \\
u(x, 0) = 0, 0 \leq x \leq 1.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u = U + v$, где $U = a(t)x + b(t)$. Подставляя в краевые условия, найдём:
\begin{equation}
\begin{cases}
a(t) = t, \\
b(t) = 0.
\end{cases}
\end{equation}
Тогда $u = tx + v$. Получаем задачу на $v$:
\begin{equation}
\begin{cases}
x + v_t = v_{xx} - v - tx, \\
v(0, t) = u_x(1, t) = 0, \\
v(x, 0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде $v = e^{bt}z$, где $b = -1$. Получаем задачу на $z$:
\begin{equation}
\begin{cases}
z_t = z_{xx} - x(t + 1)e^t, \\
z(0, t) = z_x(l, t) = 0, \\
z(x, 0) = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции соответствующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = \frac{(\pi(2n + 1))^2}4, \\
X_n = \sin\frac{\pi(2n + 1)}2x.
\end{cases}
\end{equation}
Раскладываем источник в ряд Фурье:
\begin{equation}
f_n = 2(t + 1)e^t\int_0^1x\sin\frac{\pi(2n + 1)}2xdx = \ldots = \frac{8(t + 1)e^t}{\pi^2(2n + 1)^2}(-1)^n.
\end{equation}
Подставляя всё в уравнение, получаем систему задач Коши:
\begin{equation}
\begin{cases}
z_n' = -\frac{\pi^2(2n + 1)^2}4z_n + \frac{8(t + 1)e^t}{\pi^2(2n + 1)^2}(-1)^n, \\
z_n(0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде:
\begin{equation}
z_n = C(t)\exp\left\{-\frac{\pi^2(2n + 1)^2t}4\right\}.
\end{equation}
Тогда для $C(t)$ находим
\begin{equation}
C' = \frac{8(t + 1)}{\pi^2(2n + 1)^2}(-1)^n\exp\left\{1 + \frac{\pi^2(2n + 1)^2}4\right\}
\end{equation}
Откуда для $C(t)$:
\begin{equation}
C(t) = \frac{8(-1)^n}{\pi^2(2n + 1)^2}\frac4{4 + \pi^2(2n + 1)^2}\left[e^{kt}\left(t + 1 - \frac4{4 + \pi^2(2n + 1)^2}\right) - 1 + \frac4{4 + \pi^2(2n + 1)^2}\right] + C_0
\end{equation}
Подставляя в краевые условия, находим, что $C_0 = 0$:
Тогда для $u(x, t)$:
\begin{equation}
u(x, t) = tx + e^{-t}\left(\sum_{n = 0}^{\infty}C_n\exp\left\{-\left(1 + \frac{\pi^2(2n + 1)^2}4\right)t\right\}\sin\frac{2n + 1}2x\right)
\end{equation}
#+END_EXPORT
** Задача 4.17
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + u + \cos 2x\sin x, 0 < x < \frac{\pi}2, t > 0, \\
u(0, t) = u_x\left(\frac{\pi}2, t\right) = 0, t > 0, \\
u(x, 0) = 0, 0 \leq x \leq \frac{\pi}2.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u = e^tz$. Тогда для $z$ получаем задачу:
\begin{equation}
\begin{cases}
z_t = z_{xx} + \frac12(\sin 3x - \sin x)e^{-t}, \\
z(0, t) = z_x\left(\frac{\pi}2, t\right) = 0, \\
z(x, 0) = 0.
\end{cases}
\end{equation}
Источник уже является разложением в ряд Фурье, так что получаем задачи:
\begin{equation}
\begin{cases}
z_n' = -(2n + 1)^2z_n + f_n, \\
z_n(0) = 0.
\end{cases}
\end{equation}
При $n > 1 f_n = 0 \Rightarrow z_n = 0$.

При $n = 0$:
\begin{equation}
\begin{cases}
z_0' = -z_0 - \frac12e^{-t}, \\
z_0(0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде $z = C(t)e^{-t}$. Тогда:
\begin{equation}
C'(t) = -\frac12 \Rightarrow C(t) = -\frac12t + C_1 = -\frac{t}2
\end{equation}
Получили, что $z_0 = -\frac12te^{-t}$.

При $n = 1$:
\begin{equation}
\begin{cases}
z_1' = -9z_1 + \frac12e^{-t}, \\
z_1(0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде $z_1 = C(t)e^{-9t}$. Тогда $C' = \frac12e^{8t} \Rightarrow C(t) = \frac1{16}e^{8t} + C_1$.
Подставляя краевые условия, находим, что $C = \frac1{16}(e^{8t} - 1)$.

Итого для $u(x, t)$ получаем:
\begin{equation}
u(x, t) = e^t\left(-\frac12 + e^{-t}\right)\sin x + \left(\frac1{16}(e^{8t} - 1)e^{-9t}\sin 3x\right)
\end{equation}
#+END_EXPORT
** Задача 4.19
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + x^2 - 2t + \cos 3x, 0 < x < \pi, t > 0, \\
u_x(0, t) = 1, u_x(\pi, t) = 2\pi t + 1, t > 0, \\
u(x, 0) = x, 0 \leq x \leq \pi.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Решение ищем в виде $u = U + v$, где $U = a(t)x^2 + b(t)x$. Получим, что:
\begin{equation}
\begin{cases}
a(t) = t, \\
b(t) = 1,
\end{cases}
\end{equation}
поэтому $u = tx^2 + x + v$. После подстановки получим задачу на $v$:
\begin{equation}
\begin{cases}
v_t + x^2 = v_{xx} + 2t + x^2 - 2t + \cos 3x, \\
v_x(0, t) = v_x(\pi, t) = 0, \\
v(x, 0) = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции соответсвующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = n^2, \\
X_n = \cos nx.
\end{cases}
\end{equation}
Ищем решение в виде
\begin{equation}
v(x, t) = \sum_{n = 0}^{\infty}v_n(t)\cos nx.
\end{equation}
Получим систему задач Коши:
\begin{equation}
\begin{cases}
v_n' = -n^2v_n + f_n, \\
v_n(0) = 0.
\end{cases}
\end{equation}
При $n \neq 3 v_n \equiv 0$. При $n = 3$ решением будет функция $v_3 = Ce^{-9t} + \frac19$.
Подставляя начальные условия, получаем, что $v_3 = \frac19(1 - e^{-9t})$. Итого получим:
\begin{equation}
u(x, t) = tx^2 + x + \frac19(1 - e^{-9t})\cos 3x.
\end{equation}
#+END_EXPORT
** Задача 4.21
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + u - x + 2\sin2x\cos x, 0 < x < \frac{\pi}2, t > 0, \\
u(0, t) = 0, u_x\left(\frac{\pi}2, t\right) = 1, t > 0, \\
u(x, 0) = x, 0 \leq x \leq \frac{\pi}2.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u = U + v$, $U = a(t)x + b(t)$, получим, что $U = x \Rightarrow u = v + x$.
Для $v$ получаем задачу:
\begin{equation}
\begin{cases}
v_t = v_{xx} + v + \sin3x + \sin x, \\
v(0, t) = v_x\left(0, \frac{\pi}2\right) = 0, t > 0, \\
v(x, 0) = 0, 0 \leq x \leq \frac{\pi}2.
\end{cases}
\end{equation}
Ищем решение в виде $v = e^tz$, получим задачу на $z$:
\begin{equation}
\begin{cases}
z_t = z_{xx} + (\sin 3x + \sin x)e^{-t}, \\
z(0, t) = z_x\left(\frac{\pi}2, t\right) = 0, \\
z(x, 0) = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции соответствующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = (2n + 1)^2, \\
X_n = \sin(2n + 1)x.
\end{cases}
\end{equation}
Раскладывая $z$ и источник в ряды Фурье, получаем задачи для $z_n$:
\begin{equation}
\begin{cases}
z_0' = -z_0 + e^{-t}, \\
z_0(0) = 0,
\end{cases}
\end{equation}
\begin{equation}
\begin{cases}
z_1' = -9z_1 + e^{-t}, \\
z_1(0) = 0.
\end{cases}
\end{equation}
Решениями этих задач будут функции $z_0 = te^{-t}$ и $z_1 = \frac18(e^{-t} - e^{-9t})$. Итого
получаем:
\begin{equation}
u(x, t) = x + e^t\left[te^{-t}\sin x + \frac18(e^{8t} + 1)\sin 3x\right]
\end{equation}
#+END_EXPORT
** Задача 4.24
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} - 2u_x + u + e^x\sin x - t, 0 < x < \pi, t > 0, \\
u(0, t) = u(\pi, t) = 1 + t, t > 0, \\
u(x, 0) = 1 + e^x\sin2x, 0 \leq x \leq \pi.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Решение ищем в виде $u = U + v$, где $U = a(t)x + b(t)$. Тогда
\begin{equation}
\begin{cases}
a(t) = 0, \\
b(t) = 1 + t.
\end{cases}
\end{equation}
Получили, что $u = 1 + t + v$. Это приводит к задаче для $v$:
\begin{equation}
\begin{cases}
v_t = v_{xx} - 2v_x + v + e^x\sin x, \\
v(0, t) = v(\pi, t) = 0, \\
v(x, 0) = e^x\sin2x
\end{cases}
\end{equation}
Ищем решение в виде $v = e^{\alpha x + \beta t}z$. Подставим в задачу:
\begin{equation}
\beta e^{\alpha x + \beta t}z + e^{\alpha x + \beta t}z = \alpha^2e^{\alpha x + \beta t}z + 2\alpha e^{\alpha x + \beta z}z_x + e^{\alpha x + \beta z}z_{xx}
- 2\alpha e^{\alpha x + \beta z}z - 2e^{\alpha x + \beta z}z_x + e^x\sin x + e^{\alpha x + \beta t}z
\end{equation}
Получаем систему:
\begin{equation}
\begin{cases}
\beta = \alpha^2 - 2\alpha + 1,  \\
2\alpha - 2 = 0.
\end{cases}
\end{equation}
Откуда
\begin{equation}
\begin{cases}
\alpha = 1, \\
\beta = 0.
\end{cases}
\end{equation}
Получим задачу на $z$:
\begin{equation}
\begin{cases}
z_t = z_{xx} + \sin x, \\
z(0, t) = z(\pi, t) = 0, \\
z(x, 0) = \sin 2x.
\end{cases}
\end{equation}
Собственные значения и собственные функции соответствующей ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = n^2, \\
X_n = \sin nx.
\end{cases}
\end{equation}
Если искать решение в виде ряда Фурье, получим задачи:
\begin{equation}
\begin{cases}
z_1' = -z_1 + 1, \\
z_1(0) = 0,
\end{cases}
\end{equation}
и
\begin{equation}
\begin{cases}
z_2' = -4z_2, \\
z_2(0) = 1,
\end{cases}
\end{equation}
решениями которых будут функции $z_1 = 1 - e^{-t}$ и $z_2 = e^{-4t}$ соответсвенно. Итого для $u(x, t)$:
\begin{equation}
u(x, t) = 1 + t + e^x((1 - e^{-t})\sin x + e^{-4t}\sin 2x)
\end{equation}
#+END_EXPORT
ДЗ: 4.14, 4.16, 4.18, 4.20, 4.22, 4.23
* Семинар 6
\zall
ДЗ: 5.2, 5.3, 5.5, 5.6, 5.7, 5.9, 5.15, 5.19, 5.20
** Задача 5.4
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = u_{xx} + e^{-t}\cos x, -\infty < x < +\infty, t > 0, \\
u(x, 0) = \cos x, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u(x, t) = F(t)\cos x$. Подставим в условие:
\begin{equation}
\begin{cases}
F'\cos x = -F\cos x + e^{-t}\cos x, \\
F(0) = 1
\end{cases}
\end{equation}
или
\begin{equation}
\begin{cases}
F' = -F + e^{-t}, \\
F(0) = 1.
\end{cases}
\end{equation}
Решение задачи ищем в виде $F = Ce^{-t}$, получаем, что
\begin{equation}
F(t) = t + 1
\end{equation}
Тогда для $u(x, t)$:
\begin{equation}
u(x, t) = (t + 1)e^{-t}\cos x.
\end{equation}
#+END_EXPORT
** Задача 2
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = 4u_{xx}, \\
u(x, 0) = 2\sin 3x.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u(x, t) = F(t)\sin 3x$. Подставляя в условие, находим, что $F(t) = 2e^{-36t}$ и что
\begin{equation}
u(x, t) = 2e^{-36t}\sin 3x.
\end{equation}
#+END_EXPORT
** Задача 5.8
#+BEGIN_EXPORT latex
\begin{equation}
u_t = a^2u_{xx},
u(x, t) - \text{ решение}.
\end{equation}
Тогда $U(x, t) = \frac1{\sqrt{1 + 4at^2ct}}e^{-\frac{cx^2}{1 + 4a^2ct}}U\left(\frac{x}{1 + 4a^2ct}, \frac{t}{1 + 4a^2ct}\right)$ - тоже решение.
\begin{equation}
\begin{cases}
4u_t = u_{xx}, -\infty < x < +\infty, t > 0, \\
u(x, 0) = e^{2x - x^2}, -\infty < x < +\infty.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Подставим в начальные условия решение в виде, выписанном выше:
\begin{equation}
u(x, 0) = e^{2x - x^2} = e^{-cx^2}u(x, 0) \Rightarrow c = 1.
\end{equation}
$\ldots$
#+END_EXPORT
** Задача 5.10
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, -\infty < x < +\infty, t > 0, \\
u(x, 0) = \varphi(x), x \in \mathbb{R}, \\
|u(x, t)| < C
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде
\begin{equation}
u(x, t) = X(x)T(t).
\end{equation}
Тогда
\begin{equation}
\frac{T'}{a^2T} = \frac{X''}{X} = -\lambda.
\end{equation}
Получаем две задачи:
\begin{equation}
\begin{cases}
X'' + \lambda X = 0, \\
T' + a^2\lambda T = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции:
\begin{equation}
\begin{cases}
\lambda = k^2, \\
X = e^{ikx}, T = e^{-k^2a^2t}, k \in \mathbb{R}
\end{cases}
\end{equation}
Ищем решение в виде:
\begin{equation}
u(x, t) = \int_{-\infty}^{\infty}A(k)e^{-k^2a^2t + ikx}dk
\end{equation}
Тогда
\begin{equation}
u(x, 0) = \varphi(x) = \int_{-\infty}^{+\infty}A(k)e^{ikx}dk.
\end{equation}
Подставив в $u(x, t)$, находим:
\begin{equation}
u(x, t) = \frac1{2\pi}\int_{-\infty}^{+\infty}\int_{-\infty}^{+\infty}\exp(-k^2a^2t + ik(x - \xi))dk\varphi(\xi)d\xi
= \frac1{2\sqrt{\pi a^2t}}\int_{-\infty}^{+\infty}e^{-\frac{(x - \xi)^2}{4a^2t}}\varphi(\xi)d\xi
\end{equation}
\begin{equation}
\Phi(x) = \frac2{\sqrt{\pi}}\int_0^ze^{-x^2}dx, \Phi(\infty) = 1.
\end{equation}
#+END_EXPORT
** Задача 5.16
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_t = a^2u_{xx}, \\
u(x, 0) = \varphi(x) = \begin{cases}
0, -\infty < x < l \text{ или } l < x < +\infty, \\
u_0 = const \neq 0, -l < x < l.
\end{cases}
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Решение имеет вид
\begin{multline}
u(x, t) = \int_{-l}^l\frac1{2\sqrt{\pi a^2t}}e^{-\frac{(x - \xi)^2}{4a^2t}}u_0d\xi =
\frac{2a\sqrt{t}u_0}{2\sqrt{\pi a^2t}}\int_{-\frac{e - x}{2a\sqrt{t}}}^{\frac{l - x}{2a\sqrt{t}}}e^{-z^2}dz = \\
= \frac{u_0}{\sqrt{\pi}}\left(\int_0^{\frac{l - x}{2a\sqrt{t}}}e^{-z^2}dz +
\int_0^{\frac{l + x}{2a\sqrt{t}}}e^{-z^2}dz\right)
= \frac{u_0}2\left(\Phi\left(\frac{l - x}{2a\sqrt{t}}\right) + \Phi\left(\frac{l - x}{2a\sqrt{t}}\right)\right)
\end{multline}
#+END_EXPORT
** Задача 5.17
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_0 = u_{xx}, \\
u(x, 0) = \begin{cases}
0, x < 0, \\
e^{-\alpha x}, x > 0, \alpha = const > 0.
\end{cases}
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде
\begin{equation}
u(x, t) = \int_0^{+\infty}\frac1{2\sqrt{\pi a^2t}}e^{-\frac{(x - \xi)^2}{4a^2t}}e^{-\alpha\xi}d\xi
\end{equation}
\begin{equation}
-\frac{(x - \xi)^2 + 4a^2t\alpha\xi}{4a^2t} = \ldots =
-\frac{(\xi - x + 2a^2t\alpha)^2 + 4a^2t\alpha x + 4a^4t^2\alpha^2}{4a^2t}
\end{equation}
Подставляя в (23), получим:
\begin{equation}
u(x, t) = \frac1{2\sqrt{\pi a^2 t}}e^{\alpha x + a^2t + a^2t\alpha}\int_{\frac{-x + 2a^2ta}{2a\sqrt{t}}}^{+\infty}e^{-z^2}dz =
\frac{e^{\alpha x + a^2t\alpha^2}}{\sqrt\pi}\left(\sqrt{\pi} - \int_0^{\frac{-x + 2a^2t\alpha}{2a\sqrt{t}}}e^{-z^2}dz\right) = \ldots
\end{equation}
#+END_EXPORT
Если краевые условия первого рода, продолжаем нечётным образом, иначе чётным.
* Семинар 7
\zall
ДЗ: 6.5, 6.13, 6.14, 7.22, 7.25, 7.26, 7.19, 7.20

*Уравнение Лапласа*: $\Delta u = 0$, *уравнение Пуассона*: $\Delta u = -F$.
Функции, удовлетворяющие уравнению Лапласа, называются *гармоническими*.
*Задача Дирихле*: $u|_{\Sigma} = f_1$, *задача Неймана*: $\frac{\partial u}{\partial n}|_{\Sigma} = f_2$.
** Задача 6.1
#+BEGIN_EXPORT latex
Проверить, являются ли функции гармоническими:
1. u_1 = \frac1{\sqrt{x^2 + y^2 + z^2}}, x^2 + y^2 + z^2
2. u_2 = e^{xyz}
3. u_3 = \sin x\sin y\sin z
4. u_4 = \sin 3x\sin 4y\sh 5z
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
1.
$$\frac{\partial u}{\partial x} = -\frac{x}{(x^2 + y^2 + z^2)^{\frac32}}$$
$$\operatorname{grad}u = -\left\{\frac{x}{(x^2 + y^2 + z^2)^{\frac32}}, \frac{y}{(x^2 + y^2 + z^2)^{\frac32}}, \frac{z}{(x^2 + y^2 + z^2)^{\frac32}}\right\}$$
$$\Delta u = \operatorname{div}(\operatorname{grad}u) = \frac{2x^2 - y^2 - z^2 + 2y^2 - x^2 - z^2 + 2z^2 - x^2 - y^2}{\frac{x^2 + y^2 + z^2}^{\frac52}} = 0$$
$$\frac{\partial^2u}{\partial x^2} = -\frac{(x^2 + y^2 + z^2)^{\frac32}} + x\frac32(x^2 + y^2 + z^2)^{\frac12}\cdot2x = \frac{2x^2 - y^2 - z^2}{(x^2 + y^2 + z^2)^{\frac52}}$$
Гармоническая\\
2. 
$$\operatorname{grad}u = \{yz2e^{xyz}, xze^{xyz}, xye^{xyz}\}$$
$$\operatorname{div}(\operatorname{grad}u) = yze^{xyz}yz + (xz)^2e^{xyz} + (xy)^2e^{xyz}$$
Не гармоническая\\
3.
$$\operatorname{grad}u = \{\cos x\sin y\sin z, \cos y\sin x\sin z, \cos z\sin x\sin y\}$$
$$\operatorname{div}\operatorname{grad}u = -\sin x\sin y\sin z - \sin y\sin x\sin z - \sin z\sin x\sin y = -3\sin x\sin y\sin z$$
Не гармоническая\\
4.
$$\frac{\partial u}{\partial x} = 3\cos 3x\sin 4y\sh 5z$$
$$\frac{\partial u}{\partial y} = 4\sin 3x\cos 4y\sh 5z$$
$$\frac{\partial u}{\partial z} = 5\sin 3x\sin 4y\ch 5z$$
$$\operatorname{div}\operatorname{grad}u = -9\sin 3x\sin 4y\sh 5z - 16\sin 3x\sin 4x\sh 5z + 25\sin 3x\sin 4y\sh 5z = 0$$
Гармоническая
#+END_EXPORT
** Задача 6.5
Проверить, являются ли функции гармоническими:
#+BEGIN_EXPORT latex
$$u_1 = \ln\frac1{\sqrt{x^2 + y^2}}, x^2 + y^2 \neq 0$$
$$u_2 = x^2 - y^2 + xy$$
$$u_3 = \frac{x}{x^2 + y^2}$$
$$u_4 = \cos x\sh y - \sin x\sin y$$
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
1.
$$u_1 = -\frac12\ln(x^2 + y^2)$$
$$\operatorname{grad}u = -\left(\frac{x}{x^2 + y^2}, \frac{y}{x^2 + y^2}\right)$$
$$\operatorname{div}\operatorname{grad}u = \ldots = 0$$
Гармоническая\\
2.
$$\frac{\partial u}{\partial x} = 2x + y$$
$$\frac{\partial u}{\partial y} = -2y + x$$
$$\operatorname{div}\operatorname{grad}u = 2 - 2 = 0$$
Гармоническая\\
3.
$$\frac{\partial u}{\partial x} = \frac{y^2 - x^2}{(y^2 + x^2)^2}$$
$$\operatorname{div}\operatorname{grad}u = \ldots = 0$$
Гармоническая\\
4.
$$\div\grad u = \ldots = 0$$
Гармоническая\\
#+END_EXPORT
** Задача 6.3
Рассчитать производную по нормали:
#+BEGIN_EXPORT latex
\begin{equation}
x^2 + y^2 + z^2 = a^2
\end{equation}
\begin{equation}
u_1 = xyz
\end{equation}
\begin{equation}
u_2 = x^3 + y^3 + z^3
\end{equation}
\begin{equation}
u_3 = x^2 + y^2 + z^2
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
$$\frac{\partial u}{\partial n} = \frac{\partial u}{\partial x}\cos\alpha +
\frac{\partial u}{\partial y}\cos\beta + \frac{\partial u}{\partial z}\cos\gamma$$
#+END_EXPORT
** Задача 7.20
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
\Delta u = 0, 0 < x < a, 0 < y < b, \\
u|_{y = 0} = f_1(x), 0 \leq x \leq a, \\
u|_{x = a} = f_2(y), 0 \leq y \leq b, \\
u|_{y = b} = f_3(x), 0 \leq x \leq a, \\
u|_{x = 0} = f_4(y), 0 \leq y \leq b.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Разбиваем задачу на две:
\begin{equation}
\begin{cases}
\Delta u = 0, \\
u|_{y = 0} = f_1(x), \\
u|_{y = b} = f_3(x), \\
u|_{x = 0} = u|_{x = a} = 0
\end{cases}
\end{equation}
и
\begin{equation}
\begin{cases}
\Delta u = 0, \\
u|_{x = 0} = f_4(y), \\
u|_{x = a} = f_2(y), \\
u|_{y = 0} = u|_{y = b} = 0.
\end{cases}
\end{equation}
Решение задачи (1) будет суммой решений (2) и (3).

Ищем решение каждой задачи в виде $u(x, y) = X(x)Y(y)$. После подстановки получаем задачи:
\begin{equation}
\begin{cases}
X'' + \lambda X = 0, \\
X(0) = X(a) = 0, \\
Y'' - \lambda Y = 0, \\
\lambda_n = \left(\frac{\pi n}a\right)^2, \\
X_n = \sin\frac{\pi n}ax, \\
Y_n = C_1e^{\frac{\pi n}ay} + C_2e^{-\frac{\pi n}ay} = A_n\sh\frac{\pi n}ay + B_n\sh\frac{\pi n}a(b - y)
\end{cases}
\end{equation}
и
\begin{equation}
\begin{cases}
X'' - \lambda X = 0, \\
Y'' + \lambda Y = 0, \\
Y(0) = Y(b) = 0, \\
\lambda_n = \left(\frac{\pi n}b\right)^2, \\
Y_n = \sin\frac{\pi n}by, \\
X_n = \ldots
\end{cases}
\end{equation}
Получаем, что
\begin{equation}
\begin{cases}
u_1 = \sum_{n = 1}^{\infty}\left(A_n\sh\frac{\pi n}ay + B_n\sh\frac{\pi n}a(b - y)\right)\sin\frac{\pi n}ax\\
u_2 = \sum_{n = 1}^{\infty}\left(C_n\sh\frac{\pi n}bx + D_n\sh\frac{\pi n}b(a - x)\right)\sin\frac{\pi n}by
\end{cases}
\end{equation}
Подставив в начальные условия, найдём $A_n$ и $B_n$:
\begin{equation}
\begin{dcases}
A_n = \frac1{\sh\frac{\pi n a}b}\frac2a\int_0^af_3(x)\sin\frac{\pi n}axdx, \\
B_n = \frac1{\sh\frac{\pi n b}a}\frac2a\int_0^af_1(x)\sin\frac{\pi n}axdx, \\
C_n = \frac1{\sh\frac{\pi n a}b}\frac2b\int_0^bf_4(y)\sin\frac{\pi n}bydy, \\
D_n = \frac1{\sh\frac{\pi n b}a}\frac2b\int_0^bf_2(y)\sin\frac{\pi n}bydy.
\end{dcases}
\end{equation}
#+END_EXPORT
** Задача next
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
\Delta u = 0, \\
u(0, y) = v_0, \\
u(a, y) = 0, \\
u(x, 0) = 0, \\
u(x, b) = 0.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде
\begin{equation}
u(x, y) = X(x)Y(y)
\end{equation}
Получаем задачу
\begin{equation}
\begin{cases}
Y'' + \lambda Y = 0, \\
Y(0) = Y(b) = 0, \\
X'' - \lambda X = 0, \\
\lambda_n = \left(\frac{\pi n}b\right)^2, \\
Y_n = \frac{\pi n}by, \\
X_n = C_n\sh\frac{\pi n}bx + D_n\sh\frac{\pi n}b(a - x).
\end{cases}
\end{equation}
Получаем, что
\begin{equation}
u(x, y) = \sum_{n = 1}^{\infty}\left(C_n\sh\frac{\pi n}bx + D_n\sh\frac{\pi n}b(a - x)\right)\sin\frac{\pi n}bx
\end{equation}
Подставим начальные условия:
\begin{equation}
u(0, y) = v_0 = \sum_{n = 1}^{\infty}D_n\sh\frac{\pi n}ba\sin\frac{\pi n}by
\end{equation}
Что даёт
\begin{equation}
D_n = \frac1{\sh\frac{\pi n}ba}\frac{2v_0}b\int_0^b\sin\frac{\pi n}bydy = (1 - (-1)^n)\frac{2v_0}{\sin\frac{\pi na}bb}
\end{equation}
#+END_EXPORT
* Семинар 8
ДЗ: 7.7, 7.6, 7.8, 7.9, 7.12, 7.14, 7.15
#+BEGIN_EXPORT latex
\zall
\begin{equation}
u = \tilde{C_0} + \tilde{C_1}\ln r + \sum_{n = 1}^{\infty}(C_nr^n + D_nr^{-n})(A_n\sin n\varphi + B_n\cos n\varphi)
\end{equation}
\begin{equation}
u = \frac1{2\pi}\int_0^{2\pi}\frac{(a^2 - r^2)f(\xi)d\xi}{r^2 + a^2 - 2ra\cos(\varphi - \xi)}
\end{equation}
#+END_EXPORT
** Задача 7.1
Решить задачу:
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
\Delta u = \frac1r\frac{\partial}{\partial r}\left(r\frac{\partial u}{\partial r}\right) + \frac1r^2\frac{\partial^2u}{\partial\varphi^2} = 0, 0 \leq r < a, 0 \leq \varphi < 2\pi, \\
u(a, \varphi) = f(\varphi), 0 \leq \varphi < 2\pi.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде:
\begin{equation}
u = R(r)\Phi(\varphi)
\end{equation}
Тогда:
\begin{equation}
r(R' + rR'')\Phi + R\Phi'' = 0.
\end{equation}
Получаем задачу:
\begin{equation}
\begin{cases}
\Phi'' + \lambda\Phi = 0, \\
\Phi(0) = \Phi(2\pi), \\
r^2R'' + rR' - \lambda R = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции первой задачи:
\begin{equation}
\lambda_n = n^2, \\
\Phi = A_n\sin n\varphi + B_n\cos n\varphi
\end{equation}
Для решения последнего уравнения сделаем замену $R = e^tr$, \ldots, получаем решение:
\begin{equation}
R = C_ne^{nt} + D_ne^{-nt} = C_nr^n + \frac{D_n}{r^n}, R_0 = C_0 + \tilde{C_1}t = C_0 + \tilde{C_1}\ln r.
\end{equation}
Получили, что $u$ имеет вид:
\begin{equation}
u = C_0 + \sum_{n = 1}^{\infty}r^n(A_n\sin n\varphi + B_n\cos n\varphi).
\end{equation}
Разложим $f(\varphi)$:
\begin{equation}
f(\varphi) = u(a, \varphi) = C_0 + \sum_{n = 1}^{\infty}a^n(A_n\sin n\varphi + B_n\cos n\varphi),
\end{equation}
т. е.:
\begin{equation}
C_0 = \frac1{2\pi}\int_0^nf(\xi)d\xi, a^nA_n = \frac1{\pi}\int_0^{2\pi}f(\xi)\sin n\xi d\xi,
a^nB_n = \frac1{\pi}\int_0^{2\pi}f(\xi)\cos n\xi d\xi
\end{equation}
Подставляя в (26), получаем:
\begin{multline}
u = \frac1{2\pi}\int_0^{pi}f(\xi)d\xi + \frac1{2\pi}\sum_{n = 1}^{\infty}\left(\frac{r}a\right)^n
\int_0^{2\pi}f(\xi)(\sin n\xi\sin n\varphi + \cos n\xi\cos n\varphi)d\xi = \\
= \frac1{2\pi}\left[\int_0^{2\pi}f(\xi)\left(1 + \frac{r}a\frac{e^{2(\varphi - \xi)}}{1 - \frac{r}ae^{i(\varphi - \xi)}}
+ \frac{r}a\frac{e^{-2i(\varphi - \xi)}}{1 - \frac{r}ae^{-i(\varphi - \xi)}}\right)\right]
\end{multline}
#+END_EXPORT
** Задача 7.3
#+BEGIN_EXPORT latex
Решить задачу:
\begin{equation}
\begin{cases}
\Delta u = 0, r > a, \\
u|_{r = a} = f(\varphi), 0 < \varphi < 2\pi.
|u(r, \varphi)| < C
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде:
\begin{equation}
u = C_0 + \sum_{n = 1}^{\infty}r^{-n}(A_n\sin n\varphi + B_n\cos n\varphi).
\end{equation}
Тогда
\begin{equation}
u(a, \varphi) = f(\varphi) = C_0 + \sum_{n = 1}^{\infty}a^{-n}(A_n\sin n\varphi + B_n\cos n\varphi)
\end{equation}
\begin{equation}
\begin{cases}
C_0 = \frac2{\pi}\int_0^{2\pi}f(\xi)d\xi, \\
a^{-n}A_n = \frac1{\pi}\int_0^{2\pi}f(\xi)\sin n\xi d\xi, \\
a^{-n}B_n = \frac1{\pi}\int_0^{2\pi}f(\xi)\cos n\xi d\xi.
\end{cases}
\end{equation}
\begin{equation}
u(a, \varphi) = \frac2{\pi}\int_0^{2\pi}f(\xi)d\xi + \frac1{\pi}\sum_{n = 1}^{\infty}\left(\frac{a}r\right)^n
\int_0^{2\pi}f(\xi)\cos n(\varphi - \xi)d\xi
\end{equation}
Пусть теперь $f(\varphi) = \cos^2\varphi$. Тогда
\begin{equation}
cos^2\varphi = \frac12\cos2\varphi + \frac12 \Rightarrow C_0 = \frac12, B_2a^{-2} = \frac12 \Rightarrow B_2 = \frac{a^2}2
\end{equation}
и
\begin{equation}
u(r, \varphi) = \frac12 + \left(\frac{a}r\right)^2\frac12\cos2\varphi
\end{equation}
#+END_EXPORT
** Задача 7.4
#+BEGIN_EXPORT latex
\begin{cases}
\Delta u = 0, r < a, 0 \leq \varphi \leq 2\pi, \\
\frac{\partial u}{\partial r}|_{r = a} = f(\varphi), \int_0^{2\pi}f(\varphi)d\varphi = 0.
\end{cases}
Последнее условие является необходимым для наличия решения.
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде
\begin{equation}
u = \tilde{C_0} + \sum_{n = 0}r^n(A_n\sin n\varphi + B_n\cos n\varphi).
\end{equation}
Тогда из краевого условия:
\begin{equation}
\frac{\partial u}{\partial r}|_{r = a} = f(\varphi) = \sum_{n = 0}^{\infty}na^{n - 1}(A_n\sin n\varphi + B_n\cos n\varphi),
\end{equation}
т. е.
\begin{equation}
\begin{cases}
na^{n - 1}A_n = \frac1{\pi}\int_0^{2\pi}f(\xi)\sin n\xi d\xi, \\
na^{n - 1}B_n = \frac1{\pi}\int_0^{2\pi}f(\xi)\cos n\xi d\xi.
\end{cases}
\end{equation}
Подставляя в (37), получаем:
\begin{equation}
u(r, \varphi) = C_0 + \frac1{\pi}\sum_{n = 1}^{\infty}\frac{r^n}{na^{n - 1}}\int_0^{2\pi}f(\xi)\cos n(\varphi - \xi)d\xi
\end{equation}
Положим теперь $f(\varphi) = A\cos\varphi$. Можно проверить, что решение существует. Тогда
\begin{equation}
\frac{\partial u}{\partial r}|_{r = a} = \sum_{n = 0}^{\infty}na^{n - 1}(A_n\sin n\varphi + B_n\cos n\varphi) = A\cos n\varphi \Rightarrow B_1 = A,
\end{equation}
т. е.
\begin{equation}
u = C_0 + rA\cos\varphi
\end{equation}

Рассмотрим теперь задачу в области $r > a$. В этом случае решение приобретёт вид:
\begin{equation}
\frac{\partial u}{\partial r}|_{r = a} = \sum_{n = 1}^{\infty}-na^{-(n + 1)}(A_n\sin n\varphi + B_n\cos n\varphi) = f(\varphi)
\end{equation}
#+END_EXPORT
** Задача 7.11
#+BEGIN_EXPORT latex
Решить задачу
\begin{equation}
\begin{cases}
\Delta u = 0, 0 < a < r < b, 0 < \varphi < 2\pi, \\
u(a, \varphi) = f_1(\varphi), \\
u(b, \varphi) = f_2(\varphi).
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Решение имеет вид (1). Подставляя в начальные условия, получим:
\begin{equation}
\begin{dcases}
u(a, \varphi) = f_1(\varphi) = \tilde{C_0} + \tilde{C_1}\ln a + \sum_{n = 1}^{\infty}(C_na^n + D_na^{-n})(A_n\sin n\varphi + B_n\cos n\varphi), \\
u(b, \varphi) = f_2(\varphi) = \tilde{C_0} + \tilde{C_1}\ln b + \sum_{n = 1}^{\infty}(C_nb^n + D_nb^{-n})(A_n\sin n\varphi + B_n\cos n\varphi), \\
\frac1{2\pi}\int_0^{2\pi}f_1(\varphi) = \tilde{C_0} + \tilde{C_1}\ln a, \\
\frac1{2\pi}\int_0^{2\pi}f_2(\varphi) = \tilde{C_0} + \tilde{C_1}\ln b, \\
\frac1{\pi}\int_0^{2\pi}f_1(\xi)\sin n\xi d\xi = (C_na^n + D_na^{-n})A_n, \\
\frac1{\pi}\int_0^{2\pi}f_2(\xi)\sin n\xi d\xi = (C_nb^n + D_nb^{-n})A_n, \\
\frac1{\pi}\int_0^{2\pi}f_1(\xi)\cos n\xi d\xi = (C_na^n + D_na^{-n})B_n, \\
\frac1{\pi}\int_0^{2\pi}f_2(\xi)\cos n\xi d\xi = (C_nb^n + D_nb^{-n})B_n.
\end{dcases}
\end{equation}
#+END_EXPORT
** Задача 7.13
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
\Delta u = 0, 0 < r < a, 0 < \varphi < \alpha < 2\pi, \\
u(r, 0) = u(r, \alpha) = 0, 0 \leq r \leq a, \\
u(a, \varphi) = f(\varphi), 0 < \varphi < a.
\end{cases}
\end{equation}
Ищем решение в виде:
\begin{equation}
u(r, \varphi) = R(r)\Phi(\varphi)
\end{equation}
Получим задачи:
\begin{equation}
\begin{cases}
\Phi'' + \lambda\Phi = 0, \\
\Phi(0) = \Phi(\alpha) = 0, \\
r^2R'' + rR' - \lambda R = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции:
\begin{equation}
\lambda_n = \left(\frac{\pi n}\alpha\right)^2, \\
\Phi_n = \sin\frac{\pi n}\alpha\varphi.
\end{equation}
Решения уравнения имеют вид:
\begin{equation}
R = C_nr^{\sqrt{\lambda_n}} + D_nr^{-\sqrt{\lambda_n}}
\end{equation}
$D_n = 0$ вследствие ограниченности функции в нуле. Тогда $u(r, \varphi)$ будет иметь вид:
\begin{equation}
\begin{cases}
u(r, \varphi) = \sum_{n = 1}^{\infty}C_nr^{\frac{\pi n}{\alpha}}\sin\frac{\pi n}{\alpha}\varphi, \\
f(\varphi) = \sum_{n = 1}^{\infty}C_n\alpha^{\frac{\pi n}{\alpha}\sin\frac{\pi n}{\alpha}\varphi}
\end{cases}
\end{equation}
#+END_EXPORT
* Семинар 9
\zall
ДЗ: 8.6, 8.9, 9.1-9.7(прочитать), 9.12, 9.20, 9.13, 9.10, 9.17

*Формула Грина*:\\
Трёхмерный случай:
#+BEGIN_EXPORT latex
\begin{equation}
u(Q) = \iint_S\left(G(P, Q)\frac{\partial u}{\partial \eta_P} - u(P)\frac{\partial G(P, Q)}{\partial \eta_P}dS_P\right) -
\iiint_{\Omega} G(P, Q)\Delta u(P)dxdydz
\end{equation}
\begin{equation}
G(P, Q) = \frac1{4\pi r_{PQ}} + \nu(P), \text{ где } \nu(P) \text{ - гармоническая функция}
\end{equation}
Постановка задачи:
\begin{equation}
\begin{cases}
\Delta u(P) = -F(P) \text{ в } \Omega, \\
u|_{P \in S} = f(P)
\end{cases}
\end{equation}
По формуле Грина:
\begin{equation}
u(Q) = -\iint_Sf(P)\frac{\partial G}{\partial n_P}dS_P + \iiint_{\Omega}GFdxdydz
\end{equation}
Плоский случай:
\begin{equation}
u(Q) = \int_{\gamma}\left(G\frac{\partial u}{\partial n_P} - u\frac{\partial G}{\partial n_P}\right) - \iint_DG\Delta udxdy
\end{equation}
\begin{equation}
G(P, Q) = \frac1{2\pi}\ln\frac1{r_{PQ}} + \nu(P)
\end{equation}
Постановка задачи:
\begin{equation}
\begin{cases}
\Delta u = -F, \\
u|_{P \in \gamma} = f(P)
\end{cases}
\end{equation}
По формуле Грина:
\begin{equation}
u(Q) = -\int_{\gamma}f\frac{\partial G}{\partial n_P}d\gamma_P + \iint_DGFdxdy
\end{equation}
#+END_EXPORT
** Задача 8.5
 #+BEGIN_EXPORT latex
 \begin{equation}
 \begin{cases}
 \Delta u = 0, x, z \in K, y > 0, \\
 u|_{y = 0} = f(x, z).
 \end{cases}
 \end{equation}
 #+END_EXPORT
*** Решение
 #+BEGIN_EXPORT latex
 По формуле Грина:
 \begin{equation}
 u(Q) = \int_{-\infty}^{+\infty}\int_{-\infty}^{+\infty}f(x, z)\frac{\partial G}{\partial y}dxdz
 \end{equation}
 \begin{multline}
 G(P, Q) = \frac1{4\pi r_{PQ}} - \frac1{4\pi r_{PQ_1}} = \\
 = \frac1{4\pi}\left(\frac1{\sqrt{(x - x_0)^2 + (y - y_0)^2 + (z - z_0)^2}} +
 \frac1{\sqrt{(x - x_0)^2 + (y + y_0)^2 + (z - z_0)^2}}\right)
 \end{multline}
 Тогда
 \begin{multline}
 \frac{\partial G}{\partial y}\bigg|_{y = 0} = -\frac1{4\pi}\left(-\frac{y_0}{((x - x_0)^2 + y_0^2 + (z - z_0)^2)^{\frac32}} -
 \frac{y_0}{((x - x_0)^2 + y_0^2 + (z - z_0)^2)^{\frac32}}\right) = \\
 = \frac{y_0}{2\pi((x - x_0)^2 + y_0^2 + (z - z_0)^2)^{\frac32}}
 \end{multline}
 #+END_EXPORT
** Задача 8.10
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
\Delta u = 0, x \in K, y > 0, \\
u|_{y = 0} = f(x).
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
По формуле Грина:
\begin{equation}
u(Q) = \int_{-\infty}^{+\infty}f(x)\frac{\partial G}{\partial y} = \frac{y_0}{\pi}\int_{-\infty}^{+\infty}\frac{f(x)dx}{(x - x_0)^2 + y_0^2}
\end{equation}
Здесь
\begin{equation}
G(P, Q) = \frac1{2\pi}\ln\frac1{r_{PQ}} - \frac1{2\pi}\ln\frac1{r_{PQ_1}}
\end{equation}
\begin{equation}
\frac{\partial G}{\partial y}\bigg|_{y = 0} = -\frac1{4\pi}\left(-\frac{2y_0}{(x - x_0)^2 + y_0^2} -
\frac{2y_0}{(x - x_0)^2 + y_0^2}\right) = \frac{y_0}{\pi((x - x_0)^2 + y_0^2)}
\end{equation}
#+END_EXPORT
** Задача 8.11
#+BEGIN_EXPORT latex
\begin{equation}
\Omega = \{(x, y) | x > 0, y > 0\}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Пусть $Q(x_0, y_0)$. Введём точки $Q_1(x_0, -y_0), Q_2(-x_0, y_0), Q_3(-x_0, -y_0)$. Тогда функция
Грина имеет вид:
\begin{multline}
G = \frac1{2\pi}\left(\ln\frac1{\sqrt{(x - x_0)^2 + (y - y_0)^2}} -
\ln\frac1{\sqrt{(x - x_0)^2 + (y + y_0)^2}} - \\
- \ln\frac1{\sqrt{(x + x_0)^2 + (y - y_0)^2}} +
\ln\frac1{\sqrt{(x + x_0)^2 + (y + y_0)^2}}\right)
\end{multline}
#+END_EXPORT
** Задача 8.13
#+BEGIN_EXPORT latex
\begin{equation}
\Omega = \{(x, y) | \rho((x, y), O) < R\}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Рассматриваются точки, симметричные относительно окружности
\begin{equation}
G = \frac1{2\pi}\left(\ln\frac1{R_{PQ}} - \ln\frac1{R_{PQ'}R}\right)(?)
\end{equation}
#+END_EXPORT
*Теорема о среднем*:
#+BEGIN_EXPORT latex
\begin{equation}
u(M_0) = \frac1{2\pi a}\int_{C_A}udl
\end{equation}
#+END_EXPORT
** Задача 9.4
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
\Delta u = 0, y > 0, x \in \mathbb{R}, \\
u|_{y = 0} = \varphi(x).
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Конформно отобразим эту область на единичный круг, получим задачу:
\begin{equation}
\begin{cases}
\Delta u = 0, r < R, 0 \leq \varphi \leq 2\pi, \\
u|_{r = 1} = f(\varphi)
\end{cases}
\end{equation}
Это отображение $w(z, z_0) = \frac{z - z_0}{z - \overline{z_0}} = \rho\cdot e^{i\varphi}$.
Тогда
\begin{equation}
u = \frac1{2\pi}\int_0^{2\pi}f(\varphi)d\varphi
\end{equation}
\begin{equation}
w(z, z_0) = \frac{x - x_0 - iy_0}{x - x_0 + iy_0} = e^{i\varphi}
\end{equation}
Продифференцируем:
\begin{equation}
\frac{dx(x - x_0 + iy_0) - dx(x - x_0 - iy_0)}{(x - x_0 + iy_0)^2} = ie^{i\varphi}d\varphi
\Rightarrow
\frac{2iy_0}{(x - x_0 + iy_0)^2}dx = i\frac{x - x_0 + iy_0}{x - x_0 - iy_0}d\varphi
\end{equation}
Соответственно,
\begin{equation}
d\varphi = \frac{2y_0}{(x - x_0)^2 + y_0^2}dx
\end{equation}
И тогда для $u$:
\begin{equation}
u = \frac1{2\pi}\int_0^{2\pi}f(\varphi)d(\varphi) = \frac1{\pi}\int_{-\infty}^{+\infty}\varphi(x)\frac{y_0}{(x - x_0)^2 + y_0^2}dx.
\end{equation}
#+END_EXPORT
*Общий вид функции Грина*:
#+BEGIN_EXPORT latex
\begin{equation}
G = \frac1{2\pi}\ln\frac1{|w(z, z_0)|}
\end{equation}
#+END_EXPORT
В нашей задаче:
#+BEGIN_EXPORT latex
\begin{equation}
G = \frac1{2\pi}\ln\frac1{|w(z, z_0)|} = \frac1{2\pi}\ln\frac{|z - \overline{z_0}|}{|z - z_0|}
\end{equation}
#+END_EXPORT
* Семинар 10
\zall
ДЗ: 12.5, 12.7
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = 4u_{xx} + xt, \\
u(x, 0) = x^2, \\
u_t(x, 0) = x.
\end{cases}
\end{equation}
\begin{equation}
\begin{cases}
u_{tt} = u_{xx} + \sin t, \\
u(x, 0) = \sin x, \\
u_t(x, 0) = \cos x.
\end{cases}
\end{equation}
\begin{equation}
\begin{cases}
u_{tt} = u_{xx}, \\
u(x, 0) = \begin{cases}
\cos x, |x| < \frac{\pi}2, \\
0, |x| > \frac{\pi}2.
\end{cases}
u_t(x, 0) = 0
\end{cases}
\end{equation}
В последнем случае найти $u\left(x, \frac{\pi}4\right)$
\begin{equation}
\begin{cases}
u_{tt} = u_{xx}, \\
u(x, 0) = 0, \\
u_t(x, 0) = \begin{cases}
\cos x, |x| < \frac{\pi}2, \\
oyes0, |x| > \frac{\pi}2.
\end{cases}
\end{cases}
\end{equation}
#+END_EXPORT
** Гиперболические уравнения
*Формула д'Аламбера*:
#+BEGIN_EXPORT latex
Задача:
\begin{equation}
\begin{cases}
u_t = a^2u_{xx} + f(x, t), \\
u(x, 0) = \varphi(x), \\
u_t(x, 0) = \psi(x).
\end{cases}
\end{equation}
\begin{equation}
u(x, t) = \frac12(\varphi(x + at) + \varphi(x - at)) + \frac1{2a}\int_{x - at}^{x + at}\varphi(\xi)d\xi
+ \frac1{2a}\int_0^t\int_{x - a(t - \tau)}^{x + a(t - \tau)}f(\xi, \tau)d\xi d\tau
\end{equation}
#+END_EXPORT
#+BEGIN_EXPORT latex
Простейший случай:
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx} + f(x, t), -\infty < x < +\infty, 0 < t \leq T, \text{ (уравнение струны)}, \\
u(x, 0) = \varphi(x), \\
u_t(x, 0) = \psi(x)
\end{cases}
\end{equation}
Граничные условия:

Первого рода:
\begin{equation}
u(0, t) = \mu(t), \\
\end{equation}
Второго:
\begin{equation}
u_x(0, t) = \nu(t), \\
\end{equation}
Третьего:
\begin{equation}
u_x(0, t) + u(0, T - t_1) = 0.
\end{equation}
#+END_EXPORT
** Задача 12.1
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx}, -\infty < x < +\infty, t > 0, a > 0, \\
u(x, 0) = \varphi(x), \\
u_t(x, 0) = \psi(x).
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Приведём к канонической форме:\\
Характеристическое уравнение:
\begin{equation}
dx^2 = a^2dt^2 \Rightarrow
\begin{cases}
\xi = x - at, \\
\eta = x + at.
\end{cases}
\end{equation}
Получим форму:
\begin{equation}
v_{\xi\eta} = 0.
\end{equation}
Откуда
\begin{equation}
v = f_1(\xi) + f_2(\eta) = f_1(x - at) + f_2(x + at)
\end{equation}
Подставляем в начальные условия:
\begin{equation}
\begin{cases}
f_1(x) + f_2(x) = \varphi(x), \\
f_1'(x)\cdot(-a) + f_2'(x)\cdot a = \psi(x)
\end{cases}
\end{equation}
или, интегрируя второе уравнение от $x_0$ до $x$:
\begin{equation}
-a\int_{x_0}^xf_1'(\xi)d\xi + a\int_{x_0}^xf_2'(\xi)d\xi = \int_{x_0}^x\psi(\xi)\d\xi
\Rightarrow
f_2(x) - f_1(x) = \frac1a\int_{x_0}^x\psi(\xi)d\xi
\end{equation}
Отсюда и из первого уравнения получаем:
\begin{equation}
\begin{cases}
f_1(x) = \frac{\varphi(x)}2 + \frac1{2a}\left(\int_{x_0}^x\varphi(\xi)d\xi + C\right), \\
f_2(x) = \frac{\varphi(x)}2 - \frac1{2a}\left(\int_{x_0}^x\varphi(\xi)d\xi - C\right).
\end{cases}
\end{equation}
Откуда для $u$:
\begin{equation}
u(x, t) = \frac12(\varphi(x - at) + \varphi(x + at)) + \frac1{2a}\int_{x - at}^{x + at}\psi(\xi)d\xi \text{- формула д'Аламбера.}
\end{equation}
#+END_EXPORT
** Задача 12.2
#+BEGIN_EXPORT latex
Геометрический смысл формулы д'Аламбера?
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Зафиксируем точку $M(x_0, y_0)$. Тогда:
\begin{equation}
u(M) = \frac12(\varphi(P) + \varphi(Q)) + \frac1{2a}\int_P^Q\varphi(\xi)d\xi
\end{equation}
Прямые $x - at, x + at, x_0 + at_0, x_0 - at_0$ разбивают плоскость на шесть частей. Найдём
решение в каждой:\\
Область 1:
$$u(x, t) \equiv 0$$
Область 6:
$$u(x, t) \equiv 0$$
Область 2:
$$u(x_1, t_1) = \frac12\varphi(x_1 - at_1) + \frac1{2a}\int_{x_1 - at_1}^{x_1 + at_1}\varphi(\xi)d\xi$$
Область 3:
$$u(x_1, t_1) = \frac12\varphi(x_1 - at_1) + \frac1{2a}\int_{x_1 - at_1}^{x_1 + at_1}\varphi(\xi)d\xi$$
Область 5:
$$u(x_1, t_1) = \frac12\varphi(x_1 + at_1) + \frac1{2a}\int_{x_1 - at_1}^{x_1 + at_1}\varphi(\xi)d\xi$$
Область 4:
$$u(x_1, t_1) = \frac1{2a}\int_{x_1 - at_1}^{x_1 + at_1}\varphi(\xi)d\xi$$
#+END_EXPORT
** Задача 12.3
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u(x, 0) = \begin{cases}
1 - \frac{|x|}c, |x| \leq c, \\
0, |x| > c.
\end{cases}
u_t(x, 0) = 0
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
\begin{equation}
t = t_i = \frac{c\cdot i}{4a}, i = \overline{0, 5}
\end{equation}
\begin{equation}
x - at = 0 \Rightarrow x = \frac{c}4
\end{equation}
#+END_EXPORT
**** TODO перенести картинки из тетради
** Задача 12.4
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u(x, 0) = 0, \\
u_t(x, 0) = \begin{cases}
V = const \neq 0, |x| < c, \\
0, |x| > c.
\end{cases}
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
По формуле д'Аламбера:
\begin{equation}
u(x, t) = \Psi(x + at) - \Psi(x - at), \text{ где } \Psi(z) = \frac1{2a}\int_{x_0}^z\varphi(\xi)d\xi =
\begin{dcases}
0, z < -c, \\
\frac{V}{2a}(z + C_0), z \in [-c, c], \\
\frac{V}{a}, z > c.
\end{dcases}
\end{equation}
#+END_EXPORT
**** TODO Перенести картинки
** Задача 12.6
Найти решение для задачи из условия 12.4.
*** Решение
**** TODO Перенести рисунок

Найдём решение в каждой области:
#+BEGIN_EXPORT latex
Область 1:
\begin{equation}
u(x_0, t_0) = 0
\end{equation}
Область 2:
\begin{equation}
u(x_0, t_0) = \frac1{2a}\int_{x_0 - at_0}^cVd\xi = \frac{V}{2a}(c - x_0 - at_0)
\end{equation}
Область 3:
\begin{equation}
u(x_0, t_0) = \frac1{2a}\int_{-c}^cVd\xi = \frac{V}{2a}2c = \frac{Vc}a
\end{equation}
Область 4:
\begin{equation}
u(x_0, t_0) = \frac1{2a}\int_{x_0 - at_0}^{x_0 + at_0}Vd\xi = \frac{V}{2a}2at_0 = Vt_0
\end{equation}
Область 5:
\begin{equation}
u(x_0, t_0) = \frac1{2a}\int_{-c}^{x_0 + at_0}Vd\xi = \frac{V}{2a}(x_0 + at_0 + c)
\end{equation}
Область 6:
\begin{equation}
u(x_0, t_0) = 0
\end{equation}
#+END_EXPORT
** Задача next
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = u_{xx}, \\
u(x, 0) = \begin{cases}
\cos x, |x| \leq \frac{\pi}2, \\
0, |x| > \frac{\pi}2
\end{cases}
u_t(x, 0) = 0
\end{cases}
\end{equation}
Найти $u\left(\frac{\pi}4, t\right)$.
#+END_EXPORT
*** Решение
**** TODO Перенести картинку
#+BEGIN_EXPORT latex
Найдём решение в каждой области:\\
Область 1:
\begin{equation}
u\left(\frac{\pi}4, t_0\right) = \frac12\left(\cos\left(\frac{\pi}4 - t_0\right) +
\cos\left(\frac{\pi}4 + t_0\right)\right), t_0 \in \left[0, \frac{\pi}4\right].
\end{equation}
Область 2:
\begin{equation}
u(\frac{\pi}4, t_0) = \frac12\cos\left(\frac{\pi}4 - t_0\right), t_0 \in \left[\frac{\pi}4, \frac{3\pi}4\right].
\end{equation}
Область 3:
\begin{equation}
u\left(\frac{\pi}4, t_0\right) = 0, t_0 > \frac{3\pi}4.
\end{equation}
#+END_EXPORT
** Задача next2
#+BEGIN_EXPORT latex
Решить задачу
\begin{equation}
\begin{cases}
u_{tt} = u_{xx} + 6, \\
u(x, 0) = x^2, \\
u_t(x, 0) = 4x.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
По формуле д'Аламбера:
\begin{equation}
u(x, t) = \frac12((x - t)^2 + (x + t)^2) + \frac12\int_{x - t}^{x + t}4\xi d\xi +
\frac12\int_0^t\int_{x - (t - \tau)}^{x + (t - \tau)}6d\xi d\tau =
x^2 + t^2 + 4xt + 3\int_0^t2(t - \tau)d\tau = x^2 + t^2 + 4xt + 3t^2 = x^2 + 4xt + 4t^2
\end{equation}
#+END_EXPORT
* Семинар 12
\zall
** Метод разделения переменных для гиперболических уравнений.
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx}, 0 < x < l, t > 0\\
u(0, t) = u(l, t) = 0, \\
u(x, 0) = \varphi(x), \\
u_t(x, 0) = \psi(x).
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение уравнения в виде
\begin{equation}
u(x, t) = X(x)T(t)
\end{equation}
Подставляя в уравнение, получим:
\begin{equation}
XT'' = a^2X''T \Rightarrow \frac{X''}X = \frac{T''}{a^2T} = -\lambda
\end{equation}
Получаем задачи:
\begin{equation}
\begin{cases}
X'' + \lambda X = 0, X(0) = X(l) = 0, \\
T'' + \lambda a^2T = 0.
\end{cases}
\end{equation}
Решение первой задачи:
\begin{equation}
\begin{cases}
\lambda = \left(\frac{\pi n}l\right)^2, \\
X_n = \sin\frac{\pi n}lx.
\end{cases}
\end{equation}
Второй:
\begin{equation}
\begin{cases}
T_n = C_{1n}\sin\sqrt{\lambda_n}at + C_{2n}\sin\sqrt{\lambda_n}at
\end{cases}
\end{equation}
Тогда решение задачи (1) имеет вид:
\begin{equation}
u(x, t) = \sum_{n = 1}^{\infty}T_n(t)X_n(x) = \sum_{n = 1}^{\infty}(C_{1n}\sin\sqrt{\lambda_n}at +
C_{2n}\cos\sqrt{\lambda_n}at)\sin\sqrt{\lambda_n}x
\end{equation}
Подставляя в начальные условия, находим:
\begin{equation}
u(x, 0) = \sum_{n = 1}^{\infty}C_{2n}\sin\sqrt{\lambda_n}x = \varphi(x) \Rightarrow C_{2n} =
\frac2l\int_0^l\varphi(\xi)\sin\frac{\pi n}l\xi d\xi, \\
u_t(x, 0) = \sum_{n = 1}^{\infty}C_{1n}\sqrt{\lambda_n}a\sin\sqrt{\lambda_n}x = \psi(x) =
\frac2{\sqrt{\lambda_n}al}\int_0^l\psi(\xi)\sin\sqrt{\lambda_n}\xi d\xi.
\end{equation}
Пусть теперь задача имеет вид:
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx} + f(x, t), \\
u(0, t) = u(l, t) = 0, \\
u(x, 0) = u_t(x, 0) = 0.
\end{cases}
\end{equation}
Ищем решение в виде ряда по собственным функциям ЗШЛ:
\begin{equation}
u(x, t) = \sum_{n = 1}^{\infty}u_n(t)\sin\frac{\pi n}lx,
f(x, t) = \sum_{n = 1}^{\infty}f_n(t)\sin\frac{\pi n}lx.
\end{equation}
Подставив в уравнение, находим:
\begin{equation}
\sum_{n = 1}^{\infty}u_n''(t)\sin\frac{\pi n}lx = -a^2\sum_{n = 1}^{\infty}u_n(t)\sin\frac{\pi n}lx\left(\frac{\pi n}l\right)^2 +
\sum_{n = 1}^{\infty}f_n(t)\sin\frac{\pi n}lx
\end{equation}
Получаем систему задач Коши:
\begin{equation}
\begin{cases}
u_n''(t) = -a^2\lambda_nu_n(t) + f_n(t), \\
u_n(0) = 0, \\
u_n'(0) = 0.
\end{cases}
\end{equation}
Решение ищем методом вариации постоянной. Решение однородного уравнения имеет вид:
\begin{equation}
u_n(t) = C_1\cos(a\sqrt{\lambda_n}t) + C_2\sin(a\sqrt{\lambda_n}t)
\end{equation}
Подставляя начальные условия, получим систему:
\begin{equation}
\begin{cases}
C'_1\cos a\sqrt{\lambda_n}t + C'_2\sin a\sqrt{\lambda_n}t = 0, \\
-C'_1a\sqrt{\lambda_n}\sin a\sqrt{\lambda_n}t + C'_2a\sqrt{\lambda_n}\cos s\sqrt{\lambda_n}t = f_n(t).
\end{cases}
\end{equation}
Окончательно получится:
\begin{equation}
\begin{cases}
u''_n + a^2\lambda_nu_n = f_n, \\
u_n = \frac1{\sqrt{\lambda_n}a}\int_0^t\sin(a\sqrt{\lambda_n}(t - \tau))f_n(\tau)d\tau
\end{cases}
\end{equation}
#+END_EXPORT
** Задача 13.1
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx}, \\
u(0, t) = u(l, t) = 0, \\
u(x, 0) = \sin\frac{\pi x}l, 0 \leq x \leq l, \\
u_t(x, 0) = 0, 0 \leq x \leq l.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Собственные значения и собственнные функции ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = \left(\frac{\pi n}l)^2, \\
X_n = \sin\frac{\pi n}lx, \\
T_n = C_{1n}\sin\frac{\pi n}lat + C_{2n}\cos\frac{\pi n}lat
\end{cases}
\end{equation}
Тогда $u$ ищем в виде:
\begin{equation}
u(x, t) = \sum_{n = 1}^{\infty}X_n(x)T_n(t) =
\sum_{n = 1}^{\infty}\sin\frac{\pi n}lx\left(C_{1n}\sin\frac{\pi n}lat + C_{2n}\cos\frac{\pi n}lat\right)
\end{equation}
Подставим в начальные условия:
\begin{equation}
\begin{cases}
u(x, 0) = \sum_{n = 1}^{\infty}\frac{\pi n}lxC_{2n} = \sin\frac{\pi x}l, \\
u_t(x, 0) = \sum_{n = 1}^{\infty}\sin\frac{\pi n}lxC_{1n}\frac{\pi n}la = 0,
\end{cases}
\end{equation}
откуда
\begin{equation}
u(x, t) = \sin\frac{\pi x}l\cos\frac{\pi a}lt
\end{equation}
#+END_EXPORT
** Задача 13.2
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx}, \\
u(0, t) = u_x(\pi, t) = 0, \\
u(x, 0) = \sin\frac{3x}2 + \sin\frac{5x}2, \\
u_t(x, 0) = b\sin\frac{7x}2, b = const.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Собственные значения и собственные функции ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = \left(\frac{(2n + 1)}2\right)^2, \\
X_n = \sin\frac{2n + 1}2x, \\
T_n = C_{1n}\sin\frac{2n + 1}2bt + C_{2n}\cos\frac{2n + 1}2bt.
\end{cases}
\end{equation}
Ищем решение в виде:
\begin{equation}
u(x, t) = \sum_{n = 0}^{\infty}\sin\frac{2n + 1}2x\left(C_{1n}\sin\frac{2n + 1}bt +
C_{2n}\cos\frac{2n + 1}2bt\right)
\end{equation}
Подставляем в начальные условия:
\begin{equation}
\begin{cases}
u(x, 0) = \sum_{n = 0}^{\infty}C_{2n} = \sin\frac{3x}2 + \sin\frac{5x}2 \Rightarrow C_{21} = C_{22} = 1, C_{2n} = 0, n \notin \{1, 2\}, \\
u_t(x, 0) = \sum_{n = 0}^{\infty}\sin\frac{2n + 1}2b\frac{2n + 1}2C_{1n} = b\sin\frac{7x}2 \Rightarrow C_{13} = \frac27, C_{1n} = 0, n \neq 3.
\end{cases}
\end{equation}
Окончательно получаем:
\begin{equation}
u(x, t) = \sin\frac{3x}2\cos\frac32bt + \sin\frac{5x}2\cos\frac52bt + \frac27\sin\frac{7x}2\sin\frac72at
\end{equation}
#+END_EXPORT
** Задача 13.4
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = 4u_{xx}, \\
u_x(0, t) = 0, \\
u(1, t) = 0, \\
u(x, 0) = 1 - x, \\
u_t(x, 0) = 0.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Собственные значения и собственные функции ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = \left(\frac{\pi(2n + 1)}2\right)^2, \\
X_n = \cos\sqrt{\lambda_n}x, \\
T_n = C_{1n}\sin\sqrt{\lambda_n}2t + C_{2n}\cos\sqrt{\lambda_n}2t
\end{cases}
\end{equation}
Ищем решение в виде ряда $u(x, t) = \sum_{n = 0}^{\infty}X_n(x)T_n(t)$. Подставляем в начальные
условия:
\begin{equation}
u(x, 0) = \sum_{n = 0}^{\infty}\cos\frac{\pi (2n + 1)}2xC_{2n} = 1 - x
\end{equation}
Откуда
\begin{equation}
C_{2n} = 2\int_0^1(1 - x)\cos\frac{\pi (2n + 1)}2xdx = \ldots = \frac8{(\pi(2n + 1))^2}(1 - (-1)^n)
\end{equation}
\begin{equation}
u_t(x, 0) = 0 \Rightarrow C_{1n} = 0 \forall n.
\end{equation}
Окончательно имеем:
\begin{equation}
u(x, t) = \sum_{n = 0}^{\infty}\cos\frac{\pi(2n + 1)}2\cos\pi(2n + 1)t\frac8{(pi(2n + 1))^2}(1 - (-1)^n)
\end{equation}
#+END_EXPORT
** Задача 13.7
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = a^2u_{xx} + f_0, f_0 = const, \\
u(0, t) = u(l, t) = 0, \\
u(x, 0) = u_t(x, 0) = 0.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде ряда по собственным функциям ЗШЛ:
\begin{equation}
u(x, t) = \sum_{n = 1}^{\infty}u_n(t)\sin\frac{\pi n}lx
\end{equation}
Подставляем в начальные условия, получаем:
\begin{equation}
\begin{cases}
u''_n + \lambda a^2u_n = f_{0n}, \text{ где } f_{0n} = \frac2l\int_0^lf_0\sin\frac{\pi n}lxdx = \frac{2f_0}{\pi n}(1 - (-1)^n) \\
u(0) = u'(0) = 0.
\end{cases}
\end{equation}
Общее решение однородного уравнения имеет вид:
\begin{equation}
Cu_n(t) = C_1\cos\sqrt{\lambda_n}at + C_2\sin\sqrt{\lambda_n}at
\end{equation}
Заметим, что частным решением будет $A_n = \frac{f_{0n}}{\lambda a^2}$. Поэтому общее решение
неоднородного уравения будет:
\begin{equation}
u_n(t) = C_{1n}\cos\sqrt{\lambda_n}at + C_{2n}\sin\sqrt{\lambda_n}at + \frac{2l^2}{(\pi na)^2}(1 - (-1)^n)
\end{equation}
Обозначив последнее слагаемое через $B_n$, из начальных условий получим систему:
\begin{equation}
\begin{cases}
C_{1n} + B_n = 0, \\
C_{2n}\sqrt{\lambda_n}a + B_n = 0,
\end{cases}
\Rightarrow
\begin{cases}
C_{1n} = -B_n, \\
C_{2n} = -\frac{B}{a\sqrt{\lambda_n}}
\end{cases}
\end{equation}
Окончательное решение имеет вид:
\begin{equation}
u(x, t) = \sum_{n = 1}^{\infty}\sin\frac{\pi n}lx\frac{2l^2}{(\pi n a)^2}(1 - (-1)^n)\left(-\cos\frac{\pi n}lat + 1\right)
\end{equation}
#+END_EXPORT
** Задача 13.8
#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_{tt} = 4u_{xx}, \\
u(0, t) = t, \\
u_x\left(\frac{pi}2, x\right) = \pi, \\
u(x, 0) = 2\sin5x + \pi x, \\
u_t(x, 0) = 1.
\end{cases}
\end{equation}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Ищем решение в виде $u = U + v$, где $U(x, t) = a(t)x + b(t)$. Тогда:
\begin{equation}
\begin{cases}
u(0, t) = t = b(t), 
u_x\left(\frac{\pi}2\right, t) = a(t) = \pi
\end{cases}
\Rightarrow
\begin{cases}
a(t) = \pi, \\
b(t) = t,
\end{cases}
\end{equation}
т. е. $U = \pi x + t$. Подставляя, получаем задачу на $v$:
\begin{equation}
\begin{cases}
v_{tt} = 4v_{xx}, \\
v(0, t) = v_x\left(\frac{\pi}2, t\right) = 0, \\
v(x, 0) = 2\sin5x, \\
v_t(x, 0) = 0.
\end{cases}
\end{equation}
Собственные значения и собственные функции ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = (2n + 1)^2, \\
X_n = \sin(2n + 1)x, \\
T_n = C_{1n}\sin2(2n + 1)t + C_{2n}\cos2(2n + 1)t.
\end{cases}
\end{equation}
Ищем решение в виде ряда по $X_n(x)T_n(t)$, подставляем в начальные условия:
\begin{equation}
u(x, 0) = 2\sin5x = \sum_{n = 0}^{\infty}C_{2n}\sin2(2n + 1)x
\end{equation}
Отсюда получаем:
\begin{equation}
u(x, t) = \pi x + t + 2\sin5x\cos10t
\end{equation}
#+END_EXPORT
** Задача 13.11
#+BEGIN_EXPORT latex
\begin{cases}
u_{tt} = u_{xx} + 3u + \sin t\cos2x, 0 < x < \pi, t > 0, \\
u_x(0, t) = u_x(\pi, t) = 0, t > 0, \\
u(x, 0) = u_t(x, 0) = 0, 0 \leq x \leq \pi.
\end{cases}
#+END_EXPORT
*** Решение
#+BEGIN_EXPORT latex
Собственные значения и собственные функции ЗШЛ:
\begin{equation}
\begin{cases}
\lambda_n = n^2, \\
X_n = \cos nx.
\end{cases}
\end{equation}
Ищем решение в виде
\begin{equation}
u(x, t) = \sum_{n = 0}^{\infty}\cos nx.
\end{equation}
Подставим в задачу, получим систему задач:
\begin{equation}
u''_n = -n^2u_n + 3u_n + f_n, \\
u_n(0) = u'_n(0) = 0.
\end{equation}
При $n \neq 2$ решение этой задачи нулевое. При $n = 2$ получаем задачу:
\begin{equation}
\begin{cases}
u_2'' = -u_2 + \sin t, \\
u_2(0) = u_2'(0) = 0.
\end{cases}
\end{equation}
Ищем частное решение в виде:
\begin{equation}
u_p = at\sin t + bt\cos t.
\end{equation}
Подставив в уравнение, получим:
\begin{equation}
2a\cos t - at\sin t - 2b\sin t - bt\cos t = -at\sin t - bt\cos t + \sin t.
\end{equation}
Откуда
\begin{equation}
\begin{cases}
a = 0, \\
b = -\frac12,
\end{cases}
\end{equation}
поэтому решение уравнения имеет вид:
\begin{equation}
u_2(t) = -\frac12t\cos t + C_1\cos t + C_2\sin t
\end{equation}
Подставим начальные условия:
\begin{equation}
u_2(0) = 0 \Rightarrow C_1 = 0, \\
u_1(0) = 0 \Rightarrow C_2 = \frac12.
\end{equation}
Тогда
\begin{equation}
u_2(t) = \frac12(\sin t - t\cos t)
\end{equation}
и
\begin{equation}
u(x, t) = \frac12(\sin t - t\cos t)\cos2x
\end{equation}
#+END_EXPORT
