#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{esint}
#+LATEX_HEADER:\usepackage[english,russian]{babel}
#+LATEX_HEADER:\usepackage{mathtools}
#+LATEX_HEADER:\usepackage{amsthm}
#+OPTIONS: toc:nil
#+LATEX_HEADER:\usepackage[top=0.8in, bottom=0.75in, left=0.625in, right=0.625in]{geometry}

#+BEGIN_EXPORT latex
\begin{equation}
\begin{cases}
u_x = v_{\xi}\xi_x + v_{\eta}\eta_x, \\
u_y = v_{\xi}\xi_y + v_{\eta}\eta_y, \\
u_{xx} = v_{\xi\xi}\xi_x^2 + 2v_{\xi\eta}\xi_x\eta_x + v_{\eta\eta}\eta_x^2 + v_{\xi}\xi_{xx} + v_{\eta}\eta_{xx}, \\
u_{yy} = v_{\xi\xi}\xi_y^2 + 2v_{\xi\eta}\xi_y\eta_y + v_{\eta\eta}\eta_y^2 + v_{\xi}\xi_{yy} + v_{\eta}\eta_{yy}, \\
u_{xy} = v_{\xi\xi}\xi_x\xi_y + v_{\xi\eta}(\xi_x\eta_y + \xi_y\eta_x) + v_{\eta\eta}\eta_x\eta_y
+ v_{\xi}\xi_{xy} + v_{\eta}\eta_{xy} \\
\alpha = \xi + \eta, \\
\beta = \xi - \eta, \\
\end{cases}
\end{equation}
#+END_EXPORT

* Задача 1.11
Классифицировать уравнение
#+BEGIN_EXPORT latex
\begin{equation}
x^2u_{xx} - y^2u_{yy} = 0.
\end{equation}
#+END_EXPORT

Характеристическое уравнение:
#+BEGIN_EXPORT latex
\begin{equation}
x^2(dy)^2 - y^2(dx)^2 = (xdy + ydx)(xdy - ydx) = 0
\end{equation}
откуда уравнение является уравнением гиперболического типа
\begin{equation*}
\begin{cases}
xdy = ydx \Rightarrow \frac{dy}y = \frac{dx}x \Rightarrow y = Cx, \forall C \\
xdy = -ydx \Rightarrow \frac{dy}y = -\frac{dx}x \Rightarrow y = \frac{C}x, x \neq 0, y \neq 0, C \neq 0,
\end{cases}
\end{equation*}
т. е.
\begin{equation*}
\begin{cases}
\xi = \frac{y}x, \\
\eta = xy, \\
\xi_x = -\frac{y}{x^2}, \\
\xi_y = \frac1x, \\
\xi_{xx} = \frac{2y}{x^3}, \\
\eta_x = y, \\
\eta_y = x, \\
\end{cases}
\end{equation*}
Подставляя эти выражения в (1) и (2), получаем первую каноническую форму:
\begin{equation}
x^2\left(v_{\xi\xi}\frac{y^2}{x^4} + 2v_{\xi\eta}\left(-\frac{y^3}x\right) + v_{\eta\eta}y^2\right) -
y^2\left(v_{\xi\xi}\frac1{x^2} + 2v_{\xi\eta} + v_{\eta\eta}x^2\right) = -2v_{\xi\eta}(x^2y + y^2) = 0
\end{equation}
#+END_EXPORT

* Задача 1.14
Классифицировать уравнение
#+BEGIN_EXPORT latex
\begin{equation}
y^2u_{xx} + 2xyu_{xy} + x^2u_{yy} = 0.
\end{equation}
#+END_EXPORT

Выпишем характеристическое уравнение:
#+BEGIN_EXPORT latex
\begin{equation}
y^2(dy)^2 - 2xydxdy + x^2(dx)^2 = (ydy - xdx)^2 = 0.
\end{equation}
$D = 0 \Rightarrow$ уравнение параболического типа. Первый интеграл:
\begin{equation*}
ydy - xdx = 0 \Rightarrow ydy = xdx \Rightarrow y^2 - x^2 = C.
\end{equation*}
Выберем $\xi$ и $\eta$:
\begin{equation}
\begin{cases}
\xi = y^2 - x^2, \\
\xi_x = -2x, \\
\xi_y = 2y, \\
\xi_{xx} = -2, \\
\xi_{yy} = 2, \\
\eta = x, \\
\eta_x = 1.
\end{cases}
\end{equation}
Подставляя эти выражения в (1) и (5), получаем первую каноническую форму:
\begin{multline}
y^2(v_{\xi\xi}\cdot4x^2 + 2v_{\xi\eta}(-2x) + v_{\eta\eta} - 2v_{\xi}) + 2xy(v_{\xi\xi}(-4xy) +
v_{\xi\eta}2y) + x^2(v_{\xi\xi}\cdot4y^2 + v_{\xi}\cdot2) = \\
= -8v_{\xi\eta}xy^2 + 2v_{\xi}(x^2 - y^2) = 0
\end{multline}
#+END_EXPORT

* Задача 1.8
Классифицировать уравнение
#+BEGIN_EXPORT latex
\begin{equation}
yu_{xx} + xu_{yy} = 0
\end{equation}
Выпишем характеристическое уравнение:
\begin{equation}
y(dy)^2 + x(dx)^2 = 0 \Rightarrow \left(\frac{dy}{dx}\right)^2 = -\frac{x}y.
\end{equation}
Возможны три случая.

При $\frac{x}y < 0$ уравнение является уравнением гиперболического типа:
\begin{equation*}
\begin{cases}
\sqrt{y}dy = -\sqrt{-x}d(-x) \Rightarrow \sqrt{y^3} + \sqrt{-x^3} = C, \\
\sqrt{y}dy = \sqrt{-x}d(-x) \Rightarrow \sqrt{y^3} - \sqrt{-x^3} = C.
\end{cases}
\end{equation*}
(в случае $x > 0, y < 0$ $x$ и $y$ меняются местами).

Откуда
\begin{equation}
\begin{cases}
\xi = y^{\frac32} + (-x)^{\frac32}, \\
\eta = y^{\frac32} - (-x)^{\frac32}, \\
\alpha = y^{\frac32}, \\
\beta = (-x)^{\frac32}, \\
\alpha_y = \frac32\sqrt{y}, \\
\alpha_{yy} = \frac3{4\sqrt{y}}, \\
\beta_x = \frac32\sqrt{-x}, \\
\beta_{xx} = \frac3{4\sqrt{-x}}.
\end{cases}
\end{equation}
Подставляя это в (1) и в (9), получаем вторую каноническую форму:
\begin{multline}
y\left(v_{\beta\beta}\left(-\frac{9}{4x}\right) + v_{\beta}\frac3{4\sqrt{-x}}\right) +
x\left(v_{\alpha\alpha}\frac{9}{4y} + v_{\alpha}\frac3{4\sqrt{y}}\right) =
\frac{9x}{4y}v_{\alpha\alpha} + \frac{3x}{4\sqrt{y}}v_{\alpha} + \frac{3y}{4\sqrt{-x}}v_{\beta} -
\frac{9y}{4x}v_{\beta\beta} = 0
\end{multline}

При $\frac{x}y > 0$ уравнение является уравнением эллиптического типа:
\begin{equation*}
\sqrt{y}dy = \pm i\sqrt{x}dx \Rightarrow \sqrt{y^3} \pm i\sqrt{x^3} = C.
\end{equation*}
(в случае $x < 0, y < 0$ нужно заменить $x$ и $y$ на $-x$ и $-y$ соответственно).

Откуда
\begin{equation}
\begin{cases}
\xi = \sqrt{y^3}, \\
\eta = \sqrt{x^3}, \\
\xi_y = \frac3{2}\sqrt{y}, \\
\xi_{yy} = \frac3{4\sqrt{y}}, \\
\eta_x = \frac3{2}\sqrt{x}, \\
\eta_{xx} = \frac3{4\sqrt{x}}.
\end{cases}
\end{equation}
Подставляя в (1) и (9), получаем первую каноническую форму:
\begin{equation}
\frac{9x}{4y}v_{\xi\xi} + \frac{3x}{4\sqrt{y}}v_{\xi} + \frac{3y}{4\sqrt{x}}v_{\eta} - \frac{9y}{4x}v_{\eta\eta} = 0
\end{equation}

Наконец на прямых $x = 0, y \neq 0$ и $x \neq 0, y = 0$ уравнение является уравнением параболического типа.
При $x = 0, y \neq 0$:
\begin{equation}
y(dy)^2 = 0 \Rightarrow y = C.
\end{equation}
Выберем $\xi$ и $\eta$:
\begin{equation}
\begin{cases}
\xi = x, \\
\eta = y, \\
\xi_x = 1, \\
\eta_y = 1.
\end{cases}
\end{equation}
Подставляя в (1) и (9), получим первую каноническую форму:
\begin{equation}
yv_{\xi\xi} + xv_{\eta\eta} = 0
\end{equation}
#+END_EXPORT

* Задача 1.19
Классифицировать уравнение:
#+BEGIN_EXPORT latex
\begin{equation}
u_{xx} + 2u_{xy} + u_{x} + u_{y} + u = 0
\end{equation}
Выпишем характеристическое уравнение:
\begin{equation}
(dy)^2 - 2dxdy = dy(dy - 2dx) = 0
\end{equation}
Получаем, что уравнение является уравнением гиперболического типа и находим $\xi$ и $\eta$:
\begin{equation}
\begin{cases}
\xi = y, \\
\eta = y - 2x, \\
\alpha = y - x, \\
\beta = x, \\
\alpha_x = -1, \\
\alpha_y = 1, \\
\beta_x = 1.
\end{cases}
\end{equation}
Подставляя в (1) и (18), получаем вторую каноническую форму:
\begin{equation}
(v_{\alpha\alpha} - 2v_{\alpha\beta} + v_{\beta\beta}) + 2(v_{\alpha\alpha}(-1) + v_{\alpha\beta}) +
(v_{\alpha}(-1) + v_{\beta}) + v_{\alpha} + v = -v_{\alpha\alpha} + v_{\beta\beta} + v_{\beta} + v = 0
\end{equation}
#+END_EXPORT

* Задача 1.23
Классифицировать уравнение:
#+BEGIN_EXPORT latex
\begin{equation}
3u_{xx} + u_{xy} + 3u_x + u_y - u + y = 0
\end{equation}
Выпишем характеристическое уравнение:
\begin{equation}
3(dy)^2 - dxdy = dy(3dy - dx) = 0.
\end{equation}
Из него видим, что уравнение гиперболического типа и находим $\xi$ и $\eta$:
\begin{equation}
\begin{cases}
\xi = y, \\
\eta = 3y - x, \\
\xi_y = 1, \\
\eta_x = -1, \\
\eta_y = 3.
\end{cases}
\end{equation}
Подставляя это в (1) и в (22), получаем первую каноническую форму:
\begin{equation}
3v_{\eta\eta} + (-v_{\xi\eta} - v_{\eta\eta}) + 3(-v_{\eta}) + (v_{\xi} + 3v_{\eta}) - v + y =
-v_{\xi\eta} + v_{\xi} + 2v_{\eta\eta} - v + y = 0
\end{equation}
#+END_EXPORT

